<?php echo $this->render("layout/header_layui.phtml");?>
<body>
    <div class="layui-fluid wrapper">
        <div class="layui-row layui-col-space30">
            <div class="items-wrap wrap-bg space-top mian-h">
                <!-- titile begin -->
              <div class="layui-tab layui-tab-brief">
                    <ul class="layui-tab-title">
                        <li ><a href="<?php echo $listUrl;?>">活动列表</a></li>
                        <li class="layui-this"><a href="<?php echo $addUrl;?>"><?php echo $info['id']?'编辑':'添加'; ?>活动</a></li>
                    </ul>
                </div>
                <!-- titile end  -->
                <div class="temp-upload-wrap">
                <form class="layui-form" action="<?php echo $addPostUrl;?>" method="POST"  id="addForm">
                    <input name="token" type="hidden"  value="<?php  echo $token;  ?>" />
                    <input name="id" id="id" type="hidden"  value="<?php  echo $info['id'];  ?>" />
                    <div class="layui-form-item">
                        <label class="layui-form-label">活动标题</label>
                        <div class="layui-input-inline">
                            <input type="text" name="title" lay-verify="required" placeholder="请输入标题" class="layui-input" value="<?php  echo $info['title'];  ?>">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">抽奖次数</label>
                        <div class="layui-input-inline">
                            <input type="text" name="limit_num" lay-verify="number" placeholder="请输入抽奖次数" class="layui-input" value="<?php  echo $info['limit_num'];  ?>">
                            <select id="type"  name="limit_type" lay-verify="required" lay-search >
								<?php foreach($limitType as $k1=>$v1){ ?>
                                    <option value="<?php echo $k1; ?>"  <?php if( $info['limit_type']==$k1 ){ ?> selected <?php } ?> ><?php echo $v1; ?></option>
								<?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">活动状态</label>
                        <div class="layui-input-inline">
                            <input type="checkbox" 　<?php echo $info['status'] ? ' checked=""' : ''; ?>  name="status"
                                   lay-skin="switch" lay-filter="switchStatus" lay-text="开启|关闭">
                        </div>
                    </div>
                    <div class="layui-form-item ">
                        <label class="layui-form-label">有效时间</label>
                        <div class="layui-input-inline">
                            <input type="hidden" name="start_time" class="start_time" class="layui-input" value="<?php echo $info['start_time'];?>">
                            <input type="hidden" name="end_time" class="end_time" class="layui-input" value="<?php echo $info['end_time'];?>">
                            <input type="text" name="date" class="layui-input" id="date" placeholder="有效时间" value="<?php echo $info['start_time'];?> - <?php echo $info['end_time'];?>">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">活动说明</label>
                        <div class="layui-input-inline">
                            <textarea id="desc" name="desc" style="width:1000px;height:240px;" placeholder="请输入内容" class="layui-textarea"><?php echo $info['desc']; ?></textarea>
                        </div>
                    </div>
                    <hr class="layui-bg-gray">
                    <div class="layui-form-item">
                        <label class="layui-form-label">活动配置</label>
                        <div class="layui-input-block">
                            <table class="layui-table">
                                <thead>
                                <tr>
                                    <th>序号</th>
                                    <th>奖品图片</th>
                                    <th>奖品名称</th>
                                    <th>剩余库存</th>
                                    <th>权重</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody>
								<?php if($info['conf_rel_list']){?>
									<?php foreach ($info['conf_rel_list'] as $key=>$conf){?>
                                        <tr>
                                            <input class="layui-input" type="hidden" name="position[]" value="<?php echo $key+1 ?>">
                                            <td><?php echo $key+1; ?></td>
                                            <td><img src="<?php echo $conf['icon']; ?>" width="100px" height="100px"></td>
                                            <td><?php echo $conf['title']; ?></td>
                                            <td><?php echo $conf['left_num']; ?></td>
                                            <td><input class="layui-input" type="text" lay-verify="required" name="rate[]" value="<?php echo $conf['rate']; ?>"></td>
                                            <td><a class="link-delete" data-name="actvity_rel_conf" data-activity_rel_id="<?php echo $conf['activity_rel_id']; ?>">删除</a>
                                                <input class="layui-input" type="hidden" name="activity_rel_id[]" value="<?php echo $conf['activity_rel_id']; ?>">
                                                <input class="layui-input" type="hidden" name="goods_id[]" value="<?php echo $conf['goods_id']; ?>">
                                            </td>
                                        </tr>
									<?php }?>
								<?php }?>
                                </tbody>
                            </table>
                        </div>
                        <div class="layui-input-block">
                            <button class="layui-btn layui-btn-small" type="button"   data-name="flow_conf">
                                <i class="layui-icon">&#xe654;</i>
                            </button>
                        </div>
                    </div>
                    <hr class="layui-bg-gray">
                    <div class="layui-form-item">
                        <div class="layui-input-block">
                            <button class="layui-btn layui-btn-big layui-btn-normal" type="button" lay-submit lay-filter="formTest">立即提交</button>
                            <button class="layui-btn layui-btn-big layui-btn-primary cannel" type="button">取消</button>
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</body>

<link media="all" rel="stylesheet" type="text/css" href="<?php echo $staticPath; ?>/js/umeditor/themes/default/css/umeditor.css" />
<!--<script type="text/javascript" src="--><?php //echo $staticPath; ?><!--/js/umeditor/third-party/jquery.min.js"></script>-->
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/umeditor/third-party/template.min.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/umeditor/umeditor.config.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/umeditor/umeditor.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/umeditor/lang/zh-cn/zh-cn.js"></script>
<!--<script type="text/javascript" src="<?php /*echo $staticPath; */?>/js/common/jquery.cookie.js"></script>-->

<script>
;(function(){
    var goodsType = '<?php echo json_encode($goodsType)?>';
    layui.use('layer', function(){
        var $ = layui.jquery, layer = layui.layer; //独立版的layer无需执行这一句
        $(".layui-btn-small").click(function(){
            var that = $(this);
            var tmp = '<option value="">请选择</option>';
            goodsTypeList = JSON.parse(goodsType);
            $.each(goodsTypeList,function (key,value){
                tmp+='<option value='+key+'>'+value+'</option>';
            });
            content ='<div class="layui-form" style="margin-top: 20px;">' +
                '<div class="layui-form-item"><label class="layui-form-label">商品分类</label>' +
                '<div class="layui-input-inline">' +
                '<select id="goods_type"  name="goods_type"  lay-search lay-filter="goods_type" style="z-index: 9999"> ' +
                tmp+
                '</select>'+
                '</div></div>'+
                '<div class="layui-form-item"><label class="layui-form-label">商品</label>' +
                '<div class="layui-input-inline">' +
                '<select id="goods_id"  name="goods_id"  lay-search lay-filter="goods_id" > </select>'+
                '</div></div>'+
                '</div>'
            //示范一个公告层
            layer.open({
                type: 1
                ,title: '活动配置'
                ,area: ['500px', '300px']
                ,shade: 0.8
                ,id: 'layuipro' //设定一个id，防止重复弹出
                ,btn: ['确定', '关闭']
                ,btnAlign: 'c'
                ,content: content
                ,success: function(layero){
                    var btn = layero.find('.layui-layer-btn');
                }
                ,yes: function(index, layero){
                    getGoodsDetail(that);
                }
            });
            renderLayuiForm();
        });
    });

    //实例化编辑器
    var um = UM.getEditor('desc',{
        'imageUrl': "<?php echo $uploadDescImgUrl; ?>?token="+token, //图片上传提交后台对应的地址
        // toolbar:['source','insertcode',],
    });

    //取消按钮
    $(".cannel").click(function(){
             window.location.href= baseurl +'<?php echo $listUrl;?>';
     });

    layui.use('laydate', function(){
        var laydate = layui.laydate;
        laydate.render({
            elem: '#date'
            ,range: true
            ,done: function(value, date, endDate){
                $('.start_time').val(date.year+'-'+date.month+'-'+date.date);
                $('.end_time').val(endDate.year+'-'+endDate.month+'-'+endDate.date);
            }
        });
    });
    //form 表单 提交
    layui.use('form', function(){
        var form = layui.form;
        form.on('select(goods_type)', function(data){
            $.ajax({
                url : baseurl + '<?php echo $getGoodsIdsUrl?>'+'?type='+data.value+'&is_fill=0',
                async: false,
                data : '',
                type : 'GET',
                dataType : '',
                jsonp : 'callback',
                success:function(data){
                    if(data.success){
                        $("#goods_id").empty();
                        var temp='<option value="">全部</option>',list =data.data;
                        for (var key in list) {
                            temp = temp + '<option value="' + key + '" >' + list[key] + '</option>';
                        }
                        $("#goods_id").append(temp);
                        renderLayuiForm();
                    }
                },
                error:function(xhr,msg,e){
                    layer.msg(msg);
                }
            });
        });
        form.on('submit(formTest)', function(data){
            var index = layer.load();
            var jsonData = $("form").serializeArray();
               $.ajax({
                    url : baseurl + '<?php echo $addPostUrl?>',
                    async: false,
                    data : jsonData,
                    type : 'post',
                    dataType : 'json',
                    jsonp : 'callback',
                    success:function(data){
                        layer.msg(data.msg);
                        layer.close(index);
                        if(data.success){
                          setTimeout(function() {
                                window.location.href= baseurl +'<?php echo $listUrl;?>';
                            }, 500);
                            //跳转
                        }
                    },
                    error:function(xhr,msg,e){
                        layer.msg(msg);
                        layer.close(index);
                    }
                });
                return false;  
        }); 
    });


    //删除 表格行
    $(".layui-table").delegate('.link-delete','click',function(){
        var that = $(this);
        layer.confirm('确认是否要删除?', {icon: 3, title:'提示'}, function(i){
            var name = that.attr("data-ad-name");
            var tbody = that.parent().parent().parent();
            var inputs = that.parent().parent().find("input");
            that.parent().parent().remove();
            var tr =tbody.find("tr");
            tr.each(function(index,el){
                $($(this).find("td").get(0)).html(index+1);
                $($(this).find("input").get(0)).val(index+1);
            });
           layer.close(i);
        });

    });

})();

function delActivityConfRel(confRelId,url){
    jsonData ={'token':token,
        'conf_rel_id':confRelId
    };
    $.ajax({
        url : baseurl + url,
        async: false,
        data : jsonData,
        type : 'post',
        dataType : 'json',
        jsonp : 'callback',
        success:function(data){
            if(data.success){
            }
        },
        error:function(xhr,msg,e){
            layer.msg(msg);
        }
    });
    return false;
}

function getGoodsDetail(that) {
    id = $('#goods_id').val();
    if(!id){
        layer.msg('请选择商品');
        return false;
    }
    $.ajax({
        url : baseurl + '<?php echo $getGoodsDetailUrl?>'+'?id='+id,
        async: false,
        data : {},
        type : 'GET',
        dataType : '',
        jsonp : 'callback',
        success:function(data){
            if(data.success){
                addGoods(that,data);
                layer.closeAll();
            }
        },
        error:function(xhr,msg,e){
            layer.msg(msg);
        }
    });
    return true;
}

function addGoods(that,data) {
    var tbody = that.parent().parent().find(".layui-table tbody");
    var temp = '',tr='',list = data.data;
    var index = tbody.find("tr").length+1;
    var content = `<tr>
                    <input class="layui-input" type="hidden" name="position[]" value="`+index+`">
                    <td>`+index+`</td>
                    <td><img src="`+list['icon']+`" width="100px" height="100px"></td>
                    <td>`+list['title']+`</td>
                    <td>`+list['left_num']+`</td>
                    <td><input class="layui-input" type="text" lay-verify="required" name="rate[]" value=""></td>
                    <td><a class="link-delete" data-name="actvity_rel_conf" data-activity_rel_id="0">删除</a>
                    <input class="layui-input" type="hidden" name="activity_rel_id[]" value="0">
                    <input class="layui-input" type="hidden" name="goods_id[]" value="`+list['goods_id']+`">
                    </td>
                </tr>`;
    tbody.append(content);
    renderLayuiForm(); // 重新渲染form
}
//$.cookie('testPhp', '123456' , { path: '/', expires: 10 });
//console.log(getUUID('http://m.vip.com/'));
//console.log($.cookie('testPhp'));
</script>