<?php echo $this->render("./spm/layout/header.phtml");?>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <!-- 头部区域 begin  --> 
    <?php echo $this->render("./spm/layout/topMenu.phtml");?>
    <!-- 头部区域 end   --> 
    
    <!-- content begin   -->
    <div class="content-wrap">
        <!-- leftMenu begin   -->
        <?php echo $this->render("./spm/layout/leftMenu.phtml");?>
        <!-- leftMenu begin   -->
         
        <div class="content-main">
            <div class="wrapper">
                <!-- title begin -->
                <div class="title">
                    <p>推广活动管理</p>
                </div>
                <!-- title end  -->
                <!-- 查询条件 begin -->
                <div class="query-condition">
                    <form class="layui-form">
                        <div class="layui-form-item">
                            <div class="layui-input-inline">
                                <!-- <select name="app_id" lay-verify="" lay-search>
                                    <option value="" >所有应用</option>
                                    <?php foreach($appList as $key=>$value){ ?>
                                        <option value="<?php echo $value['app_id'] ?>" ><?php echo $value['app_name'] ?></option>
                                    <?php } ?>
                                </select> -->
                            </div>
                            <div class="layui-input-inline">
                                <select name="channel_id" lay-verify="" lay-search>
                                    <option value="" >所有渠道</option>
                                    <?php foreach($channelList as $key=>$value){ ?>
                                        <option value="<?php echo $value['id'] ?>" ><?php echo $value['channel_name'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="layui-input-inline">
                                <select name="operator" lay-verify="" lay-search>
                                    <option value="" >所有投放师</option>
                                    <?php foreach($userList as $key=>$value){ ?>
                                        <option value="<?php echo $value['user_name'] ?>" ><?php echo $value['user_name'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="layui-input-inline">
                                <input type="text" name="date" class="layui-input" placeholder="请选择日期" id="date">  
                                <input type="hidden" name="sdate" class="layui-input" value="" >
                                <input type="hidden" name="edate" class="layui-input" value="" > 
                            </div>
                            <div class="layui-input-inline">
                                <input type="text" name="name" placeholder="请输入标题" value=""  class="layui-input" />
                            </div>
                            <div class="layui-input-inline">
                                <input type="text" name="short_link" placeholder="请输入短链标识" value=""  class="layui-input" />
                            </div>
                            <div class="layui-input-inline">
                                <button type="button" class="layui-btn layui-btn-normal" lay-submit lay-filter="search">搜索</button>
                            </div>

                            <button id="addActivityBtn"  type="button" class="right layui-btn layui-btn-normal">新建监测活动</button>
                       
                        </div>
                    </form>
                </div>
                <!-- 查询条件 end  -->
                <!-- table begin -->
                <table id="activity_table" lay-filter="activity_table" >
            
                </table>
        
                <script type="text/html" id="barDemo">
                <!--   <a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="detail">查看</a> -->
                    <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
                </script>
                <!-- table end  -->
            </div>
            <input id="copy" type="text" style="opacity:0; filter:alpha(opacity=0); -moz-opacity:0; -khtml-opacity:0; -webkit-opacity:0;  " value="" > 

        </div>
         
    </div>  
    <!-- content end     --> 
</div>
<script>
var activityListUrl = baseurl + "<?php echo $activityListUrl; ?>"; // 列表
var editActivityNameUrl = baseurl + '<?php echo $editActivityNameUrl; ?>'; // 编辑
var layuiTable, table_id = "#activity_table"; // table 渲染对象 ,table 渲染id
var addActivityUrl = baseurl + '<?php echo $addActivityUrl; ?>'; // 新增
// 渲染表格参数
var page = true; // 默认开启分页
var where = { token:token , app_id:JSON.parse(localStorage.app_data).app_id  }; // 默认渲染table的初始条件

// 判断本地缓存是否 有渲染表格参数
if(localStorage.searchData){
    if(window.location.href == JSON.parse(localStorage.searchData).url){
        page = JSON.parse(localStorage.searchData).page;
        where = JSON.parse(localStorage.searchData).where; 
        where.app_id = JSON.parse(localStorage.app_data).app_id;
        // 设置 渠道
        $("select[name='channel_id'] option").each(function(){
            if($(this).val()==where.channel_id){
                $(this).attr("selected","selected");
                return;
            }
        });
        // 设置投放师operator
        $("select[name='operator'] option").each(function(){
            if($(this).val()==where.operator){
                $(this).attr("selected","selected");
                return;
            }
        });
        // 设置日期
        $("#date").val(where.date);
        $("#sdate").val(where.sdate);
        $("#edate").val(where.edate);
        //设置 搜索 标题
        $("input[name='name']").val(where.name); 
    }
}
// 渲染表格表头参数
var cols = [[ 
    // {field: 'id', title: 'ID',  sort: true , },
    {field: 'create_time', title: '创建时间',  sort: true  , }
    ,{field: 'name', title: '活动名称',  sort: true ,style:'cursor: pointer; color:#009688' , edit: 'text'}
    ,{field: 'app_name', title: '投放应用',  sort: true  ,}
    ,{field: 'channel_name', title: '渠道', sort: true , }
    ,{field: 'track_type', title: '追踪方式', sort: true , }
    ,{field: 'api_link', title: '推广链接', event:'setApi_link',style:'cursor: pointer;'}
    ,{field: 'origin_url', title: '下载链接', event:'setOrigin_url',style:'cursor: pointer;' }
    ,{field: 'id_sign', title: '活动标识',  sort: true , style:'text-align: center;',align:'center'}
    ,{field: 'status', title: '状态', sort: true , style:'text-align: center;' ,align:'center' }
    ,{field: 'operator', title: '投放师',  sort: true , style:'text-align: center;',align:'center'}
    ,{field: 'id', title: '操作', align:'center', toolbar: '#barDemo'}
]];

//JavaScript代码区域
layui.use(['element','form','laydate','table'], function(){
    var element = layui.element;
    var form = layui.form;
    var laydate = layui.laydate;
    var table = layui.table;
    layuiTable = layui.table; // 表格渲染对象 -- 
    
    // 初始化 date 插件
    laydate.render({
        elem: '#date' //指定元素
        ,value: ''
        ,range: true
        ,done: function(value, date, endDate){
            var begin = '',end='';
            if(value){
                begin = date.year + "-" + date.month + '-' + date.date; 
                end  = endDate.year + "-" + endDate.month + '-' + endDate.date; 
            }
            $("input[name='sdate']").val(begin);
            $("input[name='edate']").val(end);
        }
    });

    //初始化表格 
    var initTable = {
        elem: table_id,
        where: where,
        url : activityListUrl,
        cols: cols ,
        page: page
    };
    renderTable(table,initTable,null);

    //监听单元格编辑
    table.on('edit(activity_table)', function(obj){
        var value = obj.value //得到修改后的值
        ,data = obj.data //得到所在行所有键值
        ,field = obj.field; //得到字段
        var arr = new Object();
        arr.token = token ;
        arr.id = data.id;
        arr.name = value;
        $.ajax({
            url : editActivityNameUrl ,
            async: false,
            data : arr,
            type : 'post',
            dataType : 'json',
            jsonp : 'callback',
            success:function(data){    
                if(data.success){
                    layer.msg("操作成功"); 
                }else{
                    layer.msg(data.msg); 
                }
            },
            error:function(xhr,msg,e){
                layer.msg(msg); 
            }
        });
    });

    //监听单元格事件
    table.on('tool(activity_table)', function(obj){
        var data = obj.data;
        // 复制事件
        var copy =document.getElementById("copy");
        if(obj.event === 'setApi_link' || obj.event === 'setOrigin_url' ){
            if(obj.event === 'setApi_link'){
                $("#copy").val(data.api_link); 
            }else if(obj.event === 'setOrigin_url'){
                $("#copy").val(data.origin_url); 
            }
            copy.select(); // 选择对象
            document.execCommand("Copy"); // 执行浏览器复制命令 */
            layer.msg("复制到剪切板");
        }
        //  -- 查看 ， 编辑
        if(obj.event === 'edit'){
            window.location.href = baseurl + '<?php echo $addActivityUrl; ?>?id='+ data.id; 
        }
    });

    //监听搜索按钮
    form.on('submit(search)', function(data){
        var field = data.field;
        field.app_id = $("select[name='app_id']").find("option:selected").val();
        field.token = token;
        var params = {
            elem: table_id,
            url : activityListUrl,
            where: field,
            cols: cols,
            page: true
         }
        renderTable(table,params,null);
        return false; 
    });

    // 新建监测活动 
    $("#addActivityBtn").click(function(){
        window.location.href = addActivityUrl;
    });
});

//   topMenu 切换app 回调
var appIdSelectChange = {
    callBack:function(id){
        var initTable = {
            elem: table_id,
            where: { token: token ,app_id: id},
            url : activityListUrl,
            cols: cols
        };
        renderTable(layuiTable,initTable,null);
    } 
};
</script>
</body>
</html>
      