<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>新建推广活动组</title>
    <link href="<?php echo $staticPath?>/js/admin/lay/css/layui.css?v=<?php echo $version;?>" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $staticPath?>/css/spm/spm_page.css?v=<?php echo $version;?>" rel="stylesheet" type="text/css"/>
    <script src="<?php echo $staticPath?>/js/admin/lay/layui.js?v=<?php echo $version;?>"></script>
    <script src="<?php echo $staticPath?>/js/common/jquery.js?v=<?php echo $version;?>"></script>
</head>
<body>
    <div class="wrapper">
        <!-- title begin -->
        <div class="title">
            <p>新建推广活动组</p>
        </div>
        <!-- title end  -->
        <!-- 查询条件 begin -->
        <div class="query-condition">
            <form class="layui-form">
                <div class="layui-form-item">
                    <label class="layui-form-label long-label">活动组名称</label>
                    <div class="layui-input-inline">
                        <input type="text" name="" placeholder=""  class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label long-label">应用</label>
                    <div class="layui-input-inline">
                        <div class="layui-input-inline">
                            <select name="app_id" lay-verify="" lay-search>
                                <option value="" >选择应用</option>
                                <?php foreach($appList as $key=>$value){ ?>
                                    <option value="<?php echo $value['app_id'] ?>" ><?php echo $value['app_name'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label long-label">活动组名称</label>
                    <div class="layui-input-inline">
                        <input type="text" name="" placeholder=""  class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-input-block">
                        <button type="button" class="layui-btn layui-btn-normal" lay-submit lay-filter="new">保存</button>
                        <button type="reset" class="layui-btn layui-btn-primary">取消</button>
                    </div>
                </div>
            </form>
        </div>
        <!-- 查询条件 end  -->
    </div>
    
</body>
<script>
var token = '<?php echo $token;?>';
//JavaScript代码区域
layui.use(['element','form'], function(){
    var element = layui.element;
    var form = layui.form;

    //表单提交
    form.on('submit(new)', function(data){
        layer.msg(JSON.stringify(data.field));
        return false;
    });
});

//重新渲染
function renderLayuiFormAndTab(){
	layui.use(['element','form'], function(){
		layui.element.init(); 
		layui.form.render();
	});
}



</script>
</html>
