<!doctype html>
<html>
<meta charset="utf-8">
<title><?php echo $titlepre;?>磨基广告管理系统后台</title>
<link rel="shortcut icon" href="<?php echo $staticPath;?>/favicon.ico" />
<link href="<?php echo $staticPath?>/css/style.css?v=<?php echo $version;?>" rel="stylesheet" />
<link href="<?php echo $staticPath?>/css/jquery-ui.css?v=<?php echo $version;?>"rel="stylesheet"  />
<link href="<?php echo $staticPath?>/css/star/star.source.css?v=<?php echo $version;?>" rel="stylesheet" />
<script src="<?php echo $staticPath?>/js/common/jquery.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticPath?>/js/common/jquery-ui.min.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticPath?>/js/common/jquery.form.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticPath?>/js/common/common.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticPath;?>/js/admin/layer.js"></script>
<script>
var token = "<?php echo $token;?>";
var baseurl = "<?php echo $adminroot; ?>";
</script>
</head>
<body>
<div class="wrap">

