<!DOCTYPE html>
<html>
<head>
<meta content="text/html;charset=utf-8" http-equiv="Content-Type">
<title><?php echo $titlepre;?>磨基广告管理系统后台</title>
<link rel="shortcut icon" href="<?php echo $staticPath;?>/favicon.ico" />
<link media="screen" href="<?php echo $staticPath;?>/css/reset.css?v=<?php echo $version;?>" rel="stylesheet" type="text/css">
<link media="screen" href="<?php echo $staticPath;?>/css/content.css?v=<?php echo $version;?>" rel="stylesheet" type="text/css">
<link media="screen" href="<?php echo $staticPath;?>/css/jquery-ui.css?v=<?php echo $version;?>" rel="stylesheet" type="text/css">
<link media="screen" href="<?php echo $staticPath;?>/css/table.css?v=<?php echo $version;?>" rel="stylesheet" type="text/css">
<link media="screen" href="<?php echo $staticPath;?>/css/gri.controls.css?v=<?php echo $version;?>" rel="stylesheet" type="text/css">
    
<script src="<?php echo $staticPath;?>/js/common/jquery.js?v=<?php echo $version;?>" type="text/javascript"></script>
<script src="<?php echo $staticPath;?>/js/common/jquery.form.js?v=<?php echo $version;?>" type="text/javascript"></script>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui.min.js?v=<?php echo $version;?>" type="text/javascript"></script>
<script src="<?php echo $staticPath;?>/js/common/core.js?v=<?php echo $version;?>" type="text/javascript"></script>
<script src="<?php echo $staticPath;?>/js/common/validate.js?v=<?php echo $version;?>" type="text/javascript"></script>
<script src="<?php echo $staticPath;?>/js/common/common.js?v=<?php echo $version;?>" type="text/javascript"></script>
<script src="<?php echo $staticPath;?>/js/common/md5.js?v=<?php echo $version;?>" type="text/javascript"></script>
<script  src="<?php echo $staticPath;?>/js/common/float.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticPath;?>/js/common/jquery.cookie.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticPath;?>/js/admin/layer.js"></script>
<script>
var token = "<?php echo $token;?>";
var baseurl = "<?php echo $adminroot; ?>";
//layer.use("<?php echo $staticPath;?>/js/common/layer.ext.js");
</script>
</head>
<body>