<!DOCTYPE html>
<html>
<head>
<meta content="text/html;charset=utf-8" http-equiv="Content-Type">
<title><?php echo $titlepre ?>子客投放系统</title>
<link rel="shortcut icon" href="<?php echo $staticAdvertiserPath;?>/favicon.ico" />
<link href="<?php echo $staticAdvertiserPath;?>/css/reset.css?v=<?php echo $version;?>" rel="stylesheet" />
<link href="<?php echo $staticAdvertiserPath;?>/css/style.css?v=<?php echo $version;?>" rel="stylesheet" />
<link href="<?php echo $staticAdvertiserPath;?>/css/layout.css?v=<?php echo $version;?>" rel="stylesheet" />
<link href="<?php echo $staticAdvertiserPath;?>/css/jquery-ui.css?v=<?php echo $version;?>" rel="stylesheet"  />
<link href="<?php echo $staticAdvertiserPath;?>/css/star/star.source.css?v=<?php echo $version;?>" rel="stylesheet" />
<link href="<?php echo $staticAdvertiserPath;?>/css/advertiser.css?v=<?php echo $version;?>" rel="stylesheet" />
<script src="<?php echo $staticAdvertiserPath;?>/js/common/jquery.js??v=<?php echo $version;?>"></script>
<script src="<?php echo $staticAdvertiserPath;?>/js/common/jquery-ui.min.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticAdvertiserPath;?>/js/common/jquery.form.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticAdvertiserPath;?>/js/common/common.js?v=<?php echo $version;?>"></script>
<script>
var token = "<?php echo $token; ?>";
var baseurl = "<?php echo $webRoot;?>";
</script>
</head>
<body>
    <div class="colMain clearfix" >

