<?php echo $this->render("layout/header_layui.phtml");?>
<div class="items-wrap wrap-bg wrapper">
    <div class="items-main-title">
        <p><?php echo $result['id']?"编辑":"添加"; ?>落地页模板</p> 
    </div>
    <!-- 表单 begin -->
    <div class="items-main-form-wrap">
        <form class="layui-form" action="<?php echo $addPostUrl; ?>" method="POST"  id="addFrom" >
            <input name="token" value="<?php echo $token;?>" type="hidden" />
            <input type="hidden" name="id"   id=""  value='<?php echo $result['id']; ?>' />
            <input type="hidden" name="action"   id=""  value='<?php echo $result['action']; ?>' />
            <div class="layui-form-item">
                <label class="layui-form-label">模板类型</label>
                <div class="layui-input-block">
                    <?php if($result['type'] ==''){?>
                        <input type="radio" lay-filter="template_type" value="1" title="动态模板" name="type" class="radio" >
                        <input type="radio" lay-filter="template_type" value="2" title="静态模板" name="type" class="radio" checked>
                    <?php }else{ ?>
                        <input type="radio" lay-filter="template_type" value="1" title="动态模板" name="type" class="radio" <?php echo  $result['type'] == 1?' checked':''; ?>>
                        <input type="radio" lay-filter="template_type" value="2" title="静态模板" name="type" class="radio" <?php echo  $result['type'] == 2?' checked':''; ?>>
                    <?php }?>
                </div>
            </div>

            <?php if($result['type'] == ''|| $result['type']== 2 ){?>
            <div id="app_id_select" class="layui-form-item" style="display:block;">
            <?php }else{ ?>
            <div id="app_id_select" class="layui-form-item" style="display:none;">
            <?php } ?>
                <label class="layui-form-label">选择应用</label>
                <div class="layui-input-inline">
                    <select id="app_id" name="app_id" lay-filter="app_id" lay-verify="required" lay-search >
                        <option value="" selected="">请选择</option>
                        <?php if($appList){?>
                            <?php foreach ($appList as $item){ ?>
                                <option value="<?php echo $item['app_id'] ?>" <?php if ($result['app_id'] ==$item['app_id']){?>SELECTED<?php } ?> ><?php echo $item['app_name'] ?><?php echo $item['platform']==1?"(Android)":"(IOS)"; ?></option>
                            <?php }?>
                        <?php }?>
                    </select>
                </div>
            </div>
            <div class="layui-form-item">
                <label class="layui-form-label">上传模板</label>
                <div class="layui-input-inline">
                    <div id="zipId"  style="margin-left:200px;">
                        <input type="hidden" name="zip" id="zip" value="<?php echo  $result['zip'] ; ?>">
                    </div>
                    <div id="zipuploaddiv">
                        <iframe name="upload" src="<?php echo $uploadTemplateZipUrl.'/?otherId=zipId';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no">                                         
                        </iframe>
                    </div>
                </div>
                <div class="layui-form-mid layui-word-aux">(zip压缩包)</div>
            </div>

            <?php if($result['name']!=''){?>
            <div id="temp_name" class="layui-form-item" style="display:block;">
            <?php }else{ ?>
            <div id="temp_name" class="layui-form-item" style="display:none;">
            <?php } ?>
                <label class="layui-form-label">模板名称</label>
                <div class="layui-input-inline">
                    <input type="text" value="<?php echo $result['name']; ?>" name="name" autocomplete="off" class="layui-input" disabled>
                </div>
            </div>
            
            <?php if($result['type'] == ''|| $result['type']== 2 ){?>
            <div class="layui-form-item" id="create_temp" style="display:none;">
            <?php }else{ ?>
            <div class="layui-form-item" id="create_temp" style="display:block;" >
            <?php } ?>
                <label class="layui-form-label">上传创建模板</label>
                <div class="layui-input-inline">
                    <div id="createZipId"  style="margin-left:200px;">
                        <input type="hidden" name="create_zip" id="create_zip" value="<?php echo  $result['create_zip'] ; ?>">
                    </div>
                    <div id="createzipuploaddiv" >
                        <iframe name="upload" src="<?php echo $uploadTemplateZipUrl.'/?otherId=createZipId';?>" style="height:50px;width:100%;" frameborder="0" scrolling="no">                                         
                        </iframe>
                    </div>
                </div>
                <div class="layui-form-mid layui-word-aux">(zip压缩包)</div>
            </div>

            <?php if($result['create_name']!=''){?>
            <div id="createtemp_name" class="layui-form-item" style="display:block;">
            <?php }else{ ?>
            <div id="createtemp_name" class="layui-form-item" style="display:none;">
            <?php } ?>
                <label class="layui-form-label">创建模板名称</label>
                <div class="layui-input-inline">
                    <input type="text" value="<?php echo $result['create_name']; ?>" name="create_name" autocomplete="off" class="layui-input" disabled>
                </div>
            </div>
           
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <button type="button" data-id="<?php echo $result['id']; ?>" id="goback" type="reset" class="layui-btn layui-btn-primary">返回</button>
                    <button type="button" lay-submit lay-filter="submit_form" class="layui-btn submit">立刻提交</button>
                </div>
            </div>

        </form>
    </div>
</div>
<script type="text/javascript">
var addPostUrl = baseurl + '<?php echo $addPostUrl; ?>';  // 表单提交
var listUrl = baseurl + '<?php echo $listUrl; ?>'; // 列表页面
var page = getQueryString('page');
var app_id = getQueryString('app_id');
var name = getQueryString('name');
var type = getQueryString('type');
var screatedate = getQueryString('screatedate');
var ecreatedate = getQueryString('ecreatedate');
var id = '<?php echo $result['id']; ?>';

layui.use(['form','element'], function(){
    var element = layui.element;
    var form = layui.form;

    // 模板类型切换
    form.on('radio(template_type)', function(data){
        if(data.value==1){ // 动态模板
            $("#app_id_select").hide();
            $("#create_temp").show();
        }else{ // 静态模板
            $("#app_id_select").show();
            $("#create_temp").hide();
        }
    }); 

    // 表单提交
    form.on('submit(submit_form)', function(data){
        var type = $("input[name='type']:checked").val();
        var isUpload = false;
        if(!$("#zip").val()){
            layer.msg("请上传模板"); 
            isUpload = true;
        }
        if(type==1){
            if(!$("#create_zip").val()){
                layer.msg("请上传创建模板"); 
                isUpload = true;
            }
        }
        if(!isUpload){
            var index = layer.load();
            $.ajax({
                url : addPostUrl ,
                async: false,
                data : data.field,
                type : 'post',
                dataType : 'json',
                jsonp : 'callback',
                success:function(data){
                    layer.close(index); 
                    layer.msg(data.msg); 
                    if(data.success){
                        setTimeout(function(){
                            window.location.href = listUrl + "?page="+page+"&app_id="+app_id+"&name="+name+"&type="+type+"&screatedate="+screatedate+"&ecreatedate="+ecreatedate;
                        },500);
                    }
                },
                error:function(xhr,msg,e){
                    layer.close(index); 
                    layer.msg(msg); 
                }
            });
        }
        return false;
    });

   // 返回
   $("#goback").click(function(){
        var id = $(this).attr("data-id");
        window.location.href = listUrl + "?id="+id+"&page="+page+"&app_id="+app_id+"&name="+name+"&type="+type+"&screatedate="+screatedate+"&ecreatedate="+ecreatedate;
   });



});

// 上传模板成功回调
function showTemplateZipAttach(id, imgsrc, value, name){
    if(id=="createZipId"){
        $("#createtemp_name").show();
        $("#createtemp_name").find("input[name='create_name']").val(name);
        $("#create_zip").val(value);
    }else{
        $("#temp_name").show();
        $("#temp_name").find("input[name='name']").val(name);
        $("#zip").val(value);
    }
}
</script>