<?php echo $this->render("./spm/layout/header.phtml");?>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <!-- 头部区域 begin  -->
    <?php echo $this->render("./spm/layout/topMenu.phtml");?>
    <!-- 头部区域 end   -->

    <!-- content begin   -->
    <div class="content-wrap">
        <!-- leftMenu begin   -->
        <?php echo $this->render("./spm/layout/leftMenu.phtml");?>
        <!-- leftMenu begin   -->

        <div class="content-main">
            <div class="wrapper">
                <!-- title begin -->
                <div class="title">
                    <p><?php if($payConfig){ echo '编辑';}else{ echo '新建';} ?>监控平台</p>
                </div>
                <!-- title end  -->
                <!-- form begin -->
                <form class="layui-form">
                    <!-- 基本信息 begin -->
                    <p class="padding-top20"></p>
                    <div class="subtitle"><p>基本信息:</p></div>
                    <div class="inputs-wrap">
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">平台编号</label>
                            <div class="layui-input-block long-label-input">
                                <input type="hidden" name="id" value="<?php echo $monitorPlatform['id']; ?>" />
                                <input type="text" name="platform_no" placeholder="" value="<?php echo $monitorPlatform['platform_no']; ?>" class="layui-input" style="width:650px;">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">平台名称</label>
                            <div class="layui-input-block long-label-input">
                                <input type="text" name="name" placeholder="" value="<?php echo $monitorPlatform['name']; ?>" class="layui-input" style="width:650px;">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">平台类型</label>
                            <div class="layui-input-inline">
                                <select name="type" lay-verify=""  lay-filter="type" lay-search>
                                    <option value="" >选择平台类型</option>
                                    <?php foreach($platformType as $key=>$value){ ?>
                                        <option value="<?php echo $key; ?>" <?php if($key==$monitorPlatform['type']){ echo 'selected';} ?> ><?php echo $value; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <p class="padding-top20"></p>
                    <div class="subtitle"><p>接收模板:</p></div>
                    <div class="inputs-wrap">
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">点击接收模版</label>
                            <div class="layui-input-block long-label-input">
                                <input type="text" name="click_template" placeholder="" value="<?php echo $monitorPlatform['click_template']; ?>" class="layui-input" style="width:650px;">
                            </div>
                        </div>
                    </div>
                    <div class="subtitle"><p>回调模板:</p></div>
                    <div class="inputs-wrap">
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">激活回调模版</label>
                            <div class="layui-input-block long-label-input">
                                <input type="text" name="active_callback_template" placeholder="" value="<?php echo $monitorPlatform['active_callback_template']; ?>" class="layui-input" style="width:650px;">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">注册回调模版</label>
                            <div class="layui-input-block long-label-input">
                                <input type="text" name="register_callback_template" placeholder="" value="<?php echo $monitorPlatform['register_callback_template']; ?>" class="layui-input" style="width:650px;">
                            </div>
                        </div>
                    </div>

                    <hr class="layui-bg-gray">
                    <div class="layui-form-item">
                        <div class="layui-input-block">
                            <button type="button" class="layui-btn layui-btn-normal" lay-submit lay-filter="submit_form">保存</button>
                            <button id="cancel" type="reset" class="layui-btn layui-btn-primary">取消</button>
                        </div>
                    </div>
                </form>
                <!-- form end  -->
            </div>
        </div>
        <!-- content end     -->
    </div>
    <script>
        /* 请求链接 */
        var addPlatformPostUrl = baseurl + '<?php echo $addPlatformPostUrl; ?>'; // 提交表单
        var indexUrl = baseurl + '<?php echo $indexUrl; ?>'; //  列表页面
        //JavaScript代码区域
        layui.use(['element','form'], function(){
            var element = layui.element;
            var form = layui.form;

            //表单提交
            form.on('submit(submit_form)', function(data){
                data.field.token = token;
                $.ajax({
                    url : addPlatformPostUrl,
                    async: false,
                    data : data.field,
                    type : 'post',
                    dataType : 'json',
                    jsonp : 'callback',
                    success:function(data){
                        layer.msg(data.msg);
                        if(data.success){
                            setTimeout(function(){
                                window.location.href = indexUrl;
                            },500);
                        }
                    },
                    error:function(xhr,msg,e){
                        layer.msg(msg);
                    }
                });
                return false;
            });
            // 取消
            $("#cancel").click(function(){
                window.location.href = indexUrl;
            });
        });
    </script>
</body>
</html>
