<?php echo $this->render("layout/header1.phtml");?>
<div class="colMain">
    <div class="nav">
	<ul class="cc">
    	<li class="current"><a href="<?php echo $listUrl;?>">旧配置列表</a></li>
		<li><a href="<?php echo $addUrl;?>">添加旧配置</a></li>
	</ul>
	</div>
    <div class="main">
        <div class="toolbar">
            <div class="search fl">
                <form action="<?php echo $listUrl;?>" method="GET"  id="searchForm">     
                <input type="hidden" name="platform" value="<?php echo $search['platform'] ;?>">  
                <div>         
                     <label class="ig_label">平台：</label>
                      <ul class="ip_ul clearfix platform">
                        <li  class="<?php echo ($search['platform'] == '')?'cur':'';?>"  data-platform="">全部</li>
                        <li class="<?php echo ($search['platform'] == 1)?'cur':'';?>" data-platform="1">Android</li>
                        <li class="<?php echo ($search['platform'] == 2)?'cur':'';?>" data-platform="2">IOS</li>
                    </ul>
                    <input type="text" class="iText" name='name'  value='<?php echo $search['name'] ;?>' placeholder="可输入广告商名称查询" />       
                    <input type="submit" class="submit" value="" 　/>
                </div>
                </form>
            </div>
        </div>
        <div class="content">
            <div class="grid">
                <table>
                    <thead>
                        <tr>  
                          <th>平台类型</th>
                            <th>配置项名称</th>
                            <th>应用</th>
                            <th>视频广告商</th>
                            <th>操作</th>       
                        </tr>
                    </thead>
                       <tbody>
                        <?php foreach($list as $k1=>$v1){?>
                        <tr>
                          <td><span class="blue"><?php echo  ($v1['platform']==1)?'Android':'IOS'  ?>  </span></td>
                              <td>
                                 <p><?php echo $v1['app_name']; ?>（<?php echo $v1['app_key']; ?>）</p>
                            </td>
                        	<td><?php echo $v1['name']; ?></td>         
                            <td>
                                    <a href="<?php echo$addUrl;?>/?id=<?php echo $v1['id'];?>" class="mr10">编辑</a>
									<a href="<?php echo $viewUrl;?>/?id=<?php echo $v1['id'];?>" class="mr10">查看</a>
									<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $v1['id'];?>', '', event);"　class="mr10">删除</a>
                            </td>
                        </tr> 
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            <div class="mr10 mt10 cc tc"><?php echo $pager;?></div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(function(){
	$(".platform li").click(function () {
	    $(this).addClass("cur").siblings().removeClass("cur");
	     platform = $(this).attr('data-platform');
	     $("input[name='platform']").val(platform);
	     $("#searchForm").submit()
	});

});
</script>
<?php echo $this->render("layout/footer1.phtml");?>