<?php echo $this->render("./spm/layout/header.phtml");?>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <!-- 头部区域 begin  -->
    <?php echo $this->render("./spm/layout/topMenu.phtml");?>
    <!-- 头部区域 end   -->

    <!-- content begin   -->
    <div class="content-wrap">
        <!-- leftMenu begin   -->
        <?php echo $this->render("./spm/layout/leftMenu.phtml");?>
        <!-- leftMenu begin   -->

        <div class="content-main">
            <div class="wrapper">
                <!-- title begin -->
                <div class="title">
                    <p><?php if($documentType){ echo '编辑';}else{ echo '新建';} ?>文档类型</p>
                </div>
                <!-- title end  -->
                <!-- form begin -->
                <div class="query-condition">
                    <form class="layui-form">
                        <!-- 基本信息 begin -->
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">类型名称</label>
                            <div class="layui-input-block long-label-input">
                                <input type="hidden" name="id" value="<?php echo $documentType['id']; ?>" />
                                <input type="text" name="name" placeholder="" value="<?php echo $documentType['name']; ?>" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">描述</label>
                            <div class="layui-input-block long-label-input">
                                <input type="text" name="description" placeholder="" value="<?php echo $documentType['description']; ?>" class="layui-input">
                            </div>
                        </div>
                        <hr class="layui-bg-gray">
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button type="button" class="layui-btn layui-btn-normal" lay-submit lay-filter="submit_form">保存</button>
                                <button id="cancel" type="reset" class="layui-btn layui-btn-primary">取消</button>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- form end  -->
            </div>
        </div>
        <!-- content end     -->
    </div>
    <script>
        /* 请求链接 */
        var addDocumentTypePostUrl = baseurl + '<?php echo $addDocumentTypePostUrl; ?>'; // 提交表单
        var documentTypeUrl = baseurl + '<?php echo $documentTypeUrl; ?>'; //  列表页面
        //JavaScript代码区域
        layui.use(['element','form'], function(){
            var element = layui.element;
            var form = layui.form;

            //表单提交
            form.on('submit(submit_form)', function(data){
                data.field.token = token;
                $.ajax({
                    url : addDocumentTypePostUrl,
                    async: false,
                    data : data.field,
                    type : 'post',
                    dataType : 'json',
                    jsonp : 'callback',
                    success:function(data){
                        layer.msg(data.msg);
                        if(data.success){
                            setTimeout(function(){
                                window.location.href = documentTypeUrl;
                            },500);
                        }
                    },
                    error:function(xhr,msg,e){
                        layer.msg(msg);
                    }
                });
                return false;
            });
            // 取消
            $("#cancel").click(function(){
                window.location.href = documentTypeUrl;
            });
        });
    </script>
</body>
</html>
