<?php echo $this->render("./spm/layout/header.phtml");?>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <!-- 头部区域 begin  -->
    <?php echo $this->render("./spm/layout/topMenu.phtml");?>
    <!-- 头部区域 end   -->

    <!-- content begin   -->
    <div class="content-wrap">
        <!-- leftMenu begin   -->
        <?php echo $this->render("./spm/layout/leftMenu.phtml");?>
        <!-- leftMenu begin   -->

        <div class="content-main">
            <div class="tabs-wrapper">
                <div class="layui-tab layui-tab-brief" lay-filter="">
                    <ul class="layui-tab-title">
                        <li class="layui-this">API测试</li>
                        <li>IPUA测试</li>
                    </ul>
                    <div class="layui-tab-content">
                        <!-- 归因查询  begin -->
                        <div class="layui-tab-item layui-show layui-anim layui-anim-upbit">
                            <div class="wrapper">
                                <!-- 查询条件 begin -->
                                <div class="query-condition">
                                    <form class="layui-form">
                                        <div class="layui-form-item ">
                                            <div class="layui-input-inline">
                                                <input type="text" lay-verify="required" name="deviceid" placeholder="请输入设备ID" value=""  class="layui-input" />
                                            </div>
                                            <div class="layui-input-inline">
                                                <button type="button" class="layui-btn" lay-submit lay-filter="search">测试</button>
                                            </div>
                                        </div>
                                        <div class="layui-form-item">
                                            <div class="layui-form-mid layui-word-aux">说明：支持通过 idfa ，imei ，idfa 或 imei 加密值</div>
                                        </div>
                                    </form>
                                </div>
                                <!-- 查询条件 end  -->
                                <hr class="layui-bg-gray">
                                <div class="data-result layui-anim layui-anim-up" style="display:none;">
                                    <ul class="layui-timeline" id="data-result-items"> </ul>
                                </div>
                            </div>
                        </div>
                        <!-- 归因查询  end  -->
                        <!-- 清除设备  begin -->
                        <div class="layui-tab-item layui-anim layui-anim-upbit">
                            <div class="wrapper">
                                <!-- 查询条件 begin -->
                                <div class="query-condition">
                                    <form class="layui-form">
                                        <div class="layui-form-item">
                                            <div class="layui-input-inline">
                                                <input type="text" lay-verify="required" name="deviceid" placeholder="请输入设备ID" value=""  class="layui-input" />
                                            </div>
                                            <div class="layui-input-inline">
                                                <button type="button" class="layui-btn" lay-submit lay-filter="cleardevice">测试</button>
                                            </div>
                                        </div>
                                        <div class="layui-form-item">
                                            <div class="layui-form-mid layui-word-aux">说明：支持通过 idfa ，imei ，idfa 或 imei 加密值</div>
                                        </div>
                                    </form>
                                </div>
                                <!-- 查询条件 end  -->
                                <hr class="layui-bg-gray">
                            </div>
                        </div>
                        <!-- 清除设备  end  -->
                    </div>
                </div>

            </div>
        </div>

    </div>
    <!-- content end     -->
</div>
<script>
    layui.use(['element','form'], function(){
        var form = layui.form;
        // 查询设备

    });

    // equipment




</script>
</body>
</html>
