<?php echo $this->render("./spm/layout/header.phtml");?>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <!-- 头部区域 begin  -->
    <?php echo $this->render("./spm/layout/topMenu.phtml");?>
    <!-- 头部区域 end   -->

    <!-- content begin   -->
    <div class="content-wrap">
        <!-- leftMenu begin   -->
        <?php echo $this->render("./spm/layout/leftMenu.phtml");?>
        <!-- leftMenu begin   -->

        <div class="content-main">
            <div class="wrapper">
                <!-- title begin -->
                <div class="title">
                    <p>文档管理</p>
                </div>
                <!-- title end  -->
                <!-- 查询条件 begin -->
                <div class="query-condition">
                    <form class="layui-form">
                        <div class="layui-form-item">
                            <div class="layui-input-inline">
                                <input type="text" name="date" class="layui-input" placeholder="请选择日期" id="date">
                                <input type="hidden" name="sdate" class="layui-input" value="" >
                                <input type="hidden" name="edate" class="layui-input" value="" >
                            </div>
                            <div class="layui-input-inline">
                                <select name="document_type" lay-verify="" lay-search >
                                    <option value="" selected>所有类型</option>
                                    <?php foreach($documentType as $key=>$value){ ?>
                                        <option value="<?php echo $value['id'] ?>" ><?php echo $value['name'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="layui-input-inline">
                                <input type="text" name="name" placeholder="请输入文档名称" value=""  class="layui-input" />
                            </div>
                            <div class="layui-input-inline">
                                <button type="button" class="layui-btn layui-btn-normal" lay-submit lay-filter="search">搜索</button>
                            </div>

                            <div class="layui-input-inline">
                                <button id="documentType" type="button" class="layui-btn layui-btn-normal">文档类型管理</button>
                            </div>

                            <button id="addDocument" type="button" class="right layui-btn layui-btn-normal">上传文档</button>

                        </div>
                    </form>
                </div>
                <!-- 查询条件 end  -->
                <!-- table begin -->
                <table id="activity_table" lay-filter="activity_table" >

                </table>

                <script type="text/html" id="barDemo">
                    <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
                    <a class="layui-btn layui-btn-xs" lay-event="download">下载</a>
                </script>

                <!-- table end  -->
            </div>
            <input id="copy" type="text" style="opacity:0; filter:alpha(opacity=0); -moz-opacity:0; -khtml-opacity:0; -webkit-opacity:0;  " value="" >


        </div>

    </div>
    <!-- content end     -->
</div>
<script>
    /* 请求链接 */
    var addDocumentUrl = baseurl + '<?php echo $addDocumentUrl; ?>'; // 新建，编辑 文档
    var documentTypeUrl = baseurl + '<?php echo $documentTypeUrl; ?>'; // 配置文档类型
    var documentListUrl = baseurl + "<?php echo $documentListUrl; ?>"; // 渲染表格列表

    /* table 渲染参数 */
    var layuiTable;
    var page = true;
    var where = { token: token ,name: '' };
    var table_id = '#activity_table';
    var cols = [[ //表头
        {field: 'id', title: 'ID',  sort: true  }
        ,{field: 'document_type', title: '文档类型',  sort: true }
        ,{field: 'document_name', title: '文档名称',  sort: true }
        ,{field: 'document_format', title: '文件格式',  sort: true }
        ,{field: 'update_time', title: '更新时间',  sort: true }
        ,{field: 'operator', title: '最后编辑人',  sort: true }
        ,{field: 'document_url', title: '操作', align:'center', toolbar: '#barDemo'}
    ]];

    // 判断本地缓存是否 有渲染表格参数
    if(localStorage.searchData){
        if(window.location.href == JSON.parse(localStorage.searchData).url){
            page = JSON.parse(localStorage.searchData).page;
            where = JSON.parse(localStorage.searchData).where;
            // 初始化搜索条件
            $("input[name='name']").val(where.name); //
            $("select[name='document_type'] option").each(function(){
                if($(this).val()==where.document_type){
                    $(this).attr("selected","selected");
                    return;
                }
            });
            // 设置日期
            $("#date").val(where.date);
            $("#sdate").val(where.sdate);
            $("#edate").val(where.edate);
        }
    }

    //JavaScript代码区域
    layui.use(['element','form','laydate','table'], function(){
        var element = layui.element;
        var form = layui.form;
        var laydate = layui.laydate;
        var table = layui.table;
        layuiTable = layui.table;
        // 初始化 date 插件
        laydate.render({
            elem: '#date' //指定元素
            ,value: ''
            ,range: true
            ,done: function(value, date, endDate){
                var begin = '',end='';
                if(value){
                    begin = date.year + "-" + date.month + '-' + date.date;
                    end  = endDate.year + "-" + endDate.month + '-' + endDate.date;
                }
                $("input[name='sdate']").val(begin);
                $("input[name='edate']").val(end);
            }
        });

        //初始化表格
        var initTable = {
            elem: table_id,
            where: where,
            url : documentListUrl ,
            cols: cols ,
            page : page
        };
        renderTable(table,initTable,null);

        //监听搜索按钮
        form.on('submit(search)', function(data){
            var field = data.field;
            field.token = token;
            where = field;
            var params = {
                elem: table_id,
                where: where,
                url : documentListUrl ,
                cols: cols ,
                page : page
            }
            renderTable(table,params,null);
            return false;
        });

        //监听单元格事件  -- 查看 ， 编辑
        table.on('tool(activity_table)', function(obj){
            var data = obj.data;
            if(obj.event === 'edit'){  // 编辑
                window.location.href = addDocumentUrl + "?id="+data.id;
            }else if(obj.event === 'download'){  // 下载
                window.open(data.document_url);
            }
        });

        // 新建渠道
        $("#addDocument").click(function(){
            window.location.href = addDocumentUrl;
        });

        // 新建渠道
        $("#documentType").click(function(){
            window.location.href = documentTypeUrl;
        });
    });
</script>
</body>
</html>
