<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
    <li class="current"><a href="<?php echo $listUrl;?>"><?php echo ($search['is_check'] != '')?'审核':'' ?>用户列表</a></li>
    <?php if($search['is_check'] == ''){?>
		<li><a href="<?php echo $editUrl;?>">添加用户</a></li>
<?php }?>	
	</ul>
</div>
<div id="changeSystemGroup" style="margin: 20px; line-height: 32px; font-size: 14px; display: none">
    <ul class="form">
       <li> 
            <span class="label">请选择权限组：</span>
            <select name="changgegroupid" id="changgegroupid" class="wa">
                <?php foreach($groups as $key=>$value){?>    
                <option value="<?php echo $key?>"><?php echo $value['name']?></option>
                <?php } ?>
            </select>
        </li>
    </ul>
</div>
<form action="<?php echo $listUrl;?>" method="GET" id="searchForm">
	<input type="hidden" class="iText" name="type"  id="type" value="<?php echo $search['type']?>">
    <div class="table_full">
	<table width="100%">
	
             <tr class="tr">
                <th class="th">用户名</th>
                <td class="td"><input type="text" class="iText" name="user_name"  id="user_name" value="<?php echo $search['user_name']?>"></td>
                <th class="th">邮箱</th>
                <td class="td"><input type="text" class="iText" name="email"  id="email" value="<?php echo $search['email']?>"></td>
                <th class="th">权限组</th>
                <td class="td">
                   <select name="group_id"  class="wa" id="group_id">
                        <option value="">全部</option>
                        <?php foreach($groups as $key=>$value){?>    
                        <option value="<?php echo $key?>"  <?php echo  $search['group_id'] == $key?'selected=selected':''?>  ><?php echo $value['name']?></option>
                        <?php } ?>
                    </select>
                </td>
                  <th class="th">用户类型</th>
                     <td class="td">
                   <select name="user_type"  class="wa">
                        <option value="">全部</option>
                        <?php foreach($userType as $key=>$value){?>    
                        <option value="<?php echo $key?>"  <?php echo  $search['user_type'] == $key?'selected=selected':''?>  ><?php echo $value;?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
            <?php if($search['type'] == 'check_list'){?>
            <tr>
               <th class="th">审核状态</th>
            	<td class="td">
                   <select name="is_check"  class="wa">
                        <option value="">全部</option>
                        <option value="0"  <?php echo  $search['is_check'] == '0'?'selected=selected':''?>  >审核中</option>
                        <option value="-1"  <?php echo  $search['is_check'] == '-1'?'selected=selected':''?>  >审核不通过</option>
                    </select>
                </td>
            </tr>
           <?php }?>
        </table>
    </div>
    <div class="mb10 tac"><span class="btn"><span><button type="submit" id="submitForm">搜 索</button></span></span></div>
    </form>
    <div class="table_list">
    <form id="batchForm" action="<?php echo $batchupdategroupUrl;?>" method="post">
        <input name="token" type="hidden" value="<?php echo $token;?>" />
        <input name="action" id="action" type="hidden" value="" />
        <input name="content" id="content"  type="hidden" value="" />
        <div class="h_a">
            <span class="btn2">
               <span><button onclick="changeSystemGroup('修改权限组')" type="button">修改权限组</button></span>
            </span>
            <span>共 <?php echo $total;?> 条结果</span>
        </div>
        <table width="100%">
		<tr class="hd">
                <td><input type="checkbox" onclick="checkAll('.checkbox')"></td>
			<td width="60">UID</td>
			<td>邮箱</td>
			<td>用户类型</td>
			<td>用户名</td>
			<td>用户组</td>
			<td>是否锁定</td>
			  <?php if($search['type'] == 'check_list'){?>
			  	<td>审核状态</td>
			  <?php }?>
			<td>注册时间</td>
			<td>操作</td>
		</tr>
<?php foreach($users as $key => $value) {?>
		<tr class="ct">
                <td><?php if($value['group_id'] != 0){?><input class="checkbox" name="ids[]" value="<?php echo $value['user_id'];?>" type="checkbox"><?php } ?></td>
			<td><?php echo $value['user_id'];?></td>
			<td><?php echo $value['email'];?></td>
			<td><?php echo $userType[$value['user_type']];?></td>
			<td><?php echo $value['user_name'];?></td>
			<td><?php echo $value['group_id'] == 0 ? '超级管理员' : $groups[$value['group_id']]['name'];?></td>
			<td><?php echo ($value['is_lock']==0)?'未锁定':'锁定';?></td>
		    <?php if($search['type'] == 'check_list'){?>
			  <td><?php echo ($value['is_check'] == '0')?'审核中':'审核不通过';?></td>
			<?php }?>  
            <td><?php echo $value['create_time'];?></td>
			<td>
			<a href="<?php echo $value['is_check'] == 1?$editUrl:$checkUrl;?>/?user_id=<?php echo $value['user_id'];?>" class="mr10">编辑</a>
			 <?php if($value['is_check'] ==  1){?>
				<a href="<?php echo $viewUrl;?>/?user_id=<?php echo $value['user_id'];?>" class="mr10">查看</a>
			 <?php }?>
			</td>
		</tr>
<?php } ?>
	</table>
    </form>
</div>
<div class="mr10 cc tc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/common/chosen.jquery.js"></script>
<link   type="text/css" href="<?php echo $staticPath; ?>/css/chosen.css" rel="stylesheet" >
<script type="text/javascript">
    //广告表单数据提交
    $(document).ready(function(){
        ajaxForm('batchForm',function(ret){
            ajaxRedirect(ret, baseurl+'<?php echo $listUrl;?>');
        });
    });
    $("#group_id").change(function(){
    	$("#searchForm").serialize();
    	$("#searchForm").submit();
     })
    //$("form").serialize()
    function changeSystemGroup(title){
        return $("#changeSystemGroup").dialog({
                        title : title,
                        draggable : false,
                        width:600,
                        modal : true,
                        resizable : false,
                        buttons: {
                                '完成': function() {
                                    $('#action').val('changeSystemGroup');
                                    $('#content').val($("#changgegroupid").val());
                                   $("#batchForm").submit();
                                },
                                '取消': function() {
                                    $(this).dialog('close');
                                }
                            }
                    });
    }
</script>
