<?php echo $this->render("layout/header.phtml");?>
<style>
	body,html{ background:#f2f2f2; }
</style>
<link href="<?php echo $staticPath?>/css/page_layout.css?v=<?php echo $version;?>" rel="stylesheet" type="text/css"/>
<body>
	<div class="default-page">
		<div class="main">
            <form method="post" action="<?php echo $passwdPostUrl;?>" id="editUserFrom" autocomplete="off">
                <input name="token" value="<?php echo $token;?>" type="hidden" />
                <div class="main-title">修改密码 <i></i></div>
                <hr class="bg-gray"></hr>
                <ul class="main-list">
                    <li><span>当前密码：</span> <input type="password" autocomplete="off"  placeholder="请输入当前密码" maxlength="20" name="current_password" class="input"></li>
                    <li><span>新密码： </span>  <input type="password"  autocomplete="off"  placeholder="请输入新密码" maxlength="20" name="password" class="input"></li>
                    <li><span>重复密码： </span> <input type="password"  autocomplete="off" placeholder="请输入新密码" maxlength="20" name="r_password" class="input"></li>
                </ul>
                <div class="btns-wrap">
                    <button type="submit" class="btn-submit">保存</button>
                </div>
            </form>
		</div>
	</div>
</body>
</html>
<script type="text/javascript">
//用户表单数据提交
$(document).ready(function(){
    ajaxForm('editUserFrom',function(ret){
    	if (ret) {
    		if (ret.success) {
                layer.msg(ret.msg);
    			setTimeout(function() {
    						logout(baseurl+'/Admin/Index/index');
    					}, 500);
    		} else {
    			layer.msg(ret.msg);
    		}
    	}
    });
})
</script>
