<div id="main" class="ms-mian ms-height">
        <!-- app main top begin -->
        <?php echo $this->render("intergration/flow/layout/top.phtml");?>
        <!-- app main top end   -->

        <!-- app 主页 begin -->
        <div class="items-wrap wrap-bg space-top mian-h" id="main-index" >
            <div class="items-main-title">
                <p>流量配置</p> 
                <button id="newflow" class="layui-btn layui-btn-normal" data->新建流量配置</button>
            </div> 
            <div class="main-nolist">暂无配置</div>
            <table id="main-index-table" class="layui-table">
                <colgroup>
                    <col width="150">
                    <col width="200">
                    <col>
                </colgroup>
                <thead>
                    <tr>
                    <th>ID</th>
                    <th>配置名称</th>
                    <th>配置类型</th>
                    <th>更新时间</th>
                    <th>操作人</th>
                    <th>操作</th>
                    </tr> 
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <!-- app 主页 end -->
</div>
<script>
    ;(function(){
        // 主页 数据 回调
        var mainCallback = {
            success:function(data){
                var app = data.data;
                if(data.success){
                    //初始化 mian 头部 信息
                    $("#main").find(".app-icon img").attr("src",app.icon);
                    $("#main").find(".app-name span").html(app.app_name);
                    $("#main").find(".app-key").html('AppKey：'+app.app_key);
                    $("#main").find(".app-type i").removeClass('ios');
                    $("#main").find(".app-type i").removeClass('android');
                    $("#main").find(".app-type i").addClass(app.platform_class);
                    initTable(app.list,"#main-index-table");
                }else{
                    layer.msg(data.msg); 
                }
            },
            error:function(xhr,msg,e){
                layer.msg(msg); 
            } 
        };

        // 主页初始化
        function initMain(){
           var app_key = getQueryString('app_key');
           if(!app_key){
               var app =  $($(".appList li").get(0));
               $($(".appList li").get(0)).addClass("active");   
               app_key = app.find(".app-title").attr("data-app-key");
               $(".page_app_key").val(app_key);
           }else{
               $(".appList li").removeClass("active"); 
               var applist = $(".appList li");
               applist.each(function(){
                    var appKey = $(this).find(".app-title").attr("data-app-key");
                    if(appKey==app_key){
                         $(this).addClass("active");   
                    }
               });
              
           }
           $(".app-key").attr("data-app-key",app_key);
           var url = baseurl + '<?php echo $flowListUrl;?>?app_key=' + app_key;
           requestAjax({url:url},mainCallback);
        }

        // 流量配置 列表初始化
        function initTable(list,id){
            if(list.length>0){
                var tr = '';
                var tr_class='';
                for(var k in list){
                    if(list[k].conf_type == 1){
                    	tr_class = 'red';
                     }
                     tr = tr + `<tr class="`+tr_class+`">
                        <td><a class="table-btn"  onclick="tableRecordHandle(this,1,`+list[k].id+`)">`+list[k].id+`</a></td>
                        <td>`+list[k].conf_name+`</td>
                        <td>`+list[k].conf_type_name+`</td>
                        <td>`+list[k].update_time+`</td>
                        <td>`+list[k].operator+`</td>
                        <td>
                            <a class="table-btn"  onclick="tableRecordHandle(this,1,`+list[k].id+`)">查看</a>
                            <a class="table-btn"  onclick="tableRecordHandle(this,2,`+list[k].id+`)">编辑</a>
                            <a class="table-btn"  onclick="tableRecordHandle(this,3,`+list[k].id+`)">删除</a>
                        </td>
                    </tr> `;
                }
                $(id).find("tbody").html(tr);
                $(id).show();
                $('.main-nolist').hide();
            }else{
                $(id).find("tbody").html('');
                $(id).hide();
                $('.main-nolist').show();
            }
        };

        // 打开新建 配置页面
        $("#newflow").click(function(){
             //window.href = baseurl;
           var href = window.location.href;
             var param = '';
             if(href.split('?').length>1){
                param = '?'+ href.split('?')[1];
             }
             window.location.href = baseurl +'<?php echo $addUrl;?>'+ param;
        });
        initMain();  // 初始化主页
    })();



    /** 
     *  table 记录操作
     *  @parame type 处理类型 1 查看 ，2 编辑 ，3 删除
     */
    function tableRecordHandle(t,type,id){
        var href = window.location.href;
        var param = '';
        if(href.split('?').length>0){
             param = href.split('?')[1];
        }

        if(type==1){
            location.href = baseurl +'<?php echo $viewUrl;?>?flow_id='+id+ '&'+ param;
        }else if(type==2){
            location.href = baseurl +'<?php echo $addUrl;?>?flow_id='+id +'&'+ param;
        }else{
            //
            layer.confirm('是否确认要删除该配置？', {icon: 3, title:'提示'}, function(index){
                var url = baseurl +'<?php echo $deleteUrl;?>?flow_id='+id
                $.ajax({
                    url : url ,
                    async: false,
                    data : null,
                    type : 'get',
                    dataType : 'json',
                    jsonp : 'callback',
                    success:function(data){
                        layer.msg(data.msg); 
                        if(data.success){
                            $(t).parent().parent().remove();
                        }
                    },
                    error :function(xhr,msg,e){
                        layer.msg(msg); 
                    }
                }); 
                layer.close(index);
            });
        }
         
    }
</script>