<?php echo $this->render("./spm/layout/header.phtml");?>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <!-- 头部区域 begin  --> 
    <?php echo $this->render("./spm/layout/topMenu.phtml");?>
    <!-- 头部区域 end   --> 
    
    <!-- content begin   -->
    <div class="content-wrap">
        <!-- leftMenu begin   -->
        <?php echo $this->render("./spm/layout/leftMenu.phtml");?>
        <!-- leftMenu begin   -->
         
        <div class="content-main">
            <div class="wrapper">
                <!-- title begin -->
                <div class="title">
                    <p><?php if($channel){ echo '编辑';}else{ echo '新建';} ?>投放渠道组</p>
                </div>
                <!-- title end  -->
                <!-- form begin -->
                <form class="layui-form">
                    <!-- 基本信息 begin -->
                    <p class="padding-top20"></p>
                    <div class="subtitle"><p>基本信息:</p></div>
                    <div class="inputs-wrap">
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">渠道组名称</label>
                            <div class="layui-input-block long-label-input">
                                <input type="hidden" name="id" value="<?php echo $channelGroup['id']; ?>" />
                                <input type="text" name="name" placeholder="" value="<?php echo $channelGroup['name']; ?>" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">渠道标签</label>
                            <div class="layui-input-inline">
                                <select name="label_id" lay-verify=""  lay-filter="label_id" lay-search>
                                    <option value="" >选择渠道标签</option>
                                    <?php foreach($channelLabel as $key=>$value){ ?>
                                        <option value="<?php echo $value['id']; ?>" <?php if($value['id']==$channelGroup['label_id']){ echo 'selected';} ?> ><?php echo $value['name']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <p class="padding-top20"></p>
                    <div class="subtitle"><p>所属子集:</p></div>
                    <div class="inputs-wrap">
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">渠道列表</label>
                            <div class="layui-input-block long-label-input">
                                <div class="selector-wrap"></div>
                            </div>
                        </div>
                    </div>

                    <hr class="layui-bg-gray">
                    <div class="layui-form-item">
                        <div class="layui-input-block">
                            <button type="button" class="layui-btn layui-btn-normal" lay-submit lay-filter="submit_form">保存</button>
                            <button id="cancel" type="reset" class="layui-btn layui-btn-primary">取消</button>
                        </div>
                    </div>
                </form>
                <!-- form end  -->
          

        </div>
         
    </div>  
    <!-- content end     --> 
</div>
<script>
/* 请求链接 */
var addChannelGroupPostUrl = baseurl + '<?php echo $addChannelGroupPostUrl; ?>'; // 提交表单
var callbackUrl = baseurl + '<?php echo $groupUrl; ?>'; // 列表页面
var getChannelByGroupIdUrl = baseurl + '<?php echo $getChannelByGroupIdUrl; ?>'; // 渠道列表

/* 页面参数 */
var channelGroupId = '<?php echo $channelGroup['id']; ?>';

//JavaScript代码区域
layui.use(['element','form'], function(){
    var element = layui.element;
    var form = layui.form;
    // 初始化 渠道列表插件
    $(".selector-wrap").selectorplug({
        url: getChannelByGroupIdUrl,
        data: { id: channelGroupId, token: token },
        name: 'group_channel_range[]',
        title: '渠道',
        object : { key:'id' ,value:'channel_name'}
    });
    //表单提交
    form.on('submit(submit_form)', function(data){
        data.field.token = token;
        $.ajax({
            url : addChannelGroupPostUrl,
            async: false,
            data : data.field,
            type : 'post',
            dataType : 'json',
            jsonp : 'callback',
            success:function(data){
                layer.msg(data.msg);
                if(data.success){
                    setTimeout(function(){
                        window.location.href = callbackUrl;
                    },500);
                }
            },
            error:function(xhr,msg,e){
                layer.msg(msg);
            }
        });
        return false;
    });

    // 取消
    $("#cancel").click(function(){
        window.location.href = callbackUrl;
    });
});

</script>
</body>
</html>
      