<?php echo $this->render("./spm/layout/header.phtml");?>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <!-- 头部区域 begin  -->
    <?php echo $this->render("./spm/layout/topMenu.phtml");?>
    <!-- 头部区域 end   -->

    <!-- content begin   -->
    <div class="content-wrap">
        <!-- leftMenu begin   -->
        <?php echo $this->render("./spm/layout/leftMenu.phtml");?>
        <!-- leftMenu begin   -->

        <div class="content-main">
            <div class="wrapper">
                <!-- title begin -->
                <div class="title">
                    <p><?php if($payConfig){ echo '编辑';}else{ echo '新建';} ?>付费回调配置</p>
                </div>
                <!-- title end  -->
                <!-- form begin -->
                <form class="layui-form">
                    <!-- 基本信息 begin -->
                    <p class="padding-top20"></p>
                    <div class="subtitle"><p>基本信息:</p></div>
                    <div class="inputs-wrap">
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">广告渠道</label>
                            <div class="layui-input-inline">
                                <select name="channel_id" lay-verify=""  lay-filter="channel_id" lay-search>
                                    <option value="" >选择广告渠道</option>
                                    <?php foreach($channel as $key=>$value){ ?>
                                        <option value="<?php echo $value['id']; ?>" <?php if($value['id']==$payConfig['channel_id']){ echo 'selected';} ?> ><?php echo $value['channel_name']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">付费回调地址</label>
                            <div class="layui-input-block long-label-input">
                                <input type="hidden" name="id" value="<?php echo $payConfig['id']; ?>" />
                                <input type="text" name="pay_callback" placeholder="" value="<?php echo $payConfig['pay_callback']; ?>" class="layui-input" style="width:650px;">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">可选择参数</label>
                            <div class="layui-input-block long-label-input">
                                <table class="mui-data-table layui-table">
                                    <thead>
                                    <tr>
                                        <th>IDFA/IMEI</th><th>MUID</th><th>付费金额</th><th>付费日期</th><th>appstore_id</th><th>游戏包名</th><th>激活时间戳</th><th>用户 IP</th>
                                    </tr>
                                    </thead>
                                    <tbody><tr><td>{idfa}</td><td>{idfamd5}</td><td>{paylevel}</td><td>{paydate}</td><td>{appstore_id}</td><td>{bundleid}</td><td>{activetime}</td><td>{ip}</td></tr></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <p class="padding-top20"></p>
                    <div class="subtitle"><p>数据加密:</p></div>
                    <div class="inputs-wrap" style="width: 800px;">
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">付费计算公式</label>
                            <div class="layui-input-block long-label-input">
                                <div class="selector-wrap">
                                    原始金额<span class="red">&nbsp;&nbsp;*&nbsp;&nbsp;</span>
                                    <input type="text" maxlength="11" onkeyup="this.value=this.value.replace(/\D/g,'')" id="uptime" name="uptime" value="<?php echo $payConfig['uptime']; ?>" class="layui-input" style="display:inline;width:80px" />
                                    <span class="red">&nbsp;&nbsp;/&nbsp;&nbsp;</span>
                                    <input type="text" maxlength="11" onkeyup="this.value=this.value.replace(/\D/g,'')" id="downtime" name="downtime" value="<?php echo $payConfig['downtime']; ?>" class="layui-input" style="display:inline;width:80px" />
                                    <span class="red">&nbsp;&nbsp;+&nbsp;&nbsp;</span>
                                    <input type="text" maxlength="11" onkeyup="this.value=this.value.replace(/\D/g,'')" id="addval" name="addval" value="<?php echo $payConfig['addval']; ?>" class="layui-input" style="display:inline;width:80px" />
                                    <span style="color:#ccc">（ 原始金额币种为 元 ）</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <hr class="layui-bg-gray">
                    <div class="layui-form-item">
                        <div class="layui-input-block">
                            <button type="button" class="layui-btn layui-btn-normal" lay-submit lay-filter="submit_form">保存</button>
                            <button id="cancel" type="reset" class="layui-btn layui-btn-primary">取消</button>
                        </div>
                    </div>
                </form>
                <!-- form end  -->
            </div>
        </div>
        <!-- content end     -->
    </div>
    <script>
        /* 请求链接 */
        var addPayConfigPostUrl = baseurl + '<?php echo $addPayConfigPostUrl; ?>'; // 提交表单
        var payConfigUrl = baseurl + '<?php echo $payConfigUrl; ?>'; //  列表页面
        //JavaScript代码区域
        layui.use(['element','form'], function(){
            var element = layui.element;
            var form = layui.form;

            //表单提交
            form.on('submit(submit_form)', function(data){
                data.field.token = token;
                $.ajax({
                    url : addPayConfigPostUrl,
                    async: false,
                    data : data.field,
                    type : 'post',
                    dataType : 'json',
                    jsonp : 'callback',
                    success:function(data){
                        layer.msg(data.msg);
                        if(data.success){
                            setTimeout(function(){
                                window.location.href = payConfigUrl;
                            },500);
                        }
                    },
                    error:function(xhr,msg,e){
                        layer.msg(msg);
                    }
                });
                return false;
            });
            // 取消
            $("#cancel").click(function(){
                window.location.href = payConfigUrl;
            });
        });
    </script>
</body>
</html>
