<?php echo $this->render("./spm/layout/header.phtml");?>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <!-- 头部区域 begin  --> 
    <?php echo $this->render("./spm/layout/topMenu.phtml");?>
    <!-- 头部区域 end   --> 
    
    <!-- content begin   -->
    <div class="content-wrap">
        <!-- leftMenu begin   -->
        <?php echo $this->render("./spm/layout/leftMenu.phtml");?>
        <!-- leftMenu begin   -->
         
        <div class="content-main">
            <div class="wrapper">
                <!-- title begin -->
                <div class="title">
                    <p>安卓渠道组管理</p>
                </div>
                <!-- title end  -->
                 <!-- 查询条件 begin -->
                <div class="query-condition">
                <form class="layui-form">
                    <div class="layui-form-item">
                        <div class="layui-input-inline">
                            <input type="text" name="name" placeholder="请输入渠道组名称" value=""  class="layui-input" />
                        </div>
                        <div class="layui-input-inline">
                            <input type="text" name="channel_no" placeholder="请输入包的渠道号" value=""  class="layui-input" />
                        </div>
                        <div class="layui-input-inline">
                            <button type="button" class="layui-btn layui-btn-normal" lay-submit lay-filter="search">搜索</button>
                        </div>
                    </div>
                </form>
            </div>
            <!-- 查询条件 end  -->
            <!-- table begin -->
            <table id="activity_table" lay-filter="activity_table" >

            </table>

            <script type="text/html" id="barDemo">
<!--                <a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="detail">查看</a>-->
                <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
            </script>

            <!-- table end  -->
            </div>
            <input id="copy" type="text" style="opacity:0; filter:alpha(opacity=0); -moz-opacity:0; -khtml-opacity:0; -webkit-opacity:0;  " value="" >


        </div>
         
    </div>  
    <!-- content end     --> 
</div>
<script>
/* 请求链接 */
var addAndroidChannelGroupUrl = baseurl + '<?php echo $addAndroidChannelGroupUrl; ?>'; // 新建，编辑 渠道
var androidChannelGroupViewUrl = baseurl + '<?php echo $androidChannelGroupViewUrl; ?>'; // 查看 渠道
var androidChannelGroupListUrl = baseurl + "<?php echo $androidChannelGroupListUrl; ?>"; // 渲染表格 -- 列表

/* table 渲染参数 */
var layuiTable;
var page = true;
var where = { token:token ,name: '' ,channel_no: '' ,app_id:JSON.parse(localStorage.app_data).app_id  }; // 默认渲染table的初始条件
var table_id = '#activity_table';
var cols = [[ //表头
    {field: 'id', title: '编号',  sort: true  , }
    ,{field: 'name', title: '渠道组名称',  sort: true }
    ,{field: 'num', title: '渠道数量',  sort: true }
    ,{field: '', title: '操作', align:'center', toolbar: '#barDemo'}
]];

// 判断本地缓存是否 有渲染表格参数
if(localStorage.searchData){
    if(window.location.href == JSON.parse(localStorage.searchData).url){
        page = JSON.parse(localStorage.searchData).page;
        where = JSON.parse(localStorage.searchData).where; 
        where.app_id = JSON.parse(localStorage.app_data).app_id; 
        // 初始化搜索条件
        $("input[name='name']").val(where.name);
    }
}

//JavaScript代码区域
layui.use(['element','form','laydate','table'], function(){
    var element = layui.element;
    var form = layui.form;
    var table = layui.table;
    layuiTable = layui.table;
    //初始化表格
    var initTable = {
        elem: table_id,
        where: where,
        url : androidChannelGroupListUrl ,
        cols: cols ,
        page : page
    };
    renderTable(table,initTable,null);

    //监听搜索按钮
    form.on('submit(search)', function(data){
        var field = data.field;
        field.app_id = $("select[name='app_id']").find("option:selected").val();
        field.token = token;
        where = field ;
        var params = {
            elem: table_id,
            where: where,
            url : androidChannelGroupListUrl ,
            cols: cols ,
            page : true
        }
        renderTable(table,params,null);
        return false;
    });

    //监听单元格事件  -- 查看 ， 编辑
    table.on('tool(activity_table)', function(obj){
        var data = obj.data;
        if(obj.event === 'detail'){  // 查看
            window.location.href = androidChannelGroupViewUrl + "?id="+data.id;
        }else if(obj.event === 'edit'){  // 编辑
            window.location.href = addAndroidChannelGroupUrl + "?id="+data.id;
        }
    });

});

//   topMenu 切换app 回调
var appIdSelectChange = {
    callBack:function(id){
        var initTable = {
            elem: table_id,
            where: { token: token ,app_id: id},
            url : androidChannelGroupListUrl,
            cols: cols
        };
        renderTable(layuiTable,initTable,null);
    }
};
</script>
</body>
</html>
      