<?php echo $this->render("./spm/layout/header.phtml");?>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <!-- 头部区域 begin  -->
    <?php echo $this->render("./spm/layout/topMenu.phtml");?>
    <!-- 头部区域 end   -->

    <!-- content begin   -->
    <div class="content-wrap">
        <!-- leftMenu begin   -->
        <?php echo $this->render("./spm/layout/leftMenu.phtml");?>
        <!-- leftMenu begin   -->

        <div class="content-main">
            <div class="wrapper">
                <!-- title begin -->
                <div class="title">
                    <p>百度配置管理</p>
                </div>
                <!-- title end  -->
                <!-- 查询条件 begin -->
                <div class="query-condition">
                    <form class="layui-form">
                        <div class="layui-form-item">
                            <div class="layui-input-inline">
                                <input type="text" name="user_id" placeholder="请输入用户id" value=""  class="layui-input" />
                            </div>
                            <div class="layui-input-inline">
                                <button type="button" class="layui-btn layui-btn-normal" lay-submit lay-filter="search">搜索</button>
                            </div>

                        
                            <button id="addConfig" type="button" class="right layui-btn layui-btn-normal">新建配置</button>

                        </div>
                    </form>
                </div>
                <!-- 查询条件 end  -->
                <!-- table begin -->
                <table id="activity_table" lay-filter="activity_table" >

                </table>

                <script type="text/html" id="barDemo">
                    <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
                </script>

                <!-- table end  -->
            </div>
            <input id="copy" type="text" style="opacity:0; filter:alpha(opacity=0); -moz-opacity:0; -khtml-opacity:0; -webkit-opacity:0;  " value="" >


        </div>

    </div>
    <!-- content end     -->
</div>
<script>
    var searchCondition = { curr:1 , where:{ name:'' } }; // 缓存搜索条件,查询数据
    var baiduConfigListUrl = baseurl + '<?php echo $baiduConfigListUrl; ?>'; // 百度配置
    var baiduConfigUnitUrl = baseurl + '<?php echo $baiduConfigUnitUrl; ?>'; // 百度配置
    var addBaiduConfigPostUrl = baseurl + '<?php echo $addBaiduConfigPostUrl; ?>'; // 新建，编辑 百度配置
    var page = getQueryString("page");
    var user_id = getQueryString("user_id");

    // 初始化搜索条件
    $("input[name='user_id']").val(user_id);

    //JavaScript代码区域
    layui.use(['element','form','laydate','table'], function(){
        var element = layui.element;
        var form = layui.form;
        var table = layui.table;
        var cols = [[ //表头
            {field: 'user_id', title: '账户id',  sort: true  }
            ,{field: 'akey', title: '加密密钥',  sort: true }
            ,{field: 'update_time', title: '更新时间',  sort: true }
            ,{field: '', title: '操作', align:'center', toolbar: '#barDemo'}
        ]];

        //初始化表格
        var initTable = {
            elem: '#activity_table',
            where: { token:token , name:name },
            url : baiduConfigListUrl ,
            cols: cols ,
            page : { curr:page }
        };
        renderTable(table,initTable,null);

        //监听搜索按钮
        form.on('submit(search)', function(data){
            var field = data.field;
            searchCondition = field;
            field.token = token;
            var params = {
                elem: '#activity_table',
                url : baiduConfigListUrl,
                where: field,
                cols: cols,
                page : true
            }
            renderTable(table,params,null);
            return false;
        });

        //监听单元格事件  -- 查看 ， 编辑
        table.on('tool(activity_table)', function(obj){
            var data = obj.data;
            var page = searchCondition.curr,
                user_id = searchCondition.where.user_id;
            if(obj.event === 'edit'){  // 编辑
                $.ajax({
                    url : baiduConfigUnitUrl ,
                    async: false,
                    data : {token:token , id:data.id },
                    type : 'post',
                    dataType : 'json',
                    jsonp : 'callback',
                    success:function(data){
                        if(data.success){
                            addBaiduConfig(obj.tr,data.data);
                        }else{
                            layer.msg(data.msg);
                        }
                    },
                    error:function(xhr,msg,e){
                        layer.msg(msg);
                    }
                });
            }
        });

        // 新建渠道
        $("#addConfig").click(function(){
            addBaiduConfig($(this),null);
        });
    });

    //  渲染table
    function renderTable(table,data,callback){
        var callBakcData = {};
        //第一个实例
        table.render({
            elem: data.elem
            ,url: data.url //数据接口
            ,method: 'post'
            ,response: {
                statusName: 'success' //数据状态的字段名称，默认：code success
                ,statusCode: 0 //成功的状态码，默认：0
                ,msgName: 'msg' //状态信息的字段名称，默认：msg
                ,countName: 'count' //数据总数的字段名称，默认：count
                ,dataName: 'data' //数据列表的字段名称，默认：data
            }
            ,where: data.where
            ,limit: '10'
            ,page: data.page //开启分页
            ,cols: data.cols
            ,done: function(res, curr, count){
                callBakcData.where = data.where;
                callBakcData.curr = curr;
                callBakcData.res = res;
                callBakcData.count = count;
                searchCondition = callBakcData;
                //console.log(searchCondition);
                if(callback){
                    try{
                        callback.done(callBakcData);
                    }catch(e){

                    }
                }
            }
        });
    }
    // 新建，编辑 百度配置弹窗
    function addBaiduConfig(that,jsonData){
        var user_id='',akey='',text='新建';
        if(jsonData){
            text = '编辑' ;
            user_id = jsonData.user_id;
            akey = jsonData.akey;
        }
        var temp = `
    <br>
        <form class="layui-form" id="add_baiduConfig">
            <div class="layui-form-item">
            <label class="layui-form-label long-label">账户id</label>
            <div class="layui-input-inline ">
            <input type="text" name="user_id" placeholder="" value="`+user_id+`" class="layui-input" autocomplete="off">
            </div>
            <div class="layui-form-mid layui-word-aux">*</div>
            </div>
            <div class="layui-form-item">
            <label class="layui-form-label long-label">akey</label>
            <div class="layui-input-inline ">
            <input type="text" name="akey" placeholder="" class="layui-input" value="`+akey+`" autocomplete="off">
            </div>
            <div class="layui-form-mid layui-word-aux">*</div>
        </div>
        </form>`;
        layer.open({
            title : text +'百度配置',
            type: 1,
            area: ['800px', '400px'],
            shadeClose: true, //点击遮罩关闭
            content: temp,
            btn: ['保存', '取消'],
            success: function(layero){
                var btn = layero.find('.layui-layer-btn').find('.layui-layer-btn0');
                btn.on("click",function(){
                    var arr = $("#add_baiduConfig").serializeArray();
                    if(jsonData){
                        var objId = { name: 'id' , value: jsonData.id };
                        arr.push(objId) ;
                    }
                    arr.push({ name: 'token', value: token });
                    $.ajax({
                        url : addBaiduConfigPostUrl ,
                        async: false,
                        data : arr,
                        type : 'post',
                        dataType : 'json',
                        jsonp : 'callback',
                        success:function(data){
                            layer.msg(data.msg);
                            if(data.success){
                                setTimeout(function(){
                                    if(jsonData){
                                        that.find("td").each(function(){
                                            if($(this).attr('data-field')=='user_id'){
                                                $(this).find("div").html(arr[0].value);
                                            }
                                            if($(this).attr('data-field')=='akey'){
                                                $(this).find("div").html(arr[1].value);
                                            }
                                        });
                                    }else{
                                        window.location.reload();
                                    }
                                }, 500);
                            }

                        },
                        error:function(xhr,msg,e){
                            layer.msg(msg);
                        }
                    });
                });
            }
        });

    }
</script>
</body>
</html>
