<?php if($code && !empty($msg)){ ?>
<font color=red><?php echo $msg;?></font> <a href="<?php echo $uploadUrl .'?imgId=' . $imgId."&template_id=". $template_id."&type=". $type;?>">[返回]</a>
<?php }elseif(!empty($data)){ ?>
<b>上传成功！</b> <a href="<?php echo $uploadUrl . '?imgId=' . $imgId."&template_id=". $template_id."&type=". $type;?>">[重新上传]</a>
<?php }else{ ?>
<form id="form1" name="form1" method="post" action="<?php echo $uploadPostUrl;?>" onsubmit="return checkFrom()" enctype="multipart/form-data">
<input type="hidden" name="token" value="<?php echo $token;?>" /> 
<input type="hidden" name="MAX_FILE_SIZE" value="2000000" />
<input name="imgId" value="<?php echo $imgId;?>" type="hidden" />
<input name="template_id" value="<?php echo $template_id;?>" type="hidden" />
<input name="type" value="<?php echo $type;?>" type="hidden" />
<input name="mkthumb" value="<?php echo $mkthumb;?>" type="hidden" />
<input type="file" id="img" name="img" class="mr20"/>  
<input type="submit" name="sub" value="上传"  class="btn"> 允许上传的图片格式为：png jpeg jpg gif 且图片大小不能超过2M
</form>
<?php } ?>
<script> var par = /^.*?\.(jpg|gif|jpeg|png)$/i;

function checkFrom() {
	if($("#img").val()==''){
		window.parent.showError('出错','请选择要上传的图片');
		return false;
	}else if (!par.test($("#img").val())){
		window.parent.showError('出错','仅支持JPG、GIF、PNG图片文件，且文件小于2M');
		return false;
	}else{
		return true;
	}
}
<?php if(!empty($data)){?>
window.parent.showgdtAttach('<?php echo $imgId;?>' ,'<?php echo $data;?>', '<?php echo $data;?>', '<?php echo $our_image_id;?>');
<?php }?>
</script>