<?php echo $this->render("../../Admin/views/layout/header2.phtml");?>
<div class="colMain" style="min-height: 196px;">
	<div class="main">
	<form action="<?php echo $adManageListUrl;?>" method="get" id="searchForm">
		<input name="token" type="hidden" value="<?php echo $token;?>" />
        <div class="table_full">
        	<table width="100%">	
        	   <tr class="tr">
        			<th class="th">广告名称</th>
        			<td class="td"><input type="text" class="iText" name="ad_name" value="<?php echo $search['ad_name'];?>"></td>
        			<th class="th">广告状态</th>
        			<td class="td">
        			 <select name="status" class="select wa">
        			    <option  value="0">全部</option>
        		        <?php foreach ($adStatus as $key=>$val ){?>
        		        <option  value="<?php echo $key; ?>" <?php echo  $search['status'] == $key?'selected=selected':''?> ><?php echo $val; ?></option>
        		        <?php }?>
        			 </select>
        		   </td>
        		   <th class="th">广告目标</th>
        		   	<td class="td">
        			 <select name="ad_target_type" class="select wa">
        			    <option  value="0">全部</option>
        				<?php foreach ($adTargetType as $key=>$val ){?>
        		        <option  value="<?php echo $key; ?>" <?php echo  $search['ad_target_type'] == $key?'selected=selected':''?> ><?php echo $val; ?></option>
        		        <?php }?>
        			 </select>
        		   </td>
        		      <th class="th">计费类型</th>
        		   	<td class="td">
        			 <select name="charge_type" class="select wa">
        			    <option  value="0">全部</option>
        				<?php foreach ($chargeTypeList as $key=>$val ){?>
        		        <option  value="<?php echo $key; ?>" <?php echo  $search['charge_type'] == $key?'selected=selected':''?> ><?php echo $val; ?></option>
        		        <?php }?>
        			 </select>
        		   </td>
        		</tr>
        		<tr>

                    <th class="th">创意类型</th>
                    <td class="td">
                        <select name="originality_type" class="select wa">
                            <option  value="0">全部</option>
							<?php foreach ($originalityType as $key=>$val ){?>
                                <option  value="<?php echo $key; ?>" <?php echo  $search['originality_type'] == $key?'selected=selected':''?> ><?php echo $val; ?></option>
							<?php }?>
                        </select>
                    </td>
        		  <th class="th">投放单元</th>
        		   	<td class="td">
        			 <select name="unit_id" class="select wa">
        			    <option  value="0">全部</option>
        				<?php foreach ($unitList as $key=>$val ){?>
        		        <option  value="<?php echo $key; ?>" <?php echo  $search['unit_id'] == $key?'selected=selected':''?> ><?php echo $val['name']; ?></option>
        		        <?php }?>
        			 </select>
        		   </td>
                    <th class="th">投放时间</th>
                    <td class="td">
                    <input class="iText" type="text" maxlength="30" style="width:100px;" id="start_time" name="start_time" value="<?php echo $search['start_time'] ;?>"  readonly="readonly" />
                     至 <input class="iText" type="text" maxlength="30" style="width:100px;" id="end_time" name="end_time" value="<?php echo $search['end_time'] ;?>"  readonly="readonly" />
                    </td>
                </tr>
        	
        	</table>
        </div>
        <div class="mb10 tac">
                <span><button type="submit" class="btn">搜 索</button></span>
        </div>
      	<div class="fr ml10 mb20">
     		<span ><button type="button" class="btn" id="btn-export">导出</button></span>
		 </div>
        </form>
		<form id="batchForm" action="<?php echo $batchUpdateAdInfoUrl;?>" method="post">
            <input name="token" type="hidden" value="<?php echo $token;?>" />
            <input name="action" id="action" type="hidden" value="" />
            <input name="value" id="value" type="hidden" value="" />
            <div class="h_a mb10">
               <span class="bt2"><span><button onclick="javascript:deleteAll()" type="button">删除</button></span></span>
            	<span class="bt2"><span><button  type="button" onclick="javascript:editStatus('修改状态');" >修改状态</button></span></span>
                <span class="bt2"><span><button  type="button" onclick="javascript:editPrice('修改价格');">修改价格</button></span></span>
                <span class="bt2"><span><button  type="button" onclick="javascript:forwardToPrePage('<?php echo $webRoot.$addAdStep1Url; ?>')">新建广告</button></span></span>
      
            </div>
    		<div class="content">
    			<div class="grid">
    				<table>
    					<thead>
                            <tr>
                                <th><input type="checkbox" onclick="checkAll('.checkbox')"></th>
                                <th>操作</th>
                                <th>广告ID</th>
                                <th>广告名称</th>
                                <th>广告状态</th>
                                <th>广告目标</th>
                                <th>创意类型</th>
                                <th>计费类型</th>
                                <th>限额</th>
                                <th>出价（元）</th>
                                <th>消耗（元）</th>
                                <th>曝光</th>
                                <th>点击</th>
                                <th>激活</th>
                                <th>点击率（%）</th>
                                <th>点击均价</th>
                                 <th>激活率（%）</th>
                                 <th>CPA</th>
                            </tr>
                        </thead>
    				 <?php foreach ($adList as $key=>$val ){?>
    					<tr>
                            <td><input class="checkbox" name="ids[]" value="<?php echo $val['id']; ?>" type="checkbox"></td>
                            <?php if($val['status'] == 5){ ?>
                            <td><a href="<?php echo $webRoot.$addAdStep1Url.'?action=copy&id='.$val['id'] ; ?>" title="复制">复制</a></td>
                            <?php }else{?>
                            <td><a href="<?php echo $webRoot.$addAdStep1Url.'?id='.$val['id'] ; ?>" title="编辑">编辑</a>| <a href="<?php echo $webRoot.$addAdStep1Url.'?action=copy&id='.$val['id'] ; ?>" title="复制">复制</a></td>
                            <?php }?>
                            <td><?php echo $val['id']; ?></td>
                            <td><span class="name_span"><a href="<?php echo $webRoot.$origainalityListUrl.'?ad_id='.$val['id'] ; ?>" title="编辑"><?php echo $val['ad_name']; ?></a> </span> <a class='edit ml20 edit_name' ad_name='<?php echo $val['ad_name']?>' ad_id='<?php echo $val['id'];?>'></a></td>
                            <td><?php echo $val['del']==Common_Service_Const::NOT_DELETE_FLAG?$adStatus[$val['status']]:'已删除'; ?></td>
                            <td><?php echo $adTargetType[$val['ad_target_type']]; ?></td>
                            <td><?php echo $originalityType[$val['originality_type']]; ?></td>
                            <td><?php echo $chargeTypeList[$val['charge_type']]; ?></td>
                            <td><?php echo $val['ad_limit_type']?$val['ad_limit_amount']:'无限制'; ?></td>
                            <td><?php echo number_format($val['price'],2);   ?></td>
                            <td><?php echo number_format($val['amount'],2); ?></td>
                            <td><?php echo number_format($val['views']); ?></td>
                            <td><?php echo number_format($val['clicks']); ?></td>
                            <td><?php echo number_format($val['actives']); ?></td>
                            <td><?php echo number_format($val['click_rate'],2); ?></td>
                            <td><?php echo number_format($val['amount_rate'],2); ?></td>
                             <td><?php echo number_format($val['active_rate'],2); ?></td>
                             <td><?php echo number_format($val['cpa'],2); ?></td>
                        </tr>
    				   <?php }?>
    				</table>
    			</div>
    			<div class="mt10 cc tc">
                    <?php echo $pager;?>
                </div>
    		</div>
        </form>
	</div>
</div>
</div>



<div id="editStatus" style="margin: 20px; line-height: 32px; font-size: 14px; display: none">
  <ul class="form">
		  <li> 
			<span class="label">状态：</span>
			<div class="fc">
			    <?php foreach ($modifyStatus as $key=>$val ){?>
			 	<p><input type="radio" value="<?php echo $key; ?>" name="editStatus" class="radio"><?php echo $val; ?></p>
	        <?php }?>
            </div>
		 </li>
	</ul>
</div>

<div id="editPrice" style="margin: 20px; line-height: 32px; font-size: 14px; display: none">
  <ul class="form">
	<li> 
		<span class="label">出价：</span>
		<div class="fc">
            <label><input name="edit_price" type="text" value="" class="iText " > </label> </p>
        </div>
	 </li>
	</ul>
</div>




<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datepicker();
     $('#end_time').datepicker();
	ajaxForm('batchForm',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $adManageListUrl;?>');
	});

    $(".edit_name").click(function(){
        name = $(this).attr('ad_name')
        id = $(this).attr('ad_id')
        inputId = 'modify_name' + id
        $(this).siblings('.input').remove();
        str = '<input type="text" class="input" value="'+ name +'"   id="'+inputId+'">'
        $(this).siblings('.name_span').hide().after(str);
        $("#" + inputId).focus()
        $("#" + inputId).blur(function(){
            adName = $("#"+inputId).val();
            if( $.trim(adName) == ''){
        		return false;
             }
            $.ajax({
                url:  baseurl+"<?php echo $updateAdNameUrl  ?>",
                type: "POST",
                dataType : 'json',
                data : { 'token':token, 'id':id, 'ad_name': adName},
                success: function(ret) {
                    if (ret.success) {
                        showMsg('', ret.msg);
                        setTimeout(function() {
                            location.reload();
                        }, 500);
                    } else {
                        showError('', ret.msg);
                    }
                    $("#" + inputId).siblings('.name_span').show()
                    $("#" + inputId).remove()
                }
            });
        });
    });
    
    
    $("#btn-export").click(function() {

            var confarr = [];
            var name = "";
            var value = "";
            $("#searchForm input").each(function(){
                name = $(this).attr("name");
                value = $(this).val();
                if(value != ""){
                    confarr.push(name + "=" + value);
                }
            });
            $("#searchForm select").each(function(){
                name = $(this).attr("name");
                $(this).find("option:selected").each(function(){
                    value = $(this).val();
                });
                if(value != 0){
                    confarr.push(name + "=" + value);
                }
            });
            var str = confarr.join("&");
            window.location.href = "<?php echo $exportAdUrl; ?>"+"?"+str;
        });
    
})

function editPrice(title){
	return $("#editPrice").dialog({
					title : title,
					draggable : false,
					width:600,
					modal : true,
					resizable : false,
					buttons: {
					        'ok': function() {
					            edit_price = $.trim($("input[name='edit_price']").val());
					 
					         	if(edit_price == ''){
					        		alert("出价不能为空!");
					                return false;
					        	}
					        	$('#action').val('price');
					        	$('#value').val(edit_price);
					        	$("#batchForm").submit();
					        },
					        Cancel: function() {
					            $(this).dialog('close');
					        }
					    }
				});
}

function editStatus(title){
	return $("#editStatus").dialog({
					title : title,
					draggable : false,
					width:600,
					modal : true,
					resizable : false,
					buttons: {
					        'ok': function() {
					        	status =  $("input[name='editStatus']:checked").val();			
					           	if(status==null || status == 'undefined') {
					                alert("状态没选中!");
					                return false;
					            }
					        	$('#action').val('status');
					        	$('#value').val(status);
					        	$("#batchForm").submit();
					     	
					        },
					        Cancel: function() {
					            $(this).dialog('close');
					        }
					    }
				});
}


</script>
<?php echo $this->render("../../Admin/views/layout/footer.phtml");?>