<?php echo $this->render("layout/header1.phtml");?>
<div class="colMain">
   <div class="nav">
		<ul class="cc">
            <li><a href="<?php echo $documentListUrl;?>">文档列表</a></li>
			<li class="current"><a href="<?php echo $addDocumentUrl;?>"><?php echo $navTitle; ?>文档</a></li>
		</ul>
	</div>
    <div class="main">
        <div class="app-detail">
              <form action="<?php echo $addDocumentPostUrl; ?>" method="POST" class="app_form"  id="addForm" >
                <input type="hidden" name="id"  id="id" value='<?php echo $info['id']; ?>' />
                 <input type="hidden" name="token" value="<?php echo $token;?>">
                <ul class="form">
                    <li>
                        <span class="label">一级菜单：</span>
                        <div class="fc">
                            <select name="menu_parent_id" id="menu_parent_id" >
                                <option value="0">--请选择--</option>
                                <?php foreach($menu1List as $k1=>$v1){ ?>
                                    <option value="<?php echo $v1['id']; ?>"  <?php if( $info['menu_parent_id']==$v1['id'] ){ ?> selected <?php } ?> ><?php echo $v1['name']; ?></option>
                                <?php } ?>
                            </select>
                            <span class="red">*</span>
                        </div>
                    </li>
                    <li>
                        <span class="label">二级菜单：</span>
                        <div class="fc">
                            <select name="menu_id" id="menu_id" >
                                <option value="0" parent_id="0">--请选择--</option>
                                <?php foreach($nowSubMenuList as $k1=>$v1){ ?>
                                    <option value="<?php echo $v1['id']; ?>"  <?php if( $info['menu_id']==$v1['id'] ){ ?> selected <?php } ?> parent_id="<?php echo $v1['parent_id'] ?>" ><?php echo $v1['name']; ?></option>
                                <?php } ?>
                            </select>
                            <span class="red">*</span>
                        </div>
                    </li>

                    <li>
                        <span class="label">标题：</span>
                        <div class="fc">
                            <input type="text" class="iText required" required name="title"  value="<?php echo $info['title']; ?>" />
                            <span class="red">*</span>
                        </div>
                    </li>
                    <li>
                        <span class="label">内容：</span>
                        <div class="fc">
                            <textarea  id="content" name="content" style="width:1000px;height:240px;"><?php echo $info['content']; ?></textarea >
<!--                            <textarea id="txt-content" name="content"  data-autosave="editor-content--><?php //echo $info['id'] ?><!--" autofocus>--><?php //echo $info['content']; ?><!--</textarea>-->
                            <span class="red">*</span>
                        </div>
                    </li>
					<li>
                        <div class="fc">
                            <input type="submit"  value="保存" class="submit"  />
                            <input type="button" value="取消" class="cancel" onclick="window.location.href='<?php echo $documentListUrl;?>' " />
                        </div>
                    </li>
                </ul>
            </form>
        </div>
    </div>
</div>
<!--<script type="text/javascript" src="--><?php //echo $staticPath; ?><!--/js/utf8-php/ueditor.config.js"></script>-->
<!--<script type="text/javascript" src="--><?php //echo $staticPath; ?><!--/js/utf8-php/ueditor.all.min.js"></script>-->
<!--<script type="text/javascript" src="--><?php //echo $staticPath; ?><!--/js/utf8-php/lang/zh-cn/zh-cn.js"></script>-->

<link media="all" rel="stylesheet" type="text/css" href="<?php echo $staticPath; ?>/js/umeditor/themes/default/css/umeditor.css" />
<!--<script type="text/javascript" src="--><?php //echo $staticPath; ?><!--/js/umeditor/third-party/jquery.min.js"></script>-->
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/umeditor/third-party/template.min.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/umeditor/umeditor.config.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/umeditor/umeditor.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/umeditor/lang/zh-cn/zh-cn.js"></script>
<script>
$(document).ready(function(){
	ajaxForm('addForm',function(ret){
	        ajaxRedirect(ret, baseurl+'<?php echo $documentListUrl;?>');
	 },function(){
		 return true;
	});
    var sub_menu_list = <?php echo json_encode($subMenuList); ?>;
    $('#menu_parent_id').change(function(){
        var menu_parent_id = $(this).val();
        var sub_menu_div = '<option value="0" parent_id="0">--请选择--</option>';
        if(menu_parent_id != 0){
            var now_sub_munu = sub_menu_list[menu_parent_id];
            now_sub_munu.forEach(function(data){
                sub_menu_div += '<option value="'+ data['id']+ '" parent_id="'+ data['parent_id']+ '">'+ data['name']+ '</option>';
            });
        }
        $("#menu_id").html(sub_menu_div);
    });
    //实例化编辑器
    var um = UM.getEditor('content',{
         'imageUrl': "<?php echo $uploadImgUrl; ?>?token="+token, //图片上传提交后台对应的地址
         // toolbar:['source','insertcode',],
    });
//    um.imageUploader.setPostParams({'token':token});

});
</script>
<?php echo $this->render("layout/footer1.phtml"); ?>