<?php echo $this->render("./spm/layout/header.phtml");?>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <!-- 头部区域 begin  -->
    <?php echo $this->render("./spm/layout/topMenu.phtml");?>
    <!-- 头部区域 end   -->

    <!-- content begin   -->
    <div class="content-wrap">
        <!-- leftMenu begin   -->
        <?php echo $this->render("./spm/layout/leftMenu.phtml");?>
        <!-- leftMenu begin   -->

        <div class="content-main">
            <div class="wrapper">
                <!-- title begin -->
                <div class="title">
                    <p>AF渠道管理</p>
                </div>
                <!-- title end  -->
                <!-- 查询条件 begin -->
                <div class="query-condition">
                    <form class="layui-form">
                        <div class="layui-form-item">
                            <div class="layui-input-inline">
                                <input type="text" name="channel_name" placeholder="请输入渠道名称 或 编号" value=""  class="layui-input" />
                            </div>
                            <div class="layui-input-inline">
                                <button type="button" class="layui-btn layui-btn-normal" lay-submit lay-filter="search">搜索</button>
                            </div>

                        </div>
                    </form>
                </div>
                <!-- 查询条件 end  -->
                <!-- table begin -->
                <table id="activity_table" lay-filter="activity_table" >

                </table>

                <script type="text/html" id="barDemo">
                    <a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="detail">查看</a>
                </script>

                <!-- table end  -->
            </div>
            <input id="copy" type="text" style="opacity:0; filter:alpha(opacity=0); -moz-opacity:0; -khtml-opacity:0; -webkit-opacity:0;  " value="" >

        </div>

    </div>
    <!-- content end     -->
</div>
<script>
    var searchCondition = { curr:1 , where:{ channel_name:'' ,channel_no:'' } }; // 缓存搜索条件,查询数据
    var appsflyerChannelListUrl = baseurl + "<?php echo $appsflyerChannelListUrl; ?>"; // 渲染表格
    var channelViewUrl = baseurl + '<?php echo $channelViewUrl; ?>'; // 查看 渠道
    var page = getQueryString("page");
    var channel_name = getQueryString("channel_name");
    var channel_no = getQueryString("channel_no");

    // 初始化搜索条件
    $("input[name='channel_name']").val(channel_name);
    $("input[name='channel_no']").val(channel_no);

    //JavaScript代码区域
    layui.use(['element','form','laydate','table'], function(){
        var element = layui.element;
        var form = layui.form;
        var table = layui.table;
        var cols = [[ //表头
            {field: 'channel_no', title: '渠道编号',  sort: true  }
            ,{field: 'channel_name', title: '渠道名称',  sort: true }
            ,{field: 'update_time', title: '更新时间', sort: true , }
//            ,{field: '', title: '操作', align:'center', toolbar: '#barDemo'}
        ]];

        //初始化表格
        var initTable = {
            elem: '#activity_table',
            where: { token:token , channel_name:channel_name , channel_no:channel_no },
            url : appsflyerChannelListUrl ,
            cols: cols ,
            page : { curr:page }
        };
        renderTable(table,initTable,null);

        //监听搜索按钮
        form.on('submit(search)', function(data){
            var field = data.field;
            searchCondition = field;
            field.token = token;
            var params = {
                elem: '#activity_table',
                url : appsflyerChannelListUrl,
                where: field,
                cols: cols,
                page : true
            }
            renderTable(table,params,null);
            return false;
        });

        //监听单元格事件  -- 查看 ， 编辑
        table.on('tool(activity_table)', function(obj){
            var data = obj.data;
            var page = searchCondition.curr,
                channel_name = searchCondition.where.channel_name,
                channel_no = searchCondition.where.channel_no;
            if(obj.event === 'detail'){  // 查看
//                window.location.href = channelViewUrl + "?&page="+page+"&channel_name="+channel_name +"&channel_no="+channel_no+"&id="+data.id;
            }
        });


    });

    //  渲染table
    function renderTable(table,data,callback){
        var callBakcData = {};
        //第一个实例
        table.render({
            elem: data.elem
            ,url: data.url //数据接口
            ,method: 'post'
            ,response: {
                statusName: 'success' //数据状态的字段名称，默认：code success
                ,statusCode: 0 //成功的状态码，默认：0
                ,msgName: 'msg' //状态信息的字段名称，默认：msg
                ,countName: 'count' //数据总数的字段名称，默认：count
                ,dataName: 'data' //数据列表的字段名称，默认：data
            }
            ,where: data.where
            ,limit: '10'
            ,page: data.page //开启分页
            ,cols: data.cols
            ,done: function(res, curr, count){
                callBakcData.where = data.where;
                callBakcData.curr = curr;
                callBakcData.res = res;
                callBakcData.count = count;
                searchCondition = callBakcData;
                //console.log(searchCondition);
                if(callback){
                    try{
                        callback.done(callBakcData);
                    }catch(e){

                    }
                }
            }
        });
    }



</script>
</body>
</html>
