<?php echo $this->render("layout/header1.phtml");?>
    <script type="text/javascript" src="<?php echo $staticPath;?>/js/common/WdatePicker.js"></script>
    <script type="text/javascript">
        function confirmSubmit(){
            var group_name = $("#group_name").val();
            if(group_name == ''){
                layer.msg("请输入用户组!",{'icon':1});
                return false;
            }
            var url = '<?php echo $AddMonitorGroup;?>';
            var fd = new FormData();//h5上传
            fd.append('group_name',group_name);
            fd.append('token',token);
            $.ajax({
                url: url,
                type: "POST",
                processData: false,
                contentType: false,
                data: fd,
                dataType:'json',
                success: function(data) {
                    if(data.status == 1){
                        layer.msg(data.msg);
                        window.parent.location.reload();
                        parent.layer.close();
                    }else{
                        layer.msg(data.msg);
                        layer.close();
                        //location.reload();
                    }
                }
            });
        }
    </script>
    <style>
        .importtable{
            border-collapse: collapse;border-spacing:0;
        }
        .importtable thead{
            border: 1px solid #e8e8e8; border-width: 1px;
        }
        .importtable thead tr th{
            padding: 10px;
        }
        .importtable tbody tr td{
            padding: 10px;
        }
    </style>
    <div class="colMain">

        <div class="main">
            <div class="app-detail">
                <form action="" method="POST" enctype="multipart/form-data">
                    <ul class="form">
                        <li>
                            <span class="label">用户组名称：</span>
                            <div class="fc">
                                <input type="text" name='group_name' id='group_name' value="" />
                                <span class="red">*</span>
                            </div>
                        </li>
                        <li>
                            <div class="fc">
                                <input type=""  value="保存" class="submit"  onclick="confirmSubmit()"/>

                            </div>
                        </li>
                    </ul>
                </form>
            </div>
        </div>
    </div>
    <script>
        $(function(){
            $('#monitor_type').bind('change',function(){
                var type = $(this).val();
                if(type == 1){
                    $('.ecpm_show').css('display','block');
                    $('.dau_show').css('display','none');
                }else{
                    $('.dau_show').css('display','block');
                    $('.ecpm_show').css('display','none');
                }
            })
        })
    </script>
<?php echo $this->render("layout/footer1.phtml");?>