<?php echo $this->render("layout/header1.phtml");?>
    <script type="text/javascript" src="<?php echo $staticPath;?>/js/common/WdatePicker.js"></script>
    <script type="text/javascript">
        function confirmSubmit(){
            var user_name = $("#user_name").val();
            if(user_name == ''){
                layer.msg("请输入昵称!");
                return false;
            }
            checkEmail = /^(.+)@(.+)$/;
            var email = $("#email").val();
            if(!checkEmail.test(email)){
                layer.msg("请输入正确的邮箱！");
                return false;
            }

            checkTel = /^[1][1-7][0-9]{9}$/;
            var tel = $("#tel").val();
            if(!checkTel.test(tel)){
                layer.msg("请输入正确的号码！");
                return false;
            }


            var gid = $("#gid").val();
            if(gid == -1){
                layer.msg("请选择预警对象组！");
                return false;
            }

            var url = '<?php echo $AddUserUrl;?>';
            layer.load('正在处理....', 3);
            var fd = new FormData();//h5上传
            fd.append('user_name',user_name);
            fd.append('tel',tel);
            fd.append('email',email);
            fd.append('gid',gid);
            fd.append('token',token);
            $.ajax({
                url: url,
                type: "POST",
                processData: false,
                contentType: false,
                data: fd,
                success: function(data) {
                    if(data == 1){
                        layer.msg('操作成功');
                        window.parent.location.reload();
                        parent.layer.close();
                        //location.reload();
                    }else{
                        layer.msg('操作失败');
                        //location.reload();
                    }
                }
            });
        }
    </script>
    <style>
        .importtable{
            border-collapse: collapse;border-spacing:0;
        }
        .importtable thead{
            border: 1px solid #e8e8e8; border-width: 1px;
        }
        .importtable thead tr th{
            padding: 10px;
        }
        .importtable tbody tr td{
            padding: 10px;
        }
    </style>
    <div class="colMain">

        <div class="main">
            <div class="app-detail">
                <form action="" method="POST" enctype="multipart/form-data">
                    <ul class="form">
                        <li>
                            <span class="label">用户昵称：</span>
                            <div class="fc">
                                <input type="text" name='user_name' id='user_name' value="" />
                                <span class="red">*</span>
                            </div>
                        </li>
                        <li>
                            <span class="label">邮箱：</span>
                            <div class="fc">
                                <input type="text" name='email' id='email' value="" />
                                <span class="red">*</span>
                            </div>
                        </li>
                        <li>
                            <span class="label">手机：</span>
                            <div class="fc">
                                <input type="text" name='tel' id='tel' value="" />
                                <span class="red">*</span>
                            </div>
                        </li>
                        <li>
                            <span class="label">预警对象组：</span>
                            <div class="fc">
                                <select id="gid" name="gid">
                                    <option value="-1"  >- 请选择 -</option>
                                    <?php  foreach ($user_group as $key=>$val){?>
                                        <option value="<?php echo $val['id'];?>" <?php if($gid == $val['id']) echo "selected";?> ><?php echo $val['group_name'];?> </option>
                                    <?php  }?>
                                </select>
                                <span class="red">*</span>
                            </div>
                        </li>
                        <li>
                            <div class="fc">
                                <input type=""  value="保存" class="submit"  onclick="confirmSubmit()"/>

                            </div>
                        </li>
                    </ul>
                </form>
            </div>
        </div>
    </div>
    <script>
        $(function(){
            $('#monitor_type').bind('change',function(){
                var type = $(this).val();
                if(type == 1){
                    $('.ecpm_show').css('display','block');
                    $('.dau_show').css('display','none');
                }else{
                    $('.dau_show').css('display','block');
                    $('.ecpm_show').css('display','none');
                }
            })
        })

    </script>
<?php echo $this->render("layout/footer1.phtml");?>