<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<link rel="stylesheet" type="text/css" href="<?php echo $staticPath; ?>/js/admin/lay/css/layui.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $staticPath; ?>/css/selectBox.css"/>
<style>
    *{ margin: 0; padding: 0;}
    html,body{
        font-family: 'STHeiti Light [STXihei]', Helvetica, 'Hiragino Sans GB', 'Microsoft Yahei', '微软雅黑', Arial, sans-serif;
        font-size: 14px;
        background: #e5e6eb;
    }
    .wrapper{ background: #fff; padding:5px 20px 50px 20px; box-sizing:border-box; }
    .search-wrap{   padding-top: 2px; }
    .tchar-side{ padding: 5px 10px; height: 600px; width: 100%;   }
</style>
<body>
<div class="layui-fluid wrapper">
    <div class="layui-row layui-col-space30">
        <!-- 广告用户LTV数据 begin -->

        <div class="layui-collapse">
            <!--  广告LTV报表   begin -->
            <div class="layui-colla-item">

                <div class="layui-colla-content layui-show">
                    <!--  条件搜索 begin -->
                    <div class="search-wrap">
                        <form id='formDemo1' class="layui-form" action="getMonitorLog"  data-id="1">
                            <div class="layui-inline" style="width: 200px;">
                                <input type="text" name="days" class="layui-input" id="datetime1">
                                <input type="hidden" name="taskId" class="layui-input" id="taskId" value="<?php echo $taskId;?>">
                                <input type="hidden" name="monitorType" class="layui-input" id="monitorType" value="<?php echo $monitorType;?>">
                            </div>
                            <button class="layui-btn lay-submit" lay-submit lay-filter="formDemo">立即查询</button>
                        </form>
                    </div>
                    <!--  条件搜索 end -->
                    <div class="tchar-side" id="chart1" ></div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
<script src="<?php echo $staticPath; ?>/js/admin/lay/layui.js"></script>
<script src="<?php echo $staticPath; ?>/js/common/jquery.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/admin/lay/echarts.min.js"></script>
<script>
    ;(function(){
        function to_array(obj){
            var arr=[]
            for (var i in obj){
                arr.push(obj[i]);
            }
            return arr;
        };
        function chart_render(chart,data){
            var base = -data.reduce(function (min, val) {
                return Math.floor(Math.min(min, val.lower));
            }, Infinity);
            var option = {
                title: {
                    text: '监控记录',
                    subtext: 'iDreamsky ADS Monitor',
                    left: 'center'
                },
                tooltip: {
                    trigger: 'axis',
                    axisPointer: {
                        type: 'cross',
                        animation: false,
                        label: {
                            backgroundColor: '#ccc',
                            borderColor: '#aaa',
                            borderWidth: 1,
                            shadowBlur: 0,
                            shadowOffsetX: 0,
                            shadowOffsetY: 0,
                            textStyle: {
                                color: '#222'
                            }
                        }
                    },
                    formatter: function (params) {
                        return params[2].name + '<br />' + params[2].value;
                    }
                },
                grid: {
                    left: '3%',
                    right: '4%',
                    bottom: '3%',
                    containLabel: true
                },
                xAxis: {
                    type: 'category',
                    data: data.map(function (item) {
                        return item.days;
                    }),
                    axisLabel: {
                        formatter: function (value, idx) {
                            var date = new Date(value);
                            //console.log(new Date("2018-01-01 20:00:00").getHours())
                            return idx === 0 ? value : [date.getMonth()+1, date.getDate()].join('-');
                        }
                    },
                    splitLine: {
                        show: false
                    },
                    boundaryGap: false
                },
                yAxis: {
                },
                series: [{
                    name: 'L',
                    type: 'line',
                    data: data.map(function (item) {
                        return item.lower;
                    }),
                    lineStyle: {
                        normal: {
                            opacity: 0
                        }
                    },
                    stack: 'confidence-band',
                    symbol: 'none'
                }, {
                    name: 'U',
                    type: 'line',
                    data: data.map(function (item) {
                        return item.upper - item.lower;
                    }),
                    lineStyle: {
                        normal: {
                            opacity: 0
                        }
                    },
                    areaStyle: {
                        normal: {
                            color: '#ccc'
                        }
                    },
                    stack: 'confidence-band',
                    symbol: 'none'
                }, {
                    type: 'line',
                    data: data.map(function (item) {
                        return item.value;
                    }),
                    hoverAnimation: false,
                    symbolSize: 10,
                    itemStyle: {
                        normal: {
                            color: '#c23531'
                        }
                    },
                    showSymbol: false,
                    symbol: 'triangle'
                }]
            }
            chart.setOption(option,true);
        }

        layui.use(['element','laydate','form','table'],  function(){
            var element = layui.element;
            var laydate = layui.laydate;
            var form = layui.form;
            var table = layui.table;
            laydate.render({elem: '#datetime1',range: true,value: '<?php echo $sdate." - ".$edate ?>'});
            laydate.render({elem: '#datetime2',range: true,value: '<?php echo $sdate." - ".$edate ?>'});
            form.on('submit(formDemo)',function (data){
                var formId=parseInt(data.form.id.replace(/[^0-9]/ig,""))
                var chart=echarts.init(document.getElementById('chart'+formId))
                chart.showLoading();
                layui.$.ajax({
                    type: 'GET',
                    data: data.field,
                    url: data.form.action,
                    dataType: 'json',
                    success: function(data){
                        chart_render(chart,data);
                        chart.hideLoading();
                    },
                    error: function(xhr){
                        layer.msg("fail");
                    }
                });
                return false;
            });
            layui.$('.lay-submit').click();
        })})();
</script>



