<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MONITOR</title>
</head>
<link rel="shortcut icon" href="<?php echo $staticPath;?>/img/favicon.ico" />
<link href="<?php echo $staticPath?>/js/admin/lay/css/layui.css?v=<?php echo $version;?>" rel="stylesheet" type="text/css"/>
<link href="<?php echo $staticPath?>/css/spm/spm_page.css?v=<?php echo $version;?>" rel="stylesheet" type="text/css"/>
<link href="<?php echo $staticPath?>/css/selectorplug.css?v=<?php echo $version;?>" rel="stylesheet" type="text/css"/>
<script src="<?php echo $staticPath?>/js/admin/lay/layui.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticPath?>/js/common/jquery.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticPath?>/js/common/spm/spm_common.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $staticPath?>/js/common/selectorplug.js?v=<?php echo $version;?>"></script>
<script>
var token = "<?php echo $token;?>";
var baseurl = "<?php echo $adminroot; ?>";
layui.use(['form','element','table'], function(){
    var element = layui.element;
});


</script>
