<?php echo $this->render("layout/header.phtml");?>
<div class="colMain">
    <div class="main">
        <div class="chart app-detail">
            <div class="subtitle" style="width:100%">数据概况</div>
            <ul class="chart-filter">
                <li class="date-filter">
                    <div id="date_range" class="fr" sdate="<?php echo $sdate;?>" edate="<?php echo $edate;?>"></div>
                    <div id="kpi" class="ta_date fr" data-type="kpi"  style="display:inline-block;margin-right:10px;" >
                        <span class="date_title">自定义指标</span>
                        <a class="opt_sel"> <i class="i_orderd"></i></a>
                    </div>
                    <div style="clear:both;"></div>
                </li>
                <li class="dim-filter">
                    <dl id="dim"></dl>
                </li>
            </ul>

            <div class="chart-show">
                <table class="mui-charts-table" >
                    <tr id="chart_header"></tr>
                </table>
                <div class="chart-title">走势图</div>
                <div id="data_charts"></div>
            </div>
            <hr>
            <div class="chart-table">
                <div class="chart-title">详细数据</div>
                <div id="mg_talbe"></div>
            </div>

        </div>
    </div>
</div>

<div id="blk">
    <div id="blk_kpi" type="kpi" class="blk_view kpi" mod="bottom_box">
        <div class="check_box">
            <dl id="kpi_data" title="客户端上报数据"></dl>
            <dl id="kpi_stat" title="统计扩展数据"></dl>
        </div>
    </div>
</div>


<link href="<?php echo $commonPath;?>/css/gri.controls.css?v=<?php echo $version;?>" rel="stylesheet" />
<link href="<?php echo $commonPath;?>/css/mgchart.css?v=<?php echo $version;?>" rel="stylesheet" />
<script src="<?php echo $commonPath;?>/js/highcharts.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $commonPath;?>/js/mgchart.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $commonPath;?>/js/jquery.loadmask.min.js?v=<?php echo $version;?>"></script>
<script src="<?php echo $commonPath;?>/js/gri.dateRange.js?v=<?php echo $version;?>"></script>
<style type="text/css">
#dim dd.dim_execute_btn a {
    /*background-color: #B4D66F;*/
    background: -webkit-gradient(linear,left top,left bottom,from(#77c92a),color-stop(0.5,#5fb321),to(#479d19));
}
</style>
<script type="text/javascript">
    $(function(){

        var dateRange = new pickerDateRange("date_range",'date', {
            theme : 'ta',
            isTodayValid : 1,
            startDate : "<?php echo $sdate;?>",
            endDate : "<?php echo $edate;?>",
            minValidDate : 1379174400,
            needCompare : 0,
            success : function (dateObj){
                $("#date_range").attr("sdate", dateObj.startDate);
                $("#date_range").attr("edate", dateObj.endDate);
                $("#date_range").attr("csdate", "");
                $("#date_range").attr("cedate", "");
                report.doAction();
            }
        });


        report=new Mg.Report();
        report.setDateRangePlugin("#date_range").init(<?php echo $chartConfig;?>);


    // 时间选择 改变时候直接提交 dateRange.submitBtn为对应提交按钮
    $("#"+dateRange.submitBtn).click(function(){
        submitForm()
    });
    $(".ta_select_day").click(function(){
        submitForm()
    });
    $("#operate_type").change(function(){
        submitForm()
    })
    $("#account_type").change(function(){
        submitForm()
    })

    function submitForm(){
        sdate = $("#date_range").attr("sdate")
        edate = $("#date_range").attr("edate")

        //window.location.href='/Advertiser/Account/log/?sdate=' + sdate + "&edate=" + edate + "&operate_type="+ operate_type + "&account_type="+ account_type;
    }

})
</script>
<?php echo $this->render("layout/footer.phtml");?>
