<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
	<li ><a href="<?php echo $appListUrl;?>">应用管理</a></li>
    <li class="current"><a href="<?php echo $positionListUrl;?>">广告位管理</a></li>
		
	</ul>
</div>
<form action="<?php echo $origainalityListUrl;?>" method="get">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="app_key" type="hidden" value="<?php echo $app_key;?>" />
<div class="table_full">
	<table width="100%">
  	     <tr class="tr">
            <th class="th">广告位key</th>
			<td class="td"><input type="text" class="iText" name="dever_pos_key" value="<?php echo $search['dever_pos_key'];?>"></td>
            <th class="th">广告位形式</th>
            <td class="td">
                <select name="pos_key_type" class="wa">
                <option  value="0">全部</option>
                     <?php foreach ($adType as $key =>$val){?>
                <option  value="<?php echo $key; ?>" <?php echo  $search['pos_key_type'] == $key?'selected=selected':''?> ><?php echo $val; ?></option>
                <?php }?>
                </select>
            </td>
            <th class="th">应用名称</th>
			<td class="td"><input type="text" class="iText" name="app_name" value="<?php echo $search['app_name'];?>"></td>
            <th class="th">app_key</th>
			<td class="td"><input type="text" class="iText" name="app_key" value="<?php echo $search['app_key'];?>"></td>
    	</tr>
	</table>
</div>
<div class="mb10 tac"><span class="btn"><span><button type="submit">搜 索</button></span></span></div>
</form>
<form id="batchForm" action="<?php echo $batchUpdateCheckUrl;?>" method="post">
<input name="token" type="hidden" value="<?php echo $token;?>" />
<input name="action" id="action" type="hidden" value="" />
<div class="h_a">
	<span>共<?php echo $total;?>条结果</span>
</div>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
		    <td >广告位名称</td>	
		    <td>广告位key</td> 
            <td>广告位形式</td>
            <td>应用名称</td>
            <td>app_key</td>
            <td>平台</td>
		    <td>广告位状态</td>    
			
		</tr>
	<?php foreach ($positoinList as $key =>$value){?>
		<tr class="ct">
		    <td><?php echo $value['dever_pos_name'];?></td>	
			<td><?php echo $value['dever_pos_key'];?></td>
            <td><?php echo $adType[$value['pos_key_type']];?></td>
			<td><?php echo $value['app_name'];?></td>
            <td><?php echo $value['app_key'];?></td>
            <td><?php echo $value['platform'] == 1?'Android':'IOS';?></td>
            <td><?php echo $posState[$value['state']];?></td>
		</tr>
		<?php }?>
	</table>
</div>
</form>
<div class="mr10 cc tc">
<?php echo $pager;?>
</div>



<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datetimepicker();
     $('#end_time').datetimepicker();
	ajaxForm('addAdOriginalityForm',function(ret){
		ajaxRedirect(ret, baseurl+'<?php echo $origainalityListUrl; ?>');
	});
	


});
</script>
<?php echo $this->render("layout/footer.phtml");?>
