<?php echo $this->render("layout/header.phtml");?>
    <div class="colMain">
        <div class="title">
        <p class="fl"><?php if($result['oid'] && !$result['clone']){echo '编辑';}else{echo '创建';} ?>广告定向</p>
        </div>
        <div class="main">
            <div class="app-detail">
                <form action="<?php echo $addAdStep3PostUrl; ?>" method="POST"  id="addFrom" >
                	<input name="token" value="<?php echo $token;?>" type="hidden" />
                    <input type="hidden" name="oid"   id=""  value='<?php echo $result['oid']; ?>' />
                    <input type="hidden" name="clone"   id=""  value='<?php echo $result['clone']; ?>' />
                    <ul class="form"  id="directContent">
                        <li>
                            <span class="label">使用定向：</span>
                            <div class="fc">
                                <select id="targeting_id" name="targeting_id" class="select">
                                    <option value="" selected="">请选择</option>
                                    <?php foreach ($targetinglist as $key=>$val){?>
                                    <option value="<?php echo $key; ?>" <?php echo  $result['targeting_id'] == $key?'selected=selected':''; ?> ><?php echo $val['targeting_name']; ?></option>
                                    <?php }?>
                                </select>
                            </div>
                        </li>
                         <li>
                            <span class="label">计费类型：</span>
                            <div class="fc">
                                <select name="bid_type">
                                     <option value="" selected="">请选择</option>
                                     <?php foreach ($gdt_bid_type as $key=>$val){?>
                                     <option   value="<?php echo $key; ?>"  <?php echo  $result['bid_type'] == $key?'selected=selected':''; ?>   ><?php echo $val;  ?></option>
                                     <?php }?>
                                </select>                   
                            </div>
                        </li>
                         <li> 
                            <span class="label">广告出价：</span>
                            <div class="fc">
                               <input name="bid_amount" type="text" id="bid_amount" value="<?php echo  $result['bid_amount'] ?>" class="iText " > 分/click        
                            </div>
                        </li>  
                        <li class="line"></li> 
                        <li> 
                            <div class="fc cc">
                              <?php $forwardUrl =  $addAdStep2Url;
                                    if($result['oid'])  $forwardUrl .= "?oid=".$result['oid'];
                                    if($result['clone'])  $forwardUrl .= "&clone=".$result['clone'];
                                    if($result['oid']) {$forwardUrl .= "&step=2";}else{$forwardUrl .= "?step=2";}
                              ?>
                              <input type="button"  onclick="javascript:forwardToPrePage('<?php echo $forwardUrl; ?>');" value="上一步" class="submit btn">
                              <input type="submit"  value="下一步" class="submit btn">      
                            </div>       
                        </li>
                    </ul>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
var oid = '<?php echo $result['oid']; ?>';
var clone = '<?php echo $result['clone']; ?>';
var nextUrl = '<?php echo $addAdStep4Url; ?>';
if(oid){
	nextUrl +='?oid='+oid;
}
if(clone){
	nextUrl +='&clone='+clone;
}
//广告表单数据提交
$(document).ready(function(){
	ajaxForm('addFrom',function(ret){
		ajaxRedirect(ret, baseurl+nextUrl);
	});
});

</script>
<?php echo $this->render("layout/footer.phtml");?>