<?php echo $this->render("layout/header.phtml");?>
<div class="colMain" style="min-height: 196px;">
	<div class="title">
		<p class="fl">广告管理列表</p>
	</div>
	<div class="main">
		<form id="batchForm" action="<?php echo $batchUpdateAdInfoUrl;?>" method="post">
        <input name="token" type="hidden" value="<?php echo $token;?>" />
        <input name="action" id="action" type="hidden" value="" />
        <input name="value" id="value" type="hidden" value="" />
    		<div class="content">
    			<div class="grid">
    				<table>
    					<thead>
    						<tr>
                                <th>本地广告ID</th>
                                <th>广点通广告ID</th>
                                <th>推广计划ID</th>
                                <th>广告名称</th>
                                <th>广点通定向id</th>
                                <th>配置状态</th>
                                <th>审核状态</th>
                                <th>审核消息</th>
                                <th>投放日期</th>
                                <th>投放时间段</th>
                                <th>计费类型</th>
                                <th>出价（分）</th>
                                <th>创建时间</th>
                                <th>操作</th>
                            </tr>
    					</thead>
    				 <?php if(is_array($list)){ foreach ($list as $key=>$val ){?>
    					<tr>
							<td><?php echo $val['outer_adgroup_id']; ?></td>
                            <td><?php echo $val['adgroup_id']; ?></td>
                            <td><?php echo $val['campaign_id']; ?></td>
                            <td>
                                <span class="name_span"><a href="<?php echo $webRoot.$creativeListUrl.'?adgroup_id='.$val['adgroup_id'] ; ?>" title="编辑"><?php echo $val['adgroup_name']; ?></a> </span>
    						</td>
                            <td><?php echo $val['targeting_id'];?></td>
                            <td style="color:<?php echo $val['configured_status_color']; ?>;"><?php echo $val['configured_status_cn'];?></td>
                            <td style="color:<?php echo $val['system_status_color']; ?>;"><?php echo $val['system_status_cn'];?></td>
                            <td title="<?php echo $val['audit_message'];?>" style="color:grey;cursor:pointer;"><?php echo mb_substr($val['audit_message'], 1,10,"UTF-8");?></td>
                            <td><?php echo $val['begin_date'];?> - <?php echo $val['end_date'];?></td>
                            <td><?php echo $val['start_hour'];?> - <?php echo $val['end_hour'];?></td>
    						<td><?php echo $val['bid_type_cn'];?></td>
    						<td><?php echo $val['bid_amount'];?></td>
                            <td><?php echo date("Y-m-d H:i:s", $val['created_time']);?></td>
                            <td>
                                <a href="<?php echo $addAdStep1Url. "?oid=". $val['adgroup_id'] ?>">编辑</a>&nbsp;
                                <a href="<?php echo $addAdStep1Url. "?oid=". $val['adgroup_id']."&clone=1" ?>">复制</a>&nbsp;
                                <a onclick="deleteOne('<?php echo $delGdtAdUrl;?>/?adgroup_id=<?php echo $val['adgroup_id'];?>', '是否要删除该广告？', event);" href='javascript:'>删除</a>&nbsp;
                            </td>
<!--                            
1. 广告字段。最好可以按照创建时间筛选
   1）广告id
   2）广点通广告id
   3）广点通推广计划id
   4）广告名称
   6）广点通定向id
   7）投放日期：开始投放日期-结束投放日期
   8）投放时间段：要处理成 周一 0:00-24:00 周二0:00-24:00
   9）计费方式：CPC/CPM，要处理下
   10）出价（分）
   11）创建时间-->
    					</tr>
    				   <?php }}?>
    				</table>
    			</div>
    			<div class="mt10 cc tc">
                    <?php echo $pager;?>
                </div>
    		</div>
    		</form>
	</div>
</div>
</div>



<div id="editStatus" style="margin: 20px; line-height: 32px; font-size: 14px; display: none">
  <ul class="form">
		  <li> 
			<span class="label">状态：</span>
			<div class="fc">
			    <?php foreach ($modifyStatus as $key=>$val ){?>
			 	<p><input type="radio" value="<?php echo $key; ?>" name="editStatus" class="radio"><?php echo $val; ?></p>
	        <?php }?>
            </div>
		 </li>
	</ul>
</div>

<div id="editPrice" style="margin: 20px; line-height: 32px; font-size: 14px; display: none">
  <ul class="form">
	<li> 
		<span class="label">出价：</span>
		<div class="fc">
            <label><input name="edit_price" type="text" value="" class="iText " > </label> </p>
        </div>
	 </li>
	</ul>
</div>




<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
//广告表单数据提交
$(document).ready(function(){
	 $('#start_time').datepicker();
     $('#end_time').datepicker();
	ajaxForm('batchForm',function(ret){
		ajaxRedirect(ret, baseurl+'/Advertiser/Delivery/index');
	});

    $(".edit_name").click(function(){
        name = $(this).attr('ad_name')
        id = $(this).attr('ad_id')
        inputId = 'modify_name' + id
        $(this).siblings('.input').remove();
        str = '<input type="text" class="input" value="'+ name +'"   id="'+inputId+'">'
        $(this).siblings('.name_span').hide().after(str);
        $("#" + inputId).focus()
        $("#" + inputId).blur(function(){
            adName = $("#"+inputId).val();
            if( $.trim(adName) == ''){
        		return false;
             }
            $.ajax({
                url:  baseurl+"<?php echo $updateAdNameUrl  ?>",
                type: "POST",
                dataType : 'json',
                data : { 'token':token, 'id':id, 'ad_name': adName},
                success: function(ret) {
                    if (ret.success) {
                        showMsg('', ret.msg);
                        setTimeout(function() {
                            location.reload();
                        }, 500);
                    } else {
                        showError('', ret.msg);
                    }
                    $("#" + inputId).siblings('.name_span').show()
                    $("#" + inputId).remove()
                }
            });
        });
    });
    
})

function editPrice(title){
	return $("#editPrice").dialog({
					title : title,
					draggable : false,
					width:600,
					modal : true,
					resizable : false,
					buttons: {
					        'ok': function() {
					            edit_price = $.trim($("input[name='edit_price']").val());
					 
					         	if(edit_price == ''){
					        		alert("出价不能为空!");
					                return false;
					        	}
					        	$('#action').val('price');
					        	$('#value').val(edit_price);
					        	$("#batchForm").submit();
					        },
					        Cancel: function() {
					            $(this).dialog('close');
					        }
					    }
				});
}

function editStatus(title){
	return $("#editStatus").dialog({
					title : title,
					draggable : false,
					width:600,
					modal : true,
					resizable : false,
					buttons: {
					        'ok': function() {
					        	status =  $("input[name='editStatus']:checked").val();			
					           	if(status==null || status == 'undefined') {
					                alert("状态没选中!");
					                return false;
					            }
					        	$('#action').val('status');
					        	$('#value').val(status);
					        	$("#batchForm").submit();
					     	
					        },
					        Cancel: function() {
					            $(this).dialog('close');
					        }
					    }
				});
}


</script>
<?php echo $this->render("layout/footer.phtml");?>