<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, user-scalable=0, minimal-ui" charset="UTF-8">
    <meta content="telephone=no" name="format-detection">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="Keywords" content="手游,地铁跑酷">
    <meta name="author" content="idreamsky">
    <title>地铁跑酷兑换码</title>
    <script src="http://dl2.gxpan.cn/landingpage/cats/common/js/jquery-3.2.1.min.js"></script>
    <script>
        document.documentElement.style.fontSize = (document.documentElement.clientWidth || document.body.clientWidth) /
            7.5 + 'px';
    </script>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        img {
            vertical-align: top;
        }

        body,
        html {
            margin: 0;
            padding: 0;
            background: #ebecee;
            width: 100%;
            height: 100%;
            font-family:"Microsoft Yahei";
        }

        .wrapper {
            position: relative;
            width: 100%;
            height: 100%;
        }

        .banner {
            position: relative;
            width: 100%;

        }

        .banner img {
            width: 100%;
        }

        .main {
            position: relative;
            width: 100%;
        }

        .app-info {
            padding: 0.23rem 0.22rem;
            width: 100%;
            position: relative;
            box-sizing: border-box;
            overflow: hidden;
        }

        .app-info i {
            float: left;
            display: block;
            width: 1.29rem;
            height: 1.29rem;
        }

        .app-info i img {
            width: 1.29rem;
            height: 1.29rem;
        }

        .app-info .title {
            position: absolute;
            left: 1.65rem;
            top: 0.48rem;
            font-size: 0.32rem;
            color: #333333;
            font-weight: bold;

        }

        .app-info .desc {
            position: absolute;
            left: 1.65rem;
            top: 0.9rem;
            font-size: 0.26rem;
            color: #333333;
        }

        .app-info .qr-code {
            float: right;
            width: 2.5rem;
            height: 1.2rem;
            margin-top: 0.1rem;
        }

        .app-info .qr-code img {
            width: 2.5rem;
            height: 1rem;
            border-radius: 0.04rem;
        }

        .content {
            position: absolute;
            left: 0;
            top: 4.9rem;
            right: 0;
            bottom: 0;
            padding: 0 0.29rem 0.35rem 0.29rem;
            box-sizing: border-box;
        }

        .content .content-wrap {
            width: 100%;
            height: 100%;
            background: #fff;
            box-shadow: 0.00rem 0.01rem 0.03rem #999;
            position: relative;
        }

        .content .content-wrap .title {
            position: absolute;
            width: 3.17rem;
            height: 6.2rem;
            background: url("<?php echo $staticPath;?>/coupon/images/03.png") no-repeat;
            background-size: 100% auto;
            left: 50%;
            top: 0.19rem;
            margin-left: -1.585rem;
            font-size: 0.22rem;
            color: #fff;
            text-align: center;
            line-height: 0.47rem;
            font-weight: bold;

        }

        .content .content-wrap i {
            position: absolute;
            right: 0;
            top: 0;
            width: 0.46rem;
            height: 0.48rem;
        }

        .content .content-wrap i img {
            width: 100%;
        }

        .content .content-wrap .desc {
            position: absolute;
            left: 0;
            top: 1rem;
            bottom: 0;
            right: 0;
        }


        .content .content-wrap .code {
            position: absolute;
            width: 3.17rem;
            height: 6.2rem;
            background: url("<?php echo $staticPath;?>/coupon/images/04.png") no-repeat;
            background-size: 100% auto;
            left: 50%;
            top: 1.8rem;
            margin-left: -1.585rem;
            font-size: 0.22rem;
            color: #000;
            text-align: center;
            line-height: 0.47rem;
            font-weight: bold;
        }

        .content .content-wrap .c-title {
            position: absolute;
            width: 3.17rem;
            height: 6.2rem;
            left: 50%;
            top: 1.2rem;
            margin-left: -1.585rem;
            font-size: 0.25rem;
            color: #000;
            text-align: center;
            line-height: 0.47rem;
            font-weight: bold;
        }

        .content .content-wrap .desc {
            position: absolute;
            width: 3.17rem;
            height: 6.2rem;
            left: 50%;
            top: 2.2rem;
            margin-left: -1.585rem;
            font-size: 0.25rem;
            color: #CDA57E;
            text-align: center;
            line-height: 0.47rem;
            font-weight: bold;
        }

        .content .content-wrap .rule {
            position: absolute;
            float: left;
            text-align: left;
            color: #333333;
            top: 3rem;
            font-size: 0.26rem;
            font-weight: bold;
            line-height: 0.4rem;
            padding-left: 0.1rem;
        }


    </style>
</head>

<body>
<div class="wrapper">
    <div class="banner">
        <img src="http://dl2.gxpan.cn/landingpage/common/coupon/dt-banner.png" />
    </div>
    <div class="main">
        <div class="app-info">
            <i>
                <img src="http://dl2.gxpan.cn/landingpage/common/coupon/dt-icon.png" />
            </i>
            <p class="title">地铁跑酷</p>
            <p class="desc">经典跑酷游戏</p>
            <div class="qr-code">
                <a href="http://a.app.qq.com/o/simple.jsp?pkgname=com.kiloo.subwaysurf"><img src="<?php echo $staticPath;?>/coupon/images/11.png" /></a>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="content-wrap">
            <div class="title">游戏兑换码使用规则</div>
            <i>
                <img src="<?php echo $staticPath;?>/coupon/images/05.png" />
            </i>
            <div class="c-title">礼物兑换码</div>
            <div class="code"><p><?php echo $code;?></p></div>
            <div class="desc">(长按可以复制兑换码)</div>
            <div class="rule">复制兑换码，打开地铁跑酷，进入游戏后，点击游戏界面右上角的"设置"，在设置界面选择"兑换码"，在输入框输入兑换码即可获得相应的游戏礼包。</div>
        </div>
    </div>
</div>
</body>


</html>