<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, user-scalable=0, minimal-ui" charset="UTF-8">
    <meta content="telephone=no" name="format-detection">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="Keywords" content="腾讯视频好时光">
    <meta name="author" content="idreamsky">
    <title>腾讯视频好时光</title>
    <script src="http://dl2.gxpan.cn/landingpage/cats/common/js/jquery-3.2.1.min.js"></script>
    <link rel="stylesheet" href="<?php echo $staticPath;?>/coupon/css/coupon.css">
    <script>
        document.documentElement.style.fontSize = (document.documentElement.clientWidth || document.body.clientWidth) /
            7.5 + 'px';
    </script>
    <style>

    </style>
</head>

<body>
<div class="wrapper">
    <div class="banner">
        <i><img src="<?php echo $staticPath;?>/coupon/images/09.png"></i>
        <div class="title">深圳腾讯视频好时光梅林店</div>
        <div class="c-title">【KPL线下合作观赛点】</div>
        <div class="address">
            <i><img src="<?php echo $staticPath;?>/coupon/images/10.png"></i>
            <div class="address-desc">深圳市上梅林卓悦汇购物中心六楼</div>
        </div>
        <img src="<?php echo $staticPath;?>/coupon/images/img_2.png" />
    </div>
    <div class="content">
        <div class="content-wrap">
            <div class="title">兑换码使用规则</div>
            <i>
                <img src="<?php echo $staticPath;?>/coupon/images/05.png" />
            </i>
            <div class="c-title">战队签名照片</div>
            <div class="code"><p><?php echo $code;?></p></div>
            <div class="desc">(请出示兑换码)</div>
            <div class="rule">礼品兑换规则:凭兑换码店内兑换战队签名照片，每个兑换码仅限兑换一次，不能重复兑换</div>
        </div>

        <div class="content-wrap-two">
            <i><img src="<?php echo $staticPath;?>/coupon/images/20.png"></i>
            <div class="title">战队签名照片</div>
            <div class="desc">店内出示兑换码，即可获得相关礼品；腾讯视频好时光地址：深圳市上梅林卓悦汇购物中心六楼</div>
        </div>
    </div>

</div>
</body>


</html>