<ul class="form">
    <li>
        <span class="label">页面标题：</span>
        <div class="fc">
            <input name="title" type="text" value="<?php echo $result['title']; ?>" class="iText " >
        </div>
    </li>
    <li>
        <span class="label">链接地址：</span>
        <div class="fc">
            <input name="url" type="text" value="<?php echo $result['url']; ?>" class="iText " >
        </div>
    </li>
</ul>