<?php echo $this->render("./spm/layout/header.phtml"); ?>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <!-- 头部区域 begin  -->
    <?php echo $this->render("./spm/layout/topMenu.phtml"); ?>
    <!-- 头部区域 end   -->

    <!-- content begin   -->
    <div class="content-wrap">
        <!-- leftMenu begin   -->
        <?php echo $this->render("./spm/layout/leftMenu.phtml"); ?>
        <!-- leftMenu begin   -->

        <div class="content-main">
            <div class="wrapper">
                <!-- title begin -->
                <div class="title">
                    <p>编辑广告成本</p>
                </div>
                <!-- title end  -->
                <!-- form begin -->
                <form class="layui-form">
                    <!-- 基本信息 begin -->
                    <p class="padding-top20"></p>
                    <div class="subtitle"><p>基本信息:</p></div>
                    <div class="inputs-wrap">
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">产品</label>
                            <div class="layui-input-block long-label-input">
                                <input type="hidden" name="id" value="<?php echo $entryPlan['id']; ?>" />
                                <input type="hidden" name="app_id" value="<?php echo $entryPlan['app_id']; ?>" />
                                <input type="hidden" name="channel_group_id" value="<?php echo $entryPlan['channel_group_id']; ?>" />
                                <input type="text" name="app_name" placeholder="" value="<?php echo $entryPlan['app_name']; ?>" readonly="readonly"  class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">投放渠道组</label>
                            <div class="layui-input-block long-label-input">
                                <input type="text" name="channel_group_name" placeholder="" value="<?php echo $entryPlan['channel_group_name']; ?>" readonly="readonly" class="layui-input">
                            </div>
                        </div>
                    </div>
                    <div class="subtitle"><p>可调参数:</p></div>
                    <div class="inputs-wrap">
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">开始日期</label>
                            <div class="layui-input-block long-label-input">
                                <input class="layui-input" name="start_date" id="start_date" placeholder="" value="<?php echo $entryPlan['start_date']; ?>" type="text">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">结束日期</label>
                            <div class="layui-input-block long-label-input">
                                <input class="layui-input" name="end_date" id="end_date" placeholder="" value="<?php echo $entryPlan['end_date']; ?>" type="text">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">日均消耗金额</label>
                            <div class="layui-input-block long-label-input">
                                <input type="text" name="daily_consumption" placeholder="" value="<?php echo $entryPlan['daily_consumption']; ?>" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label long-label">日均量</label>
                            <div class="layui-input-block long-label-input">
                                <input type="text" name="daily_amount" placeholder="" value="<?php echo $entryPlan['daily_amount']; ?>" class="layui-input">
                            </div>
                        </div>
                    </div>

                    <hr class="layui-bg-gray">
                    <div class="layui-form-item">
                        <div class="layui-input-block">
                            <button type="button" class="layui-btn layui-btn-normal" lay-submit lay-filter="submit_form">保存</button>
                            <button id="cancel" type="reset" class="layui-btn layui-btn-primary">取消</button>
                        </div>
                    </div>
                </form>
                <!-- form end  -->
            </div>
        </div>
        <!-- content end     -->
    </div>
    <script>
        /* 请求链接 */
        var editPlanPostUrl = baseurl + '<?php echo $editPlanPostUrl; ?>'; // 提交表单
        var planUrl = baseurl + '<?php echo $planUrl; ?>'; //  列表页面
        //JavaScript代码区域
        layui.use(['element','form','laydate'], function(){
            var element = layui.element;
            var form = layui.form;
            var laydate = layui.laydate;

            //常规用法
            laydate.render({
                elem: '#start_date'
            });
            laydate.render({
                elem: '#end_date'
            });

            //表单提交
            form.on('submit(submit_form)', function(data){
                data.field.token = token;
                $.ajax({
                    url : editPlanPostUrl,
                    async: false,
                    data : data.field,
                    type : 'post',
                    dataType : 'json',
                    jsonp : 'callback',
                    success:function(data){
                        layer.msg(data.msg);
                        if(data.success){
                            setTimeout(function(){
                                window.location.href = planUrl;
                            },500);
                        }
                    },
                    error:function(xhr,msg,e){
                        layer.msg(msg);
                    }
                });
                return false;
            });
            // 取消
            $("#cancel").click(function(){
                window.location.href = planUrl;
            });
        });
    </script>
</body>
</html>
