<?php echo $this->render("layout/header_layui.phtml");?>
<body>
    <div class="layui-fluid wrapper">
        <div class="layui-row layui-col-space30">
            <!-- left begin -->
             <?php echo $this->render("common/appinfo.phtml");?>
            <!-- left end  -->
            <!-- right begin  -->
            <?php echo $this->render("baseinfo/adsrelconfig/layout/main.phtml");?>
            <!-- right end   -->
        </div>
    </div>
</body>