<?php echo $this->render("./spm/layout/header.phtml");?>

<body class="layui-layout-body">
    <div class="layui-layout layui-layout-admin">
        <!-- 头部区域 begin  -->
        <?php echo $this->render("./spm/layout/topMenu.phtml");?>
        <!-- 头部区域 end   -->
        <!-- content begin   -->
        <div class="content-wrap">
            <!-- leftMenu begin   -->
            <?php echo $this->render("./spm/layout/leftMenu.phtml");?>
            <!-- leftMenu begin   -->
            <link rel="stylesheet" type="text/css" href="<?php echo $staticPath; ?>/js/admin/lay/css/layui.css" />
            <link rel="stylesheet" type="text/css" href="<?php echo $staticPath; ?>/css/selectBox.css" />

            <style>
                * {
                    margin: 0;
                    padding: 0;
                }

                ul,
                li {
                    list-style: none;
                }

                html,
                body {
                    font-family: 'STHeiti Light [STXihei]', Helvetica, 'Hiragino Sans GB', 'Microsoft Yahei', '微软雅黑', Arial, sans-serif;
                    font-size: 14px;
                    background: #e5e6eb;
                }

                .wrapper {
                    background: #fff;
                    padding: 5px 20px 50px 20px;
                    box-sizing: border-box;
                }

                .search-wrap {
                    padding-top: 2px;
                }

                .tchar-side {
                    padding: 5px 10px;
                    height: 600px;
                    width: 100%;
                }
            </style>
            <div class="content-main">
                <div class="wrapper">
                    <ul class="layui-tab-title">
                        <li class="layui-this">
                            <a href="">活动报表</a>
                        </li>
                        <li>
                            <a href="ltv" class="active">活动LTV</a>
                        </li>
                        <li>
                            <a href="retention">活动留存</a>
                        </li>
                    </ul>


                    <div class="layui-fluid wrapper">
                        <div class="layui-row layui-col-space30">
                            <!-- 广告用户LTV数据 begin -->
                            <div class="layui-col-xs12 layui-col-sm12 layui-col-md12 ">
                                <div class="layui-collapse">
                                    <!--  广告LTV报表   begin -->
                                    <div class="layui-colla-item">
                                        <h2 class="layui-colla-title">广告LTV报表</h2>
                                        <div class="layui-colla-content layui-show">
                                            <!--  条件搜索 begin -->
                                            <div class="search-wrap">
                                                <form id='formDemo1' class="layui-form" action="getLtvData" data-id="1">
                                                    <div class="layui-inline">
                                                        <input type="text" name="days" class="layui-input" id="datetime1">
                                                    </div>
                                                    <div class="layui-inline activity_id"></div>
                                                    <button class="layui-btn lay-submit" lay-submit lay-filter="formDemo">立即查询</button>
                                                </form>
                                            </div>
                                            <!--  条件搜索 end -->
                                            <div class="tchar-side" id="chart1"></div>
                                        </div>
                                    </div>
                                    <!-- 广告LTV报表   end   -->
                                    <!-- 广告LTV详情   begin -->
                                    <div class="layui-colla-item">
                                        <h2 class="layui-colla-title">广告LTV详情
                                            <a data-table="table1" class="export" style="float:right">导出</a>
                                        </h2>
                                        <div class="layui-colla-content layui-show">
                                            <table id="table1" lay-filter="test"></table>
                                        </div>
                                    </div>
                                    <!-- 广告LTV详情  end -->
                                </div>
                            </div>
                            <!-- 广告用户LTV数据 end  -->
                        </div>
                    </div>
                    <script src="<?php echo $staticPath; ?>/js/admin/lay/layui.js"></script>
                    <script src="<?php echo $staticPath; ?>/js/common/jquery.js"></script>
                    <script type="text/javascript" src="<?php echo $staticPath; ?>/js/admin/lay/echarts.min.js"></script>
                    <script type="text/javascript" src="<?php echo $staticPath; ?>/js/common/selectBox.js"></script>
                    <script>
                        ;
                        (function () {
                            $(function () {
                                $(".export").click(function (e) {
                                    var uri = 'data:application/vnd.ms-excel;base64,',
                                        text = '',
                                        template =
                                        '<html><head><meta charset="UTF-8"></head><body><table border="1">{table}</table></body></html>',
                                        base64 = function (s) {
                                            return window.btoa(unescape(encodeURIComponent(s)))
                                        },
                                        format = function (s, c) {
                                            return s.replace(/{(\w+)}/g,
                                                function (m, p) {
                                                    return c[p];
                                                })
                                        }
                                    $(this).parent().parent().find("table.layui-table").each(
                                        function (
                                            index, el) {
                                            if (index < 2) {
                                                text += $(this).html();
                                            }
                                        });
                                    var ctx = {
                                        worksheet: 'sheet1',
                                        table: text
                                    }
                                    window.location.href = uri + base64(format(template, ctx))
                                    // this.href= window.URL.createObjectURL(new Blob([text], {type: 'text/plain'}));
                                    e.stopPropagation();
                                });
                                $(".activity_id").selectBox({
                                    name: "activity_id",
                                    title: "活动",
                                    data: <?php echo json_encode($activitys); ?>
                                });
                            });

                            function to_array(obj) {
                                var arr = []
                                for (var i in obj) {
                                    arr.push(obj[i]);
                                }
                                return arr;
                            };

                            function table_format(data) {
                                var rdata = []
                                var rdays = []
                                var items = {}
                                for (var i = 0; i <= data['days']; i++) {
                                    rdays.push(i)
                                };
                                for (var key in data['data']) {
                                    if (!items.hasOwnProperty(key)) {
                                        items[key] = {}
                                    }
                                    if (data.hasOwnProperty('dims') && data['dims'].length) {
                                        for (var dim in data['dims']) {
                                            items[key][data['dims'][dim]] = data['data'][key][data['dims'][dim]]
                                        }
                                    } else {
                                        // items[key].push('总体LTV')
                                    }
                                    for (var rday in rdays) {
                                        items[key]['ltv' + rday] = 0;
                                    }
                                    for (var rday in data['data'][key]['ltv']) {
                                        items[key]['ltv' + rday] = parseFloat(data['data'][key]['ltv'][rday])
                                    }
                                    rdata.push(items[key]);
                                }

                                return rdata;
                            }

                            function chart_render(chart, data) {
                                var legend = []
                                var xdata = []
                                var series = []
                                var rdays = []
                                var items = {}

                                for (var i = 0; i <= data['days']; i++) {
                                    rdays.push(i)
                                };


                                for (var key in data['data']) {
                                    if (!items.hasOwnProperty(key)) {
                                        items[key] = {}
                                    }

                                    for (var rday in rdays) {
                                        items[key][rday] = 0;
                                    }
                                }

                                var maxSize = 5
                                for (var key in data['data']) {
                                    for (var rday in data['data'][key]['ltv']) {
                                        items[key][rday] = parseFloat(data['data'][key]['ltv'][rday])
                                    }
                                    var mySize = data['data'][key]['legend'].length
                                    if (mySize > maxSize) {
                                        maxSize = mySize;
                                    }
                                    legend.push(data['data'][key]['legend'])
                                    series.push({
                                        name: data['data'][key]['legend'],
                                        type: 'line',
                                        data: to_array(items[key])
                                    })
                                }


                                var option = {
                                    title: {
                                        text: data['title']
                                    },
                                    tooltip: {
                                        trigger: 'axis'
                                    },
                                    legend: {
                                        data: legend,
                                        type: 'scroll',
                                        orient: 'vertical',
                                        right: 0,
                                        top: 50,
                                        bottom: '3%',
                                        textStyle: {
                                            fontSize: 10
                                        }
                                    },
                                    grid: {
                                        left: '3%',
                                        right: maxSize * 8 + 30,
                                        bottom: '3%',
                                        containLabel: true
                                    },
                                    toolbox: {
                                        feature: {
                                            saveAsImage: {}
                                        }
                                    },
                                    xAxis: {
                                        type: 'category',
                                        boundaryGap: false,
                                        data: to_array(rdays)
                                    },
                                    yAxis: {
                                        type: 'value'
                                    },
                                    series: series
                                };
                                chart.setOption(option, true);
                            }

                            layui.use(['element', 'laydate', 'form', 'table'], function () {
                                var element = layui.element;
                                var laydate = layui.laydate;
                                var form = layui.form;
                                var table = layui.table;
                                laydate.render({
                                    elem: '#datetime1',
                                    range: true,
                                    value: '<?php echo $sdate." - ".$edate ?>'
                                });
                                laydate.render({
                                    elem: '#datetime2',
                                    range: true,
                                    value: '<?php echo $sdate." - ".$edate ?>'
                                });

                                form.on('submit(formDemo)', function (data) {
                                    var formId = parseInt(data.form.id.replace(/[^0-9]/ig, ""))
                                    var chart = echarts.init(document.getElementById('chart' +
                                        formId))
                                    chart.showLoading();
                                    layui.$.ajax({
                                        type: 'GET',
                                        data: data.field,
                                        url: data.form.action,
                                        dataType: 'json',
                                        success: function (data) {
                                            if (data.success) {
                                                chart_render(chart, data.data);
                                                table.render({
                                                    elem: "#table" + formId,
                                                    data: table_format(data.data),
                                                    cols: [data.data['cols']],
                                                    page: false,
                                                });
                                            }
                                            chart.hideLoading();

                                        },
                                        error: function (xhr) {
                                            layer.msg("fail");
                                        }
                                    });
                                    return false;
                                });

                                layui.$('.lay-submit').click();

                            });

                        })();
                    </script>
                </div>
            </div>
        </div>
    </div>


</body>

</html>