<?php echo $this->render("layout/header.phtml"); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<link rel="stylesheet" type="text/css" href="<?php echo $staticPath?>/css/layui.css"/>
<style>
    *{ margin: 0; padding: 0;}
    ul,li{ list-style: none; }
    html,body{
        font-family: 'STHeiti Light [STXihei]', Helvetica, 'Hiragino Sans GB', 'Microsoft Yahei', '微软雅黑', Arial, sans-serif;
        font-size: 14px;
    }
    .wrapper{
        background:#f2f2f2; padding:5px 20px 50px 20px; box-sizing:border-box;
    }
    .items-main-title{ width: 100%; overflow:hidden; padding: 10px 0 5px 0; box-sizing: border-box; border-bottom:1px solid #eee;  }
    .items-main-title p{ float:left; padding-left: 5px; color: #1E9FFF; display: inline-block; font-size: 20px; line-height: 40px;  }
    .items-main-search{ width: 100%;  padding: 10px 0 0 0; }
    .items-main-buttons{ float:right; display: inline-block; }
    .table-wrap{ width: 100%;}
</style>
<body>
<div class="layui-tab">
    <ul class="layui-tab-title">
        <li ><a href="runDetailReport">经营概况</a></li>
        <li class="layui-this"><a href="monthAppReport">月运营明细</a></li>
        <li><a href="weekAppReport">周运营明细</a></li>
    </ul>
    <div class="layui-tab-content">
        <div class="layui-tab-item layui-show">
            <div class="layui-fluid">
                <div class="items-main-title"><p>月运营明细</p></div>
                <!-- top begin -->
                <div class="items-main-search ">
                    <form class="layui-form" action="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">查询年份：</label>
                            <div class="layui-input-inline">
                                <select name="year" lay-filter="year" id="year">
                                    <option value="2017" <?php if($year == 2017) echo "selected";?>>2017</option>
                                    <option value="2018" <?php if($year == 2018) echo "selected";?>>2018</option>
                                    <option value="2019" <?php if($year == 2019) echo "selected";?>>2019</option>
                                    <option value="2020" <?php if($year == 2020) echo "selected";?>>2020</option>
                                </select>
                            </div>
                            <label class="layui-form-label">查询月份：</label>
                            <div class="layui-input-inline">
                                <select name="month" lay-filter="month" id="month">
                                    <option value="" >选择月份</option>
                                    <option value="1" <?php if($month == 1) echo "selected";?>>1</option>
                                    <option value="2" <?php if($month == 2) echo "selected";?>>2</option>
                                    <option value="3" <?php if($month == 3) echo "selected";?>>3</option>
                                    <option value="4" <?php if($month == 4) echo "selected";?>>4</option>
                                    <option value="5" <?php if($month == 5) echo "selected";?>>5</option>
                                    <option value="6" <?php if($month == 6) echo "selected";?>>6</option>
                                    <option value="7" <?php if($month == 7) echo "selected";?>>7</option>
                                    <option value="8" <?php if($month == 8) echo "selected";?>>8</option>
                                    <option value="9" <?php if($month == 9) echo "selected";?>>9</option>
                                    <option value="10" <?php if($month == 10) echo "selected";?>>10</option>
                                    <option value="11" <?php if($month == 11) echo "selected";?>>11</option>
                                    <option value="12" <?php if($month == 12) echo "selected";?>>12</option>
                                </select>
                            </div>
                            <a href="#" id='search' class="layui-btn layui-btn-normal">搜索</a>
                            <div class="items-main-buttons">
                                <a href="setAppKpi" class="layui-btn layui-btn-normal">应用KPI设置</a>
                                <a class="layui-btn layui-btn-normal export">导出为excel</a>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- top end  -->
                <div class="layui-row">
                    <div class="layui-col-xs6">
                        <fieldset class="layui-elem-field layui-field-title" style="margin-top: 30px;">
                            <legend>一.总体月度情况</legend>
                        </fieldset>
                        <blockquote class="layui-elem-quote">
                            截止到<?Php echo $sumData['lastUpdate'];?>:
                            <br>
                            <br>本月共完成收益：<?php echo $sumData['month']['finish_income'];?>元，计划应完成：<?php echo $sumData['month']['plan_income'];?>元，实际完成：<?php echo $sumData['month']['finish_rate'];?>%，差额：<?php echo $sumData['month']['diff'];?>元.
                        </blockquote>
                        <!--  图表1 -->
                        <div class="tchar-side" id="chart1" style="width: 700px;height: 400px;"></div>
                    </div>
                    <div class="layui-col-xs6">
                        <fieldset class="layui-elem-field layui-field-title" style="margin-top: 30px;">
                            <legend>二.各平台月收益情况</legend>
                        </fieldset>
                        <blockquote class="layui-elem-quote">
                            截止到<?Php echo $sumData['lastUpdate'];?>:
                            <br>
                            安卓平台共完成收益：<?php echo $sumData['month']['andiro']['finish_income'];?>元，计划应完成：<?php echo $sumData['month']['andiro']['plan_income'];?>元，实际完成：<?php echo $sumData['month']['andiro']['finish_rate'];?>%，差额：<?php echo $sumData['month']['andiro']['diff'];?>元.
                            <br>
                            IOS平台共完成收益：<?php echo $sumData['month']['ios']['finish_income'];?>元，计划应完成：<?php echo $sumData['month']['ios']['plan_income'];?>元，实际完成：<?php echo $sumData['month']['ios']['finish_rate'];?>%，差额：<?php echo $sumData['month']['ios']['diff'];?>元.
                        </blockquote>
                        <!--  图表2 -->
                        <div class="tchar-side" id="chart2" style="width: 700px;height: 400px;"></div>
                    </div>
                </div>
                <fieldset class="layui-elem-field layui-field-title" style="margin-top: 30px;">
                    <legend>三.详情月度情况 <span style="margin-left: 1200px;"></span><span style="background-color:#66F4DF;min-width:10px;height:20px;">定制渠道</span></legend>
                </fieldset>
                <!-- top end  -->
                <!-- table begin -->
                <div class="table-wrap">
                    <table class="layui-table">
                        <thead>
                        <tr>
                            <th>业务</th>
                            <th>平台</th>
                            <th>应用</th>
                            <th>MAU</th>
                            <th>MAU KPI</th>
                            <th>MAU 完成度</th>
                            <th>游戏覆盖率</th>
                            <th>覆盖率KPI</th>
                            <th>差额</th>
                            <th>ARPU</th>
                            <th>ARPU KPI</th>
                            <th>差额</th>
                            <th>收益</th>
                            <th>收益KPI</th>
                            <th>完成度</th>
                            <th>总计收益</th>
                            <th>总完成度</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach ($data as $type =>$items) {
                        ?>
                        <tr>
                            <td rowspan="<?php echo count($items,COUNT_RECURSIVE)+1;?>"><?php if($type == 1){echo '休闲游戏';}elseif($type == 2){echo '独立游戏';}else{echo '联盟流量';}?></td>
                            <?php foreach ($items as $keys=>$vals){ ?>
                                <td rowspan="<?php echo count($vals)+1;?>"><?php if($keys == 1) echo '安卓'; else echo 'IOS';?></td>
                                <?php foreach($vals as $key=>$val){
                                if($val['is_custom'] == 1) {
                                    echo "<tr style='background-color: #66F4DF'>";
                                }else{
                                    echo "<tr>";
                                }
                                ?>
                                <td><?php echo $val['app_name'];?></td>
                                <td><?php echo $val['mau_sys'];?></td>
                                <td><?php echo $val['mau'];?></td>
                                <td><?php echo $val['mau_diff'];?>%</td>
                                <td><?php echo $val['game_cover_sys'];?>%</td>
                                <td><?php echo $val['game_cover'];?>%</td>
                                <td><?php echo $val['game_cover_diff'];?>%</td>
                                <td><?php echo $val['arpu_sys'];?></td>
                                <td><?php echo $val['arpu'];?></td>
                                <td><?php echo $val['arpu_diff'];?></td>
                                <td><?php echo $val['ad_income_sys'];?></td>
                                <td><?php echo $val['ad_income'];?></td>
                                <td><?php echo $val['ad_income_diff'];?>%</td>
                                <?php if($key == 0){ ?>
                                <td style="background-color: white;" rowspan="<?php echo count($vals)+1;?>"><?php if($keys == 2){echo $sumData['month']['ios']['finish_income'];}else{echo $sumData['month']['andiro']['finish_income'];};?></td>
                                <td style="background-color: white;" rowspan="<?php echo count($vals)+1;?>"><?php if($keys == 2){echo $sumData['month']['ios']['finish_rate'];}else{echo $sumData['month']['andiro']['finish_rate'];};?>%</td>
                                <?php }?>
                                </tr>
                                <?php } ?>
                            <?php }?>
                        </tr>
                        <?php }?>
                        </tbody>
                    </table>
                </div>
                <!-- table end   -->
            </div>
        </div>
        <div class="layui-tab-item">内容2</div>

    </div>
</div>
</body>
</html>
<script src="<?php echo $staticPath; ?>/js/admin/lay/layui.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/admin/lay/echarts.min.js"></script>
<script>
    //注意：导航 依赖 element 模块，否则无法进行功能性操作
    layui.use(['table','form'], function(){
        var form = layui.form;

    });
    $(function(){
        var year = $('#year').val();
        var month = $('#month').val();
        layui.$.ajax({
            type: 'GET',
            data: {year:year,month:month},
            url: 'getRunMonthRepoetDataByajax',
            dataType: 'json',
            success: function(data){
                table1 = document.getElementById('chart1');
                table2 = document.getElementById('chart2');
                chart1=echarts.init(document.getElementById('chart1'));
                chart2=echarts.init(document.getElementById('chart2'));
                chart_render(chart1,data.month);
                chart_render_pie(chart2,data.platform);
                //chart.hideLoading();
            },
            error: function(xhr){
                layer.msg("fail");
            }
        });
        //自适应宽高
        var myChartContainer = function () {
            table1.style.width = window.innerWidth/2+'px';
            table1.style.height = window.innerHeight+'px';
            table2.style.width = window.innerWidth/2+'px';
            table2.style.height = window.innerHeight+'px';
        };

        //浏览器大小改变时重置大小
        window.onresize = function () {
            myChartContainer();
            chart1.resize();
            chart2.resize();
        };
    });

    function chart_render(chart,data){
        finish = to_array(data['finish_rate']);
        notFinish = to_array(data['nofinish_rate']);
        option = {
            tooltip : {
                trigger: 'axis',
                axisPointer : {            // 坐标轴指示器，坐标轴触发有效
                    type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
                }
            },
            legend: {
                data: ['已完成', '未完成']
            },
            grid: {
                left: '3%',
                right: '4%',
                bottom: '3%',
                containLabel: true
            },
            yAxis:  {
                type: 'value'
            },
            xAxis: {
                type: 'category',
                data: ['一','二','三','四','五','六','七','八','九','十','十一','十二']
            },
            series: [
                {
                    name: '已完成',
                    type: 'bar',
                    stack: '总量',
                    label: {
                        normal: {
                            show: true,
                            position: 'insideRight'
                        }
                    },
                    data:finish
                },
                {
                    name: '未完成',
                    type: 'bar',
                    stack: '总量',
                    label: {
                        normal: {
                            show: true,
                            position: 'insideRight'
                        }
                    },
                    data:notFinish
                },
                {
                    name:'基准线',
                    type:'line',
                    smooth:true,
                    itemStyle: {normal: {areaStyle: {type: 'default'}}},
                    data:[data['average'],data['average'],data['average'],data['average'],data['average'],data['average'],data['average'],data['average'],data['average'],data['average'],data['average'],data['average']],
                },
            ]
        };
        chart.setOption(option,true);
    }

    function chart_render_pie(chart,data){
        rate = to_array(data);
        option = {
            title : {
                text: '分平台统计',
                x:'center'
            },
            tooltip : {
                trigger: 'item',
                formatter: "{a} <br/>{b} : {c} ({d}%)"
            },
            legend: {
                type: 'scroll',
                orient: 'vertical',
                right: 20,
                top: 20,
                bottom: 20,
                data: ["IOS","安卓公版","安卓定制"],
                //selected: {'ios':true,'其他':true}
            },
            series : [
                {
                    name: '平台',
                    type: 'pie',
                    radius : '60%',
                    center: ['50%', '50%'],
                    data: rate,
                    itemStyle: {
                        emphasis: {
                            shadowBlur: 10,
                            shadowOffsetX: 0,
                            shadowColor: 'rgba(0, 0, 0, 0.5)'
                        }
                    }
                }
            ]
        };
        chart.setOption(option,true);
    }

    function to_array(obj){
        var arr=[]
        for (var i in obj){
            arr.push(obj[i]);
        }
        return arr;
    }




    $('#search').bind('click',function(){
        var year = $('#year').val();
        var month = $('#month').val();
        window.location="monthAppReport?year="+year+"&month="+month
    });

    $(".export").click(function(e) {
        var uri = 'data:application/vnd.ms-excel;base64,',text='',
            template = '<html><head><meta charset="UTF-8"></head><body><table>{table}</table></body></html>',
            base64 = function(s) { return window.btoa(unescape(encodeURIComponent(s))) },
            format = function(s, c) {
                return s.replace(/{(\w+)}/g,
                    function(m, p) { return c[p]; })
            }
        //console.log($(this).parent().parent().parent().parent().parent().find("table.layui-table").html())
        $(this).parent().parent().parent().parent().parent().find("table.layui-table").each(function(index, el) {
            if(index<2){
                text+=$(this).html();
            }
        });
        var ctx = {worksheet: 'sheet1', table: text}
        window.location.href = uri + base64(format(template, ctx))
        // this.href= window.URL.createObjectURL(new Blob([text], {type: 'text/plain'}));
        e.stopPropagation();
    });
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
