<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<link rel="stylesheet" type="text/css" href="<?php echo $staticPath; ?>/js/admin/lay/css/layui.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $staticPath; ?>/css/selectBox.css"/>


<style>
    *{ margin: 0; padding: 0;}
    ul,li{ list-style: none; }
    html,body{
        font-family: 'STHeiti Light [STXihei]', Helvetica, 'Hiragino Sans GB', 'Microsoft Yahei', '微软雅黑', Arial, sans-serif;
        font-size: 14px;
        background: #e5e6eb;
    }
    .wrapper{ background: #fff; padding:5px 20px 50px 20px; box-sizing:border-box; }

    .search-wrap{   padding-top: 2px; }
    .tchar-side{ padding: 5px 10px; height: 600px; width: 100%;   }
    span.red{ color:#f00;}
    a.precent,a.precent:hover{color:#009688;}
    .layui-table-cell {padding:0 5px;}
</style>

<body>
<div class="layui-fluid wrapper">
    <div class="layui-row layui-col-space30">
        <!-- 用户观看时常 begin -->
        <div class="layui-col-xs12 layui-col-sm12 layui-col-md6 ">
            <fieldset class="layui-elem-field layui-field-title">
                <legend>用户第几次观看广告人数-时间统计</legend>
            </fieldset>
            <div class="layui-collapse">
                <!--  用户观看时常   begin -->
                <div class="layui-colla-item">
                    <h2 class="layui-colla-title">用户第几次观看广告人数-时间报表</h2>
                    <div class="layui-colla-content layui-show">
                        <!--  用户观看时常 begin -->
                        <div class="search-wrap">
                            <form id='formDemo1' class="layui-form" action="getWatchingTimeData"  data-id="1">
                                <div class="layui-inline">
                                    <input type="text" name="days" class="layui-input" id="datetime1">
                                </div>
                                <div class="layui-inline app_key"></div>
                                <div class="layui-inline ad_type"></div>
                                <button class="layui-btn lay-submit" lay-submit lay-filter="formDemo">立即查询</button>
                            </form>
                        </div>
                        <!--  条件搜索 end -->
                        <div class="tchar-side" id="chart" ></div>
                    </div>
                </div>
                <!-- 用户观看时常   end   -->
                <!-- 用户观看时常   begin -->
                <div class="layui-colla-item">
                    <h2 class="layui-colla-title">用户第几次观看广告人数-时间统计详情 <a data-table="table1"  class="export" style="float:right">导出</a></h2>
                    <div class="layui-colla-content layui-show">
                        <table id="table" lay-filter="test"></table>
                    </div>
                </div>
                <!-- 用户观看时常  end -->
            </div>
        </div>
        <!-- 用户观看时常 end  -->
        <!-- 广告生命周期内价值变化趋势 begin -->
        <div class="layui-col-xs12 layui-col-sm12 layui-col-md6">
            <fieldset class="layui-elem-field layui-field-title">
                <legend>时间段内用户观看人数变化趋势</legend>
            </fieldset>
            <div class="layui-collapse">
                <!-- 用户价值表报 begin -->
                <div class="layui-colla-item">
                    <h2 class="layui-colla-title">时间段内用户观看人数报表</h2>
                    <div class="layui-colla-content layui-show">
                        <!-- 条件搜索 begin -->
                        <div class="search-wrap" style="height: 38px;">
                            <form id='formDemo2'  class="layui-form" action="getWathcingTimeDetailData" data-id="2">

                            </form>
                        </div>
                        <!-- 条件搜索 end -->
                        <!--  折线图  begin -->
                        <div class="tchar-side" id="chart_detail" ></div>
                        <!--  折线图  end  -->
                    </div>
                </div>
                <!-- 用户价值表报 end  -->
                <!-- 用户价值详情 begin -->
                <div class="layui-colla-items">
                    <h2 class="layui-colla-title">时间段内用户观看人数报表详情 <a data-table="table2" class="export" style="float:right">导出</a><a id="toggle_data" style="float:right;margin-right:5px">数值切换</a></h2>
                    <div class="layui-colla-content layui-show">
                        <table id="table_detail" lay-filter="test"></table>
                    </div>
                </div>
                <!-- 用户价值详情 end  -->
            </div>
        </div>
        <!-- 广告生命周期内价值变化趋势 end  -->
    </div>
</div>
</body>
</html>
<script src="<?php echo $staticPath; ?>/js/admin/lay/layui.js"></script>
<script src="<?php echo $staticPath; ?>/js/common/jquery.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/admin/lay/echarts.min.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/common/selectBox.js"></script>
<script>
    
    ;(function(){
        var datail_data,datail_chart;
        
        $(function(){
            $(".export").click(function(e) {
                var uri = 'data:application/vnd.ms-excel;base64,',text='',
                    template = '<html><head><meta charset="UTF-8"></head><body><table border="1">{table}</table></body></html>',
                    base64 = function(s) { return window.btoa(unescape(encodeURIComponent(s))) },
                    format = function(s, c) {
                        return s.replace(/{(\w+)}/g,
                            function(m, p) { return c[p]; })
                    }
                $(this).parent().parent().find("table.layui-table").each(function(index, el) {
                    if(index<2){
                        text+=$(this).html();
                    }
                });
                var ctx = {worksheet: 'sheet1', table: text}
                window.location.href = uri + base64(format(template, ctx))
                // this.href= window.URL.createObjectURL(new Blob([text], {type: 'text/plain'}));
                e.stopPropagation();
            });
            $(".app_key").selectBox({
                name:"app_key",
                title:"选择应用",
                data:<?php echo json_encode($apps); ?>
            });
            $(".ad_type").selectBox({
                name:"ad_type",
                title:"选择广告类型",
                data:<?php echo json_encode($adType); ?>
            });
            
            $("#toggle_data").click(function(e) {
                $(this).toggleClass("precent");
                chart_render_detail(datail_chart,datail_data);
            });
        });

        function to_array(obj){
            var arr=[]
            for (var i in obj){
                arr.push(obj[i]);
            }
            return arr;
        };


        function table_format(data){
            var rdata=[]
            var rdays=[]
            var items={}
            for (var i = 0; i <= data['length']; i++) {
                rdays.push(i)
            };
            for (var key in data['data']) {
                if(!items.hasOwnProperty(key)){
                    items[key]={}
                }
                if(data.hasOwnProperty('dims') && data['dims'].length){
                    for (var dim in data['dims']) {
                        items[key][data['dims'][dim]]=data['data'][key][data['dims'][dim]]
                    }
                }else{
                    // items[key].push('总体LTV')
                }
                for (var rday in rdays) {
                    items[key]['per_time'+rday]=0;
                }
                for (var rday in data['data'][key]['per_time']) {
                    items[key]['per_time'+rday]=parseFloat(data['data'][key]['per_time'][rday])
                }
                rdata.push(items[key]);
            }
            return rdata;
        }


        function table_format_detail(data){
            var items={};
            for (var key in data.data) {
                items['min'+key]=data.data[key]+"(<span class='red'>"+(data.data[key]*100/data.sum).toFixed(1)+"%</span>)"
            }
            return [items];
        }

        function chart_render(chart,data){
            var legend=[]
            var xdata=[]
            var series=[]
            var rdays=[]
            var items={}


            for (var key in data.cols) {
                rdays.push(data.cols[key].title)
            }

            for (var key in data['data']) {
                if(!items.hasOwnProperty(key)){
                    items[key]={}
                }

                for (var rday in rdays) {
                    items[key][rday]=0;
                }
            }

            var maxSize=5
            for (var key in data['data']) {
                for (var rday in data['data'][key]['per_time']) {
                    items[key][rday]=parseFloat(data['data'][key]['per_time'][rday])
                }
                var mySize=data['data'][key]['legend'].length
                if(mySize>maxSize){
                    maxSize=mySize;
                }
                legend.push(data['data'][key]['legend'])
                series.push({
                    name: data['data'][key]['legend'],
                    type:'line',
                    data:to_array(items[key])
                })
            }


            var option = {
                title: {
                text: data['title']
            },
            tooltip: { trigger: 'axis' },
            legend: { data:legend, type: 'scroll',orient: 'vertical',right: -5,
                top: 50,
                bottom: '3%',
                textStyle:{
                fontSize:10
            }
            },
            grid: {
                    left: '3%',
                    right: maxSize*10+30,
                    bottom: '3%',
                    containLabel: true
            },
            toolbox: {
                feature: {
                    saveAsImage: {}
                }
            },
            xAxis: {
                name :'次数',
                type: 'category',
                boundaryGap: false,
                data: to_array(rdays)
            },
            yAxis: {
                name :'平均观看时间',
                type: 'value',

            },
            series:series
        };
            chart.setOption(option,true);
            chart.on('click', function (params) {
              if (params.componentType === 'series') {
                  var inputContent = {
                      times:params.dataIndex,
                      days:data.searchMap[params.seriesIndex].sdate+' - '+data.searchMap[params.seriesIndex].edate,
                      detail:data.searchMap[params.seriesIndex].info
                  };
                  chart_detail=echarts.init(document.getElementById('chart_detail'));
                  layui.use(['element','laydate','table'],  function(){
                      var table = layui.table;
                      $.ajax({
                          type: 'GET',
                          data: inputContent,
                          url: 'getWathcingTimeDetailData',
                          dataType: 'json',
                          success: function(data){
                              if(data.success){
                                  chart_render_detail(chart_detail,data.data);
                                  table.render({
                                      elem: "#table_detail",
                                      data: table_format_detail(data.data),
                                      cols: [data.data['cols']],
                                      page: false,
                                  });
                              }
                              chart.hideLoading();
                          },
                          error: function(xhr){
                              layer.msg("fail");
                          }
                        });
                 });
               }
            });
        }



        //详情表
        function chart_render_detail(chart,data){
            //xAxis 分钟数
            var rtime=[];
             //yAxis 人数
            var x_data = [];
            var precent =$("#toggle_data").hasClass("precent");
            datail_data=data;   
            datail_chart=  chart;       
            for (var key in data.data) {
                rtime.push(key)
                if(precent){
                    yAxis_name='人数%';
                    x_data.push((data.data[key]*100/data.sum).toFixed(1))
                }else{
                    yAxis_name='人数';
                    x_data.push(data.data[key])
                }                
            }
            lengend=yAxis_name

            var option = {
                title: {
                    text: data['title']
                },
                color: ['#3398DB'],
                tooltip : {
                    trigger: 'axis',
                    axisPointer : {            // 坐标轴指示器，坐标轴触发有效
                        type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
                    }
                },
                grid: {
                    left: '2%',
                    right: '8%',
                    bottom: '8%',
                    containLabel: true
                },
                xAxis : [
                    {
                        name :'分钟',
                        type : 'category',
                        data : to_array(rtime),//需要替换
                        axisTick: {
                            alignWithLabel: true
                        }
                    }
                ],
                yAxis : [
                    {
                        name :yAxis_name,
                        type : 'value'
                    }
                ],
                series : [
                    {
                        name:lengend,
                        type:'bar',
                        barWidth: '60%',
                        data:x_data //需要替换
                    }
                ]
            };
            chart.setOption(option,true);
        }

        layui.use(['element','laydate','form','table'],  function(){
            var element = layui.element;
            var laydate = layui.laydate;
            var form = layui.form;
            var table = layui.table;
            var chart = null;
            laydate.render({elem: '#datetime1',range: true,value: '<?php echo $sdate." - ".$edate ?>'});
            laydate.render({elem: '#datetime2',range: true,value: '<?php echo $sdate." - ".$edate ?>'});

            form.on('submit(formDemo)',function(data){
                if(!chart || chart == null){
                    chart=echarts.init(document.getElementById('chart'))
                }else{
                    chart.dispose();
                    chart=echarts.init(document.getElementById('chart'))
                }
                chart.showLoading();
                layui.$.ajax({
                    type: 'GET',
                    data: data.field,
                    url: data.form.action,
                    dataType: 'json',
                    success: function(data){
                        if(data.success){
                            chart_render(chart,data.data);
                            table.render({
                                elem: "#table",
                                data: table_format(data.data),
                                cols: [data.data['cols']],
                                page: false,
                            });
                        }
                        chart.hideLoading();
                    },
                    error: function(xhr){
                        layer.msg("fail");
                    }
                });
                return false;
            });
            layui.$('.lay-submit').click();
        });
    })();

</script>



