<?php echo $this->render("layout/header.phtml"); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<link rel="stylesheet" type="text/css" href="<?php echo $staticPath?>/css/layui.css"/>
<link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<style>
    *{ margin: 0; padding: 0;}
    ul,li{ list-style: none; }
    html,body{
        font-family: 'STHeiti Light [STXihei]', Helvetica, 'Hiragino Sans GB', 'Microsoft Yahei', '微软雅黑', Arial, sans-serif;
        font-size: 14px;
    }
    .wrapper{
        background:#f2f2f2; padding:5px 20px 50px 20px; box-sizing:border-box;
    }
    .items-main-title{ width: 100%; overflow:hidden; padding: 10px 0 5px 0; box-sizing: border-box; border-bottom:1px solid #eee;  }
    .items-main-title p{ float:left; padding-left: 5px; color: #1E9FFF; display: inline-block; font-size: 20px; line-height: 40px;  }
    .items-main-search{ width: 100%;  padding: 10px 0 0 0; }
    .items-main-buttons{ float:right; display: inline-block; }
    .table-wrap{ width: 100%;}
    .grid-demo{
        padding: 20px;
        line-height: 50px;
        text-align: center;
        background-color: #fff;
        color:#1a2a32;margin-left: 8px;}
</style>
<body>
<div class="layui-tab">
    <ul class="layui-tab-title">
        <li ><a href="runDetailReport">经营概况</a></li>
        <li ><a href="monthAppReport">月运营明细</a></li>
        <li class="layui-this"><a href="weekAppReport">周运营明细</a></li>
    </ul>
    <div class="layui-tab-content">
        <div class="layui-tab-item layui-show">
            <div class="layui-fluid">
                <div class="items-main-title"><p>周运营明细(<?php echo date('Y-m-d',strtotime($lastWeekFirstDay)); ?>~<?php echo date('Y-m-d',strtotime($lastWeekEndDay)-86400);?> || <?php echo date('Y-m-d',strtotime($lastLastWeekFirstDay));?>~<?php echo date('Y-m-d',strtotime($lastWeekFirstDay)-86400);;?>)</p></div>
                <!-- top end  -->
                <div class="items-main-search ">
                    <form class="layui-form" action="" method="get">
                        <div class="layui-form-item">
                            <label class="layui-form-label">查询日期：</label>
                            <div class="layui-input-inline">
                                <input type="text" name="date" class="layui-input" id="test5" value="<?php echo $now;?>" placeholder="yyyy-MM-dd">
                            </div>
                            <button class="layui-btn" lay-submit="" lay-filter="demo1">立即提交</button>
                        </div>
                        <div class="layui-form-item">
                        </div>
                    </form>
                </div>
                <div class="layui-row">
                    <div class="layui-col">
                        <fieldset class="layui-elem-field layui-field-title" style="margin-top: 30px;">
                            <legend>一.周运营总概况</legend>
                        </fieldset>
                        <div class="layui-col-md2">
                            <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-user-circle-o fa-3x"></i></div>广告用户:<?php echo $sumData['lastWeek']['all']['dau'];?><br>同比:<?php echo $sumData['rate']['all']['dau'];?>%</div>
                        </div>
                        <div class="layui-col-md2">

                            <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-mobile fa-3x"></i></div>展示:<?php echo $sumData['lastWeek']['all']['impressions'];?><br>同比:<?php echo $sumData['rate']['all']['impressions'];?>%</div>
                        </div>
                        <div class="layui-col-md2">
                            <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-line-chart fa-3x"></i></div>eCPM:<?php echo $sumData['lastWeek']['all']['ecpm'];?><br>同比:<?php echo $sumData['rate']['all']['ecpm'];?>%</div>
                        </div>
                        <div class="layui-col-md2">
                            <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-users fa-3x"></i></div>人均观看:<?php echo $sumData['lastWeek']['all']['perpeople'];?><br>同比:<?php echo $sumData['rate']['all']['perpeople'];?>%</div>
                        </div>
                        <div class="layui-col-md2">
                            <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-area-chart fa-3x"></i></div>ARPU:<?php echo $sumData['lastWeek']['all']['arpu'];?><br>同比:<?php echo $sumData['rate']['all']['arpu'];?>%</div>
                        </div>
                        <div class="layui-col-md2">
                            <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-money fa-3x"></i></div>总收入:<?php echo $sumData['lastWeek']['all']['ad_income'];?><br>同比:<?php echo $sumData['rate']['all']['ad_income'];?>%</div>
                        </div>
                    </div>
                </div>
                <fieldset class="layui-elem-field layui-field-title" style="margin-top: 30px;">
                    <legend>二.各平台运营情况 <span style="margin-left: 1200px;"></span></legend>
                </fieldset>
                <!-- top end  -->
                <!-- table begin -->
                <div class="layui-collapse" lay-filter="test">
                    <div class="layui-colla-item">
                        <h1 class="layui-colla-title">IOS</h1>
                        <div class="layui-colla-content layui-show">
                            <div class="items-main-buttons">
                                <a class="layui-btn layui-btn-normal export">导出为excel</a>
                            </div>
                            <div class="layui-col">
                                <fieldset class="layui-elem-field layui-field-title" style="margin-top: 30px;">
                                    <legend>一.运营概况</legend>
                                </fieldset>
                                <div class="layui-col-md2">
                                    <i></i>
                                    <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-user-circle-o fa-3x"></i></div>广告用户:<?php echo $sumData['lastWeek'][2]['dau'];?><br>同比:<?php echo $sumData['rate'][2]['dau'];?>%</div>
                                </div>
                                <div class="layui-col-md2">
                                    <i></i>
                                    <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-mobile fa-3x"></i></div>展示:<?php echo $sumData['lastWeek'][2]['impressions'];?><br>同比:<?php echo $sumData['rate'][2]['impressions'];?>%</div>
                                </div>
                                <div class="layui-col-md2">
                                    <i></i>
                                    <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-line-chart fa-3x"></i></div>eCPM:<?php echo $sumData['lastWeek'][2]['ecpm'];?><br>同比:<?php echo $sumData['rate'][2]['ecpm'];?>%</div>
                                </div>
                                <div class="layui-col-md2">
                                    <i></i>
                                    <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-users fa-3x"></i></div>人均观看:<?php echo $sumData['lastWeek'][2]['perpeople'];?><br>同比:<?php echo $sumData['rate'][2]['perpeople'];?>%</div>
                                </div>
                                <div class="layui-col-md2">
                                    <i></i>
                                    <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-area-chart fa-3x"></i></div>ARPU:<?php echo $sumData['lastWeek'][2]['arpu'];?><br>同比:<?php echo $sumData['rate'][2]['arpu'];?>%</div>
                                </div>
                                <div class="layui-col-md2">
                                    <i></i>
                                    <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-money fa-3x"></i></div>总收入:<?php echo $sumData['lastWeek'][2]['ad_income'];?><br>同比:<?php echo $sumData['rate'][2]['ad_income'];?>%</div>
                                </div>
                            </div>
                            <hr>
                            <fieldset class="layui-elem-field layui-field-title" style="margin-top: 30px;">
                                <legend>二.IOS应用详情</legend>
                            </fieldset>
                            <table class="layui-table">
                                <thead>
                                <tr>
                                    <th>应用</th>
                                    <th>广告用户</th>
                                    <th>变化占比</th>
                                    <th>展示次数</th>
                                    <th>变化占比</th>
                                    <th>人均展示</th>
                                    <th>变化占比</th>
                                    <th>eCPM</th>
                                    <th>变化占比</th>
                                    <th>ARPU</th>
                                    <th>变化占比</th>
                                    <th>收益</th>
                                    <th>变化占比</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                foreach ($sumData['lastWeek'][2]['detail'] as $isCustom =>$items) {
                                    ?>
                                        <?php foreach($items as $appKey=>$val){
                                            if($val['is_custom'] == 1) {
                                                echo "<tr style='background-color: #66F4DF'>";
                                            }else{
                                                echo "<tr>";
                                            }
                                            ?>
                                            <td><?php echo $val['app_name'];?></td>
                                            <td><?php echo isset($val['dau'])?$val['dau']:0;?></td>
                                            <td><?php echo $val['dau_rate'];?>%</td>
                                            <td><?php echo isset($val['impressions'])?$val['impressions']:0;?></td>
                                            <td><?php echo $val['impressions_rate'];?>%</td>
                                            <td><?php echo $val['perpeople'];?></td>
                                            <td><?php echo $val['perpeople_rate'];?>%</td>
                                            <td><?php echo $val['ecpm'];?></td>
                                            <td><?php echo $val['ecpm_rate'];?>%</td>
                                            <td><?php echo $val['arpu'];?></td>
                                            <td><?php echo $val['arpu_rate'];?>%</td>
                                            <td><?php echo isset($val['ad_income'])?$val['ad_income']:0;?></td>
                                            <td><?php echo $val['income_rate'];?>%</td>
                                            </tr>
                                        <?php } ?>
                                    </tr>
                                <?php }?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>


                <div class="layui-collapse" lay-filter="test">
                    <div class="layui-colla-item">
                        <h1 class="layui-colla-title">安卓</h1>
                        <div class="layui-colla-content layui-show">
                            <div class="items-main-buttons">
                                <a class="layui-btn layui-btn-normal export">导出为excel</a>
                            </div>
                            <div class="layui-col">
                                <fieldset class="layui-elem-field layui-field-title" style="margin-top: 30px;">
                                    <legend>一.运营概况</legend>
                                </fieldset>
                                <div class="layui-col-md2">
                                    <i></i>
                                    <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-user-circle-o fa-3x"></i></div>广告用户:<?php echo $sumData['lastWeek'][1]['dau'];?><br>同比:<?php echo $sumData['rate'][1]['dau'];?>%</div>
                                </div>
                                <div class="layui-col-md2">
                                    <i></i>
                                    <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-mobile fa-3x"></i></div>展示:<?php echo $sumData['lastWeek'][1]['impressions'];?><br>同比:<?php echo $sumData['rate'][1]['impressions'];?>%</div>
                                </div>
                                <div class="layui-col-md2">
                                    <i></i>
                                    <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-line-chart fa-3x"></i></div>eCPM:<?php echo $sumData['lastWeek'][1]['ecpm'];?><br>同比:<?php echo $sumData['rate'][1]['ecpm'];?>%</div>
                                </div>
                                <div class="layui-col-md2">
                                    <i></i>
                                    <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-users fa-3x"></i></div>人均观看:<?php echo $sumData['lastWeek'][1]['perpeople'];?><br>同比:<?php echo $sumData['rate'][1]['perpeople'];?>%</div>
                                </div>
                                <div class="layui-col-md2">
                                    <i></i>
                                    <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-area-chart fa-3x"></i></div>ARPU:<?php echo $sumData['lastWeek'][1]['arpu'];?><br>同比:<?php echo $sumData['rate'][1]['arpu'];?>%</div>
                                </div>
                                <div class="layui-col-md2">
                                    <i></i>
                                    <div class="grid-demo grid-demo-bg1"><div><i class="fa fa-money fa-3x"></i></div>总收入:<?php echo $sumData['lastWeek'][1]['ad_income'];?><br>同比:<?php echo $sumData['rate'][1]['ad_income'];?>%</div>
                                </div>
                            </div>
                            <hr>
                            <fieldset class="layui-elem-field layui-field-title" style="margin-top: 30px;">
                                <legend>二.安卓应用详情</legend>
                            </fieldset>
                            <table class="layui-table">
                                <thead>
                                <tr>
                                    <th>应用</th>
                                    <th>广告用户</th>
                                    <th>变化占比</th>
                                    <th>展示次数</th>
                                    <th>变化占比</th>
                                    <th>人均展示</th>
                                    <th>变化占比</th>
                                    <th>eCPM</th>
                                    <th>变化占比</th>
                                    <th>ARPU</th>
                                    <th>变化占比</th>
                                    <th>收益</th>
                                    <th>变化占比</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                foreach ($sumData['lastWeek'][1]['detail'] as $isCustom =>$items) {
                                    ?>
                                    <?php foreach($items as $appKey=>$val){
                                        if($val['is_custom'] == 1) {
                                            echo "<tr style='background-color: #66F4DF'>";
                                        }else{
                                            echo "<tr>";
                                        }
                                        ?>
                                        <td><?php echo $val['app_name'];?></td>
                                        <td><?php echo isset($val['dau'])?$val['dau']:0;?></td>
                                        <td><?php echo $val['dau_rate'];?>%</td>
                                        <td><?php echo isset($val['impressions'])?$val['impressions']:0;?></td>
                                        <td><?php echo $val['impressions_rate'];?>%</td>
                                        <td><?php echo $val['perpeople'];?></td>
                                        <td><?php echo $val['perpeople_rate'];?>%</td>
                                        <td><?php echo $val['ecpm'];?></td>
                                        <td><?php echo $val['ecpm_rate'];?>%</td>
                                        <td><?php echo $val['arpu'];?></td>
                                        <td><?php echo $val['arpu_rate'];?>%</td>
                                        <td><?php echo isset($val['ad_income'])?$val['ad_income']:0;?></td>
                                        <td><?php echo $val['income_rate'];?>%</td>
                                        </tr>
                                    <?php } ?>
                                    </tr>
                                <?php }?>
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
                <!-- table end   -->
            </div>
        </div>

    </div>
</div>
</body>
</html>
<script src="<?php echo $staticPath; ?>/js/admin/lay/layui.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/admin/lay/echarts.min.js"></script>
<script>
    //注意：导航 依赖 element 模块，否则无法进行功能性操作
    layui.use(['table','form','element', 'layer','laydate'], function(){
        var element = layui.element;
        var laydate = layui.laydate;
        //日期时间选择器
        laydate.render({
            elem: '#test5'
            ,type: 'date'
        });
        //监听折叠
        element.on('collapse(test)', function(data){

        });
    });


    $(".export").click(function(e) {
        var uri = 'data:application/vnd.ms-excel;base64,',text='',
            template = '<html><head><meta charset="UTF-8"></head><body><table>{table}</table></body></html>',
            base64 = function(s) { return window.btoa(unescape(encodeURIComponent(s))) },
            format = function(s, c) {
                return s.replace(/{(\w+)}/g,
                    function(m, p) { return c[p]; })
            }
        //console.log($(this).parent().parent().parent().parent().parent().find("table.layui-table").html())
        $(this).parent().parent().parent().parent().parent().find("table.layui-table").each(function(index, el) {
            if(index<2){
                text+=$(this).html();
            }
        });
        var ctx = {worksheet: 'sheet1', table: text}
        window.location.href = uri + base64(format(template, ctx))
        // this.href= window.URL.createObjectURL(new Blob([text], {type: 'text/plain'}));
        e.stopPropagation();
    });
</script>
<?php echo $this->render("layout/footer.phtml"); ?>
