<?php echo $this->render("./spm/layout/header.phtml");?>
<link href="<?php echo $staticPath?>/css/spm/groupDropdown2.css?v=<?php echo $version;?>" rel="stylesheet" />
<link href="<?php echo $staticPath?>/css/spm/material.css?v=<?php echo $version;?>" rel="stylesheet" />
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <!-- 头部区域 begin  -->
    <?php echo $this->render("./spm/layout/topMenu.phtml");?>
    <!-- 头部区域 end   -->

        <div class="content-wrap">
        <!-- leftMenu begin   -->
        <?php echo $this->render("./spm/layout/leftMenu.phtml");?>
        <!-- leftMenu begin   -->
        <div class="content-main">
            <div class="wrapper">
                <!-- title begin -->
                <div class="title">
                    <p>素材上传</p>
                </div>
                <!-- 查询条件 begin -->
<!--                <form class="layui-form" action="">-->
                <div class="query-condition">
                        <div class="layui-form-item layui-form">
                            <label class="layui-form-label">素材类型</label>
                            <div class="layui-input-block" style="width:200px;">
                                <select id="uploadType" lay-filter="uploadType" name="type" lay-verify="required">
                                    <?php foreach ($materialType as $key=>$val){?>
                                        <option value="<?php echo $key;?>"><?php echo $val;?></option>
                                    <?php }?>
                                </select>
                            </div>
                        </div>
                        <div class="upload-list-item layui-form">
                            <label class="layui-form-label">素材组：</label>
                            <div class="layui-input-inline" style="width:200px;">
                                <select lay-verify="" lay-search name="gid" id="gid">
                                    <?php foreach ($materialGroups as $key=>$val){?>
                                        <option value="<?php echo $key;?>" ><?php echo $val;?></option>
                                    <?php }?>
                                </select>
                            </div>
                            <button type="button" class="layui-btn addmaterialGroup">
                                <i class="layui-icon">&#xe654;</i>
                            </button>               
                        </div>
                </div>
                <!-- 查询条件 end  -->
                <!-- 素材列表 begin-->
                    <div class="material-wrap uploadFile-wrap">
                        <ul id="uploadFile-list" class="upload-list">
                        </ul>
                        <ul id="upload-list" class="upload-list">
                            <li>
                                <button type="button" onclick="addUpload()" style="position: absolute;left: 50%;top: 50%;margin: -25% 0 0 -20%;" class="layui-btn layui-btn-normal">
                                <i class="layui-icon">&#xe608;</i> 添加
                                </button>
                            </li>

                        </ul>
                        <div class="clearBoth"></div>
                    </div>
                    <!-- 素材列表 end-->
                    <div class="layui-form-item">
                        <div class="layui-input-block">
                        <button type="button"  class="layui-btn" id="submit">立即提交</button>
                        <a type="button" class="layui-btn layui-btn-primary" href="javascript:history.go(-1)">取消</a>
                        </div>
                    </div>
<!--                </form>-->
            </div>
        </div>
        </div>

    </div>

</body>

</html>
<script src="<?php echo $staticPath?>/js/common/groupDropdown2.js"></script>
<script>
    var addGroupUrl = baseurl + '/Admin/Spm_Material/addGroup';// 列表
    var labelData = <?php echo $labelData; ?>//json1.data;
    //JavaScript代码区域
    layui.use(['element', 'form', 'laydate', 'table', 'upload'], function () {
        var element = layui.element;
        var form = layui.form;
        var laydate = layui.laydate;
        var table = layui.table;
        var upload = layui.upload;
        // 初始化 日期 date 插件
        laydate.render({
            elem: '#date', //指定元素
            value: '',
            range: true,
            done: function (value, date, endDate) {
                var begin = '',
                    end = '';
                if (value) {
                    begin = date.year + "-" + date.month + '-' + date.date;
                    end = endDate.year + "-" + endDate.month + '-' + endDate.date;
                }
                $("input[name='sdate']").val(begin);
                $("input[name='edate']").val(end);
            }
        });
        //监听提交
       $('#submit').click(function(data){
            var len = $("#uploadFile-list").children('li').length;
            var data = {
                field : {}
            }
            data.field.type = $("#uploadType").val();
            data.field.token = '<?php echo $token;?>';
            data.field.count = len;
            data.field.file_name = {};
            var flag = true;
            $("input[name='file_name[]']").each(function(i,el){
                data.field.file_name[i] =$(this).val();
            });
            data.field.img_width = {};
            $("input[name='img_width[]']").each(function(i,el){
                data.field.img_width[i] =$(this).val();
            });
            data.field.img_height = {};
            $("input[name='img_height[]']").each(function(i,el){
                data.field.img_height[i] =$(this).val();
            });
            data.field.file_size = {};
            $("input[name='file_size[]']").each(function(i,el){
                data.field.file_size[i] =$(this).val();
            });
            data.field.other_file = {};
            $("input[name='other_file[]']").each(function(i,el){
                data.field.other_file[i] =$(this).val();
            });
            data.field.content = {};
            $("input[name='content[]']").each(function(i,el){
                data.field.content[i] =$(this).val();
            });
            data.field.mk_operator = {};
            $("select[name='mk_operator[]']").each(function(i,el){
                data.field.mk_operator[i] =$(this).val();
            });
           data.field.signature = {};
           $("input[name='signature[]']").each(function(i,el){
               data.field.signature[i] =$(this).val();
           });
            data.field.label = {};
            $("input[name='label[]']").each(function(i,el){
                if($(this).val() == ''){
                    layer.msg('标签不能为空!');
                    flag = false;
                }
                data.field.label[i] =$(this).val();
            });
            data.field.duration = {};
            $("input[name='duration[]']").each(function(i,el){
                data.field.duration[i] =$(this).val();
            });
            data.field.picture = {};
            $("input[name='picture[]']").each(function(i,el){
                data.field.picture[i] =$(this).val();
            });
            data.field.name = {};
            $("input[name='name[]']").each(function(i,el){
                if(data.field.type != 3){
                if($(this).val() == ''){
                    layer.msg('标题不能为空!');
                    flag = false;
                    }
                }
                data.field.name[i] =$(this).val();
            });
           if($("#gid").val() == ''){
               layer.msg('请选择素材组!');
               flag = false;
           }
           if(!flag){ return false;}
            data.field.gid = $("#gid").val();


//          console.log(data.field);
//          return false;
            //data.field.app_id = $("select[name='app_id']").find("option:selected").val();
            $.ajax({
                url : 'saveData',
                async: false,
                data : data.field,
                type : 'post',
                dataType : 'json',
                jsonp : 'callback',
                success:function(data){
                    layer.msg(data.msg);
                    if(data.success){
                        setTimeout(function(){
                            window.location.href = 'index';
                        },500);
                    }
                },
                error:function(xhr,msg,e){
                    layer.msg(msg);
                }
            });
            return false;
        });


        var selectDefault = 1 ; // 默认图片类型
        $("#uploadType").find("option[value='"+selectDefault+"']").prop("selected",true);
        // 上传类型切换
        form.on('select(uploadType)', function(data){
            if($("#uploadFile-list li").length==0 || data.value==selectDefault){
                selectDefault = data.value;
                return false;
            }
            layer.open({
                type: 1
                ,offset: 'auto'
                ,id: 'reminder' //防止重复弹出
                ,content: '<div style="padding: 20px 100px;">更改素材类型，将不会保存当前编辑内容！</div>'
                ,btn: ['不管，我就要', '亚麻跌']
                ,btnAlign: 'r' //按钮居中
                ,shade: 0.5 //不显示遮罩
                ,yes: function(){
                    selectDefault = data.value
                    $("#uploadFile-list").html(' ')
                    layer.closeAll();
                }
                ,btn2:function(){
                    $("#uploadType").find("option[value='"+selectDefault+"']").prop("selected",true);
                    renderLayuiForm();
                }
                ,cancel: function(){
                    $("#uploadType").find("option[value='"+selectDefault+"']").prop("selected",true);
                    renderLayuiForm();
                }
            });
        });
    });

    // 添加上传文件
    function addUpload(obj){
        var selected = parseInt($("#uploadType").val());
        var isText = 'display:none',isFiles='display:block';
        var li = ``,text='图片',desc=' 100k以内的png／jpg／gif';
        var completeText='',imgSrc='',imgIsshow = 'display:none',size = '',img_width = '', img_height='',data = '',signature='';
        var fileName = '',file;
        if(obj){
            file = obj.file;
            completeText = '上传 100%';
            imgSrc = obj.url;
            data = obj.data;
            imgIsshow = 'display:block';
            img_width = obj.img_width;
            img_height = obj.img_height;
            size = obj.size;
            fileName = file.name;
            signature = obj.signature;
        }
        if(selected==1){
            text='图片',desc='2M以内的png／jpg／gif';
        }else if(selected==2){
            text='视频',desc='100M以内的MP4';
        }else{
            text='文案';
            isText = 'display:block';
            isFiles='display:none';
        }
        var oLi = document.createElement('li');
        li = `<div class="layui-form upload-form">
                        <p class="upload-list-title">`+text+`</p>
                        <input type='hidden' name='duration[]' value=''/>
                        <input type="hidden" name="picture[]" value=""/>
                        <input class="file_name" type="hidden" name="file_name[]" value="`+data+`"/>
                        <input class="img_width" type="hidden" name="img_width[]" value="`+ img_width+`"/>
                        <input class="img_height" type="hidden" name="img_height[]" value="`+img_height +`"/>
                        <input class="file_size" type="hidden" name="file_size[]" value="`+size +`"/>
                        <input class="signature" type="hidden" name="signature[]" value="`+signature+`"/>
                        <input class="other_file" type="hidden" name="other_file[]" />
                        <i class="upload-list-del">x</i>
                            <div class="upload-list-files" style="`+isFiles+`">
                                <img style="`+imgIsshow+`" onclick="onfileSelected(this,`+selected+`)" class="files-img" src="`+imgSrc+`" />
                                <!-- <p class="files-mask"></p> -->
                                <div class="files-btns">
                                    <span class="files-desc">
                                    `+desc+`
                                    </span>
                                    <div class="files-btns-item">
                                        <input class="fileupload-input" onchange="fileSelected(this,`+selected+`)" type="file" multiple />
                                        <p class="fileupload-btn">上传</p>
                                    </div>
                                </div>
                            </div>
                            <div class="upload-list-item layui-form">
                                <!-- <p class="up-list-item-title">状态：</p> -->
                                <p class="uploadInfo up-list-item-text red center">` +completeText+` </p>
                            </div>
                            <div class="upload-list-item layui-form" style="`+isText+`">
                                <p class="up-list-item-title">推广文案：</p>
                                <p class="up-list-item-input">
                                    <input type="text" name="content[]" placeholder="" value="" class="layui-input" />
                                </p>
                            </div>
                            <div class="upload-list-item layui-form" style="`+isFiles+`">
                                <p class="up-list-item-title">标题：</p>
                                <p class="up-list-item-input">
                                     <input type="text" name="name[]" value="`+fileName+`" class="layui-input"/>
                                </p>
                            </div>
                        </div>
                            <div class="upload-list-item ">
                                <p class="up-list-item-title">素材标签：<a class="layui-btn layui-btn-xs applyAll" style="float:right;">应用到全部</a></p>
                                <p class="up-list-item-input">
                                <div class="dropdown-mul-1">
                                 <div class="test"></div>
                                </div>
                                </p>
                            </div>
                            <div class="upload-list-item layui-form">
                                <p class="up-list-item-title">创意：<a class="layui-btn layui-btn-xs creativeAll" style="float:right;">应用到全部</a></p>
                                <div class="up-list-item-input">
                                    <select lay-verify="" lay-search name="mk_operator[]" id="mk_operator">
                                        <?php foreach ($userList as $key=>$val){?>
                                        <option value="<?php echo $val['user_id'];?>" <?php if($userInfo['user_id'] == $val['user_id']) echo 'selected';?>><?php echo $val['user_name'];?></option>
                                        <?php }?>
                                    </select>
                                </div>
                            </div>
                            <div class="upload-list-item">
                                <p class="up-list-item-title">源文件：</p>
                                <div class="up-list-item-input">
                                    <p class="fileupload-btn">上传源文件</p>
                                    <input class="fileupload-input" type="file" onchange="fileSelected(this,'other')" />
                                </div>
                                <p class="up-list-item-text"></p>
                            </div>
                        `;
        $(oLi).html(li);
        $("#uploadFile-list").append(oLi);
        // 批量
        if(obj && selected==2){
            creatVideo(data,$(oLi))
        }else if(obj && selected==1){
            picFileReader(file,$(oLi))
        }

        //console.log(labelData)
        $(oLi).find(".test").groupDropdown({
            //data: data, // 所有数据
            name: 'label[]',
            // 标签数据请求
            requestData: {
                data: {token:token}, // 请求参数
                url: 'getLabels', // 请求url
            },
            isUpdata: true, // 是否每次打开，请求标签数据
            selected: [], // 选中值
            selectedShow: false, // 是否显示侧边栏
            // 添加 二级标签
            addLabelOpts: {
                data: {token:token}, // 请求参数
                url: 'addLevel2Label',
            },
            addLabelCallback: function (data) {
                //console.log(data);
              //  $("select[name='label[]']").val(data.toString())
            },
            //
            // 选中值 回调函数
            onSelect(arr) {
                // console.log("arr:", arr)
                // console.log(this)
            }
        });
        renderLayuiForm();
    }

    // 删除列表记录
    $("#uploadFile-list").delegate('.upload-list-del','click',function(e){
        $(this).parent().parent().remove();
        e = e || window.event;
        e.stopPropagation();
    });

    //添加二级标签
    $("#uploadFile-list").delegate('.addLabel','click',function(){
       console.log('clickicciciicicicicici')
    });


    //应用输入标签到全部
    $('#uploadFile-list').delegate(".applyAll",'click',function(){
        var oUl = $('#uploadFile-list');
        $(this).parents().map(function(){
            if((this.tagName).toLowerCase() == 'li'){
                var seft = $(this);
                var values = seft.find('.dropdown-mul-1 .ids').val();
                var names = seft.find('.dropdown-mul-1 .jq-gsb-a').attr("title");
                $('.dropdown-mul-1').each(function(){
                     var dropdown = $(this);
                     dropdown.find(".ids").val(values);
                     dropdown.find(".jq-gsb-a").attr("title",names);
                     dropdown.find(".jq-gsb-a").html(names);
                });
                
                return false;
            }
        });
    });


    //创意应用到标签全部
    $('#uploadFile-list').delegate(".creativeAll",'click',function(){
        var oUl = $('#uploadFile-list')
        var selectId = $(this).parents().find("select[name='mk_operator[]']").val();
        var text  =$(this).parents().find('.layui-select-title input').val();
        oUl.find('.layui-anim').children().each(function(e,obj){
           if($(obj).hasClass('layui-this')) $(obj).removeClass('layui-this')
           if(parseInt($(obj).attr('lay-value')) == selectId){
               $(obj).addClass('layui-this')
           }
        })
        oUl.find("select[name='mk_operator[]']").val(selectId);
        oUl.find('.layui-select-title input').val('');
        oUl.find('.layui-select-title input').val(text)
        return false;
    });

    // 图片预览和文件读取状态 
    function fileSelected(t,type) {
        if(t.files.length>1 && t.files.length>0){
            // 批量
            batchListTips(t.files,type);
            $(t).parents().map(function () {
               // console.log(this.tagName.toLowerCase())
                if('li'==(this.tagName).toLowerCase()){
                    this.remove();
                }
            })
        }else if(t.files.length==1){
            //单个
            var file = t.files[0];
            var allowUp = false;
            if (type == 1){
                if(file.type == 'image/jpeg' || file.type == 'image/png' || file.type == 'image/gif'){
                    allowUp = true;
                }
            }else if(type ==2){
                if(file.type == 'video/mp4'){
                    allowUp = true;
                }
            }else{
                allowUp = true;
            }
            if(allowUp == false){
                layer.msg('上传类别错误!');
                return false;
            }
            var that;
            if(type=='other'){
                that =  $(t).parent().parent().parent().find('.uploadInfo');
            }else{
                that =  $(t).parent().parent().parent().parent().find('.uploadInfo');
            }
            readFile(that,file,type)
        }
    }

    // 读取文件状态
    function readFile(t,file,type){
        if (file) {
            var fileSize = 0;
            if (file.size > 1024 * 1024)
                fileSize = (Math.round(file.size * 100 / (1024 * 1024)) / 100).toString() + 'MB';
            else
                fileSize = (Math.round(file.size * 100 / 1024) / 100).toString() + 'KB';
            t.html(file.name +' ' + fileSize )
            uploadFile(file,t,type);
        }
    }

    //  上传文件
     function uploadFile(file,info,type,complete) {
        var fd = new FormData();
        fd.append("fileToUpload", file);
        fd.append("token",token);
        fd.append("groupId",$('#gid').val());
        var xhr = new XMLHttpRequest();
        xhr.upload.addEventListener("progress", function(evt){
            if (evt.lengthComputable) {
                info.html("上传 "+ Math.round(evt.loaded * 100 / evt.total) +"%" );
            }else{
                info.html("上传成功");
                if(complete){
                    console.log(complete);
                }
            }
        }, false);
        xhr.addEventListener("load", function(evt){
            console.log('服务器响应：',evt);
        }, false);
        xhr.addEventListener("error", function(evt){
            console.log(evt);
            info.html("文件上传错误");
        }, false);
        xhr.addEventListener("abort", function(){
            console.log(evt);
            info.html("文件上传失败");
        }, false);
        xhr.open("POST", "addPost");//修改成自己的接口
        xhr.send(fd);
        xhr.onreadystatechange = function() { 
            if (xhr.readyState == 4) { 
              if(xhr.status == 200){
                var data = JSON.parse(xhr.response);
                if(data.success){
                    var oLi = info.parent().parent();
                    //console.log(type)
                    if(type==1){
                        if(!complete){
                            oLi.find(".file_name").val(data.data.data);
                            oLi.find(".file_size").val(data.data.size);
                            oLi.find(".signature").val(data.data.signature);
                            var img = new Image();
                            img.src = '<?php echo $attachs?>' + data.data.data;
                            img.onload = function(){
                                //console.log('img.width:',img.width)
                                oLi.find(".img_width").val(img.width)
                                oLi.find(".img_height").val(img.height)
                            }
                            oLi.find(".files-img").show();
                            // oLi.find(".files-img").attr("src",'<?php echo $attachs?>' + data.data.data)
                            oLi.find("input[name='name[]']").val(file.name)
                            picFileReader(file,oLi);
                        }else{
                            var obj = new Object();
                            obj.size = data.data.size;
                            var img = new Image();
                            img.src = '<?php echo $attachs?>' + data.data.data;
                            img.onload = function(){
                                obj.img_width = img.width;
                                obj.img_height = img.height;
                                obj.url = '<?php echo $attachs?>' + data.data.data;
                                obj.data = data.data.data;
                                obj.signature = data.data.signature;
                                obj.file = file;
                                addUpload(obj)
                            }
                        }
                    }else if(type==2){
                        if(!complete){
                            oLi.find(".file_name").val(data.data.data);
                            oLi.find(".file_size").val(data.data.size);
                            oLi.find(".signature").val(data.data.signature);
                            creatVideo(data.data.data,oLi)
                            oLi.find("input[name='name[]']").val(file.name)
                        }else{
                            var obj = new Object();
                            obj.size = data.data.size;
                            obj.url = '<?php echo $attachs?>' + data.data.data;
                            obj.data = data.data.data;
                            obj.signature = data.data.signature;
                            obj.file = file;
                            addUpload(obj)
                        }
                    }else if(type == 'other'){
                        oLi.find(".other_file").val(data.data.data);
                    }
                }else{
                    layer.msg(data.msg);
                }
              }else{
                  layer.msg('通信错误!');
              } 
            }
        } 
      }

     // 批量弹窗
     function batchListTips(files,type){
        var tbody = ``;
        for(var i=0;i<files.length;i++){
            var file = files[i];
            var fileSize = 0;
            if (file.size > 1024 * 1024){
                fileSize = (Math.round(file.size * 100 / (1024 * 1024)) / 100).toString() + 'MB';
            }else{
                fileSize = (Math.round(file.size * 100 / 1024) / 100).toString() + 'KB';
            }
            tbody = tbody + `<tr>
                <td>`+ file.name +`</td>
                <td>`+ fileSize +`</td>
                <td class="file_state" id="file_state`+i+`">待处理</td>
                </tr>`;
        }
        var content = `<div style="padding:20px; box-sizing:border-box; width:100%; height:400px; overflow-x:hidden; overflow-y:auto;">
            <table id="files_table" class="layui-table">
            <colgroup>
                <col width="300">
                <col width="300">
                <col>
            </colgroup>
            <thead>
                <tr>
                <th>文件名称</th>
                <th>文件大小</th>
                <th>文件状态</th>
                </tr> 
            </thead>
            <tbody>
               `+ tbody +`
            </tbody>
            </table>
        </div>`;
        layer.open({
            type: 1
            ,offset: 'auto'
            ,area: ['960px', '600px']
            ,id: 'batchListTips' //防止重复弹出
            ,content: content
            ,btnAlign: 'r' //
            ,btn: ['点击上传']
            ,shade: 0.5 //不显示遮罩
            ,yes: function(index,layero){
                batchListAction(files,type);
                var btn = layero.find('.layui-layer-btn');
                btn.find('.layui-layer-btn0').hide();
                //layer.closeAll();
            }
        });
     }

     //批量上传文件
     function batchListAction(files,type){
        $('#files_table tbody .file_state').each(function(index,el){
            var id = $(this).attr('id')
            uploadFile(files[index],$("#"+id),type,'批量')
        });
     }

     function onfileSelected(t,type){
         $(t).parent().find('.fileupload-input').click();
     }


    //重新渲染form
    function renderLayuiForm(){
        layui.use('form', function(){
            var form = layui.form;
            form.render();
        });
    }

    //  
    function creatVideo(src,oLi){
        var video = document.createElement('video');
        var canvas = document.createElement('canvas');
        document.body.appendChild(video);
        document.body.appendChild(canvas);
        video.style.display = 'none';
        canvas.style.display = 'none';
        $(video).attr("src",'<?php echo $attachs?>'+src);
        video.onloadedmetadata = function(){
            $(oLi.find("input[name='duration[]']")).val(video.duration);
            printSc($(video),$(canvas),oLi);
        }
    }

    // 视频截图
    function printSc(video,canvas,oLi){
        setTimeout(function(){
            canvas.attr({
                width:video[0].videoWidth,
                height:video[0].videoHeight,
            });
            canvas[0].getContext('2d').drawImage(video[0], 0, 0, canvas[0].width, canvas[0].height);
            var base64 = canvas[0].toDataURL("image/jpeg");
            //video[0].pause();
            video.remove();
            canvas.remove();
            if(oLi){
                oLi.find("input[name='picture[]']").val(base64);
                oLi.find(".files-img").show();
                oLi.find(".files-img").attr("src",base64);
                //oLi.find(".thumb").val(canvas[0].toDataURL());
                oLi.find(".img_width").val(video[0].videoWidth);
                oLi.find(".img_height").val(video[0].videoHeight);
            }
        },1000);
    }
    
    // 图片读取 base64
    function picFileReader(files,oLi){
        var read = new FileReader() // 创建FileReader对像;
        read.readAsDataURL(files)  // 调用readAsDataURL方法读取文件;
        read.onload=function(){
            var base64 = read.result  // 拿到读取结果;
            oLi.find("input[name='picture[]']").val(base64);
            oLi.find(".files-img").attr("src",base64)
        }
    }

    // 添加素材组
    $(".addmaterialGroup").click(function(){
        addGroup();
    });


    // 素材组弹窗
    function addGroup(){
        var temp = `
            <br>
            <form class="layui-form" id="add_Group">
                <div class="layui-form-item">
                    <label class="layui-form-label long-label">素材组名称</label>
                    <div class="layui-input-inline ">
                        <input type="text" name="name" required  placeholder="" value="" class="layui-input" autocomplete="off">
                    </div>
                    <div class="layui-form-mid layui-word-aux">*</div>
                </div>
            </form>`;
        layer.open({
            title : '新增素材组',
            type: 1,
            area: ['500px', '200px'],
            shadeClose: true, //点击遮罩关闭
            content: temp,
            btn: ['保存', '取消'],
            yes: function(index, layero){
                var name = $("input[name='name']").val().replace(/\s+/g, "");
                if(!name){
                    layer.msg('素材组名称不能为空！')
                    return false;
                }
                var app_id = $("select[name='app_id']").find("option:selected").val();
                var arr = {
                    token : token ,
                    name : name ,
                    app_id : app_id
                }
              
                $.ajax({
                        url : addGroupUrl ,
                        async: false,
                        data : arr,
                        type : 'post',
                        dataType : 'json',
                        jsonp : 'callback',
                        success:function(data){
                            layer.msg(data.msg);
                            if(data.success){
                                layer.close(index); //如果设定了yes回调，需进行手工关闭
                                console.log(data.data);
                                // 重新渲染 select 
                                var opt = '<option value="'+data.data+'">'+ arr.name +'</option>';
                                $("#gid").append(opt);    
                                renderLayuiForm(); 
                            }
                        },
                        error:function(xhr,msg,e){
                            layer.msg(msg);
                        }
                    });
                    
            }
        });

    }




</script>