<?php echo $this->render("./spm/layout/header.phtml");?>
<link href="<?php echo $staticPath?>/css/spm/material.css?v=<?php echo $version;?>" rel="stylesheet" />
<style>
    .layui-btn-sm{
        margin-top: 10px;
    }
</style>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <!-- 头部区域 begin  -->
    <?php echo $this->render("./spm/layout/topMenu.phtml");?>
    <!-- 头部区域 end   -->

        <div class="content-wrap">
        <!-- leftMenu begin   -->
        <?php echo $this->render("./spm/layout/leftMenu.phtml");?>
        <!-- leftMenu begin   -->
        <div class="content-main">
            <div class="wrapper">
                <!-- title begin -->
                <div class="title">
                    <p>素材标签管理</p>
                </div>
                <!-- title end  -->
                <!-- 查询条件 begin -->
                <div class="query-condition">
                    <form class="layui-form" method="get" action="labelManage">
                        <div class="layui-form-item">
                            <div class="layui-input-inline">
                                <input type="text" name="label" placeholder="请输入标签查询" value="<?php echo $label;?>" class="layui-input" />
                            </div>
                            <div class="layui-input-inline">
                                <button type="submit" class="layui-btn layui-btn-normal" lay-submit lay-filter="search">查询</button>
                            </div>
                            <a class="right layui-btn layui-btn-normal" href="/Admin/Spm_Material/addLabel">新增/编辑标签</a>
                        </div>
                    </form>
                </div>

                <!-- 查询条件 end  -->
                <!-- 素材列表 begin-->
                <div class="material-wrap" style="overflow: hidden;">
                    <table class="layui-table">
                        <colgroup>
                            <col width="150">
                            <col width="200">
                            <col>
                        </colgroup>
                        <thead>
                        <tr>
                            <th>一级标签</th>
                            <th>二级标签</th>
                            <th>创建时间</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($list as $key=>$val){?>
                        <tr>
                            <td><p class="layui-btn layui-btn-radius layui-btn-primary"><?php echo $val['title'];?></p></td>
                            <td width="40%">
                                <?php
                                if(!empty($val['level2'])) {
                                    foreach ($val['level2'] as $keys => $vals) { ?>
                                        <p  class="layui-btn layui-btn-radius layui-btn-sm layui-btn-primary"><?php echo $vals['title'];?></p>
                                        <?php
                                    }
                                }
                                ?>
                            </td>
                            <td><?php echo $val['create_time'];?></td>
                        </tr>
                        <?php }?>
                        </tbody>
                    </table>
                </div>
                <!-- 素材列表 end-->
                <div id="page" style="padding-left: 40%;"></div>
            </div>
        </div>
        </div>
    </div>
</body>

</html>
<script>
    //JavaScript代码区域
    layui.use(['element', 'form', 'laydate', 'table', 'upload','laypage'], function () {
        var element = layui.element;
        var form = layui.form;
        var laydate = layui.laydate;
        var table = layui.table;
        var upload = layui.upload;
        var laypage = layui.laypage;

    });

    // 删除记录
    $(".delLabel").click(function(e){
        var id = $(this).attr('data-id');
        layer.confirm('是否确认删除', {icon: 3, title:'提示'}, function(index){
            $.ajax({
                url : 'delLabel',
                async: false,
                data : {id:id},
                type : 'get',
                    dataType : 'json',
                        jsonp : 'callback',
                        success:function(data){
                        layer.msg(data.msg);
                        if(data.success){
                            setTimeout(function(){
                                window.location.href = 'labelManage';
                            },500);
                        }
                },
                error:function(xhr,msg,e){
                    layer.msg(msg);
                }
            });
//            oLi.remove();
//            layer.close(index);
        });
       //
        // 阻止冒泡
        var ev = e || event;
        ev.stopPropagation();
        ev.preventDefault();
    });





  //重新渲染form
    function renderLayuiForm(){
        layui.use('form', function(){
            var form = layui.form;
            form.render();
        });
    }

    //   topMenu 切换app 回调
    var appIdSelectChange = {
        callBack:function(id){
           window.location.href = 'index';
        }
    };
</script>