<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>管理中心 Management center</title>
    <link rel="shortcut icon" href="<?php echo $staticPath;?>/img/favicon.ico" />
    <link href="<?php echo $staticPath?>/js/admin/lay/css/layui.css?v=<?php echo $version;?>" rel="stylesheet" type="text/css"/>
    <script src="<?php echo $staticPath?>/js/admin/lay/layui.js?v=<?php echo $version;?>"></script>
    <script src="<?php echo $staticPath?>/js/common/jquery.js?v=<?php echo $version;?>"></script>
    <style>
        body ,html{font-family:Helvetica Neue,Helvetica,PingFang SC,Tahoma,Arial,sans-serif}
        .layui-layout-admin .layui-body{ 
            left:0;
        }
        .layui-layout-admin .layui-footer{
            left:0;
            text-align: center;
            color:#666;
        }
        #blur{
            filter:blur(50px);
            -webkit-filter:blur(50px);
            -moz-filter:blur(50px);
            -ms-filter:blur(50px);
            -o-filter:blur(50px);
            width:100%; height:100%;
        }
        .bg-blur{ 
            position: absolute;
            left: 0;
            right: 0;
            top: 0;
            bottom: 0;
            z-index:1;
         }
         .bg{ position: absolute;
            left: 0;
            right: 0;
            top: 0;
            bottom: 0;
            z-index:2;
            background:url("<?php echo $staticPath;?>/img/banner.jpg") no-repeat center top;
            opacity:0.7; -o-opacity:0.7; -khtml-opacity:0.7; -webkit-opacity:0.7; 
            filter:alpha(opacity=70);
        }

        .system-wrap{ position: absolute; top:50%; left:50%; z-index:9999; padding-top:50px; box-sizing:border-box;  margin:-244px 0 0 -420px; width:840px; height:400px; background:#fff; border-radius:20px; -moz-border-radius:20px; -o-border-radius:20px; -webkit-border-radius:20px; -khtml-border-radius:20px; }
        .system-wrap .system-item{ float:left; display:inline-block; width:280px;  text-align: center;   }
        .system-wrap .system-item .system-item-logo{ width:120px; height:120px; }
        .system-wrap .system-item span{ display: block; color:#666; font-size:16px; margin-top:25px;   }
        .welcome{  float:left; width:90%; margin:20px 5% 0 5%; border-top:1px solid #eee; padding:50px; text-align: center; box-sizing:border-box; color:#666; font-size:20px; }
    </style>
</head>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <div class="layui-header">
        <div class="layui-logo">
            <img style="width:160px" src="<?php echo $staticPath;?>/img/logo.png" alt="mobgi" />
        </div>
        <ul class="layui-nav layui-layout-right">
        <li class="layui-nav-item">
            <a href="javascript:;">用户：<?php echo $user_name;?></a>
            <dl class="layui-nav-child">
            <dd><a href="<?php echo $passwdUrl;?>">修改密码</a></dd>
            <dd><a href="<?php echo $logout;?>">注销</a></dd>
            </dl>
        </li>
        </ul>
    </div>
    <!-- 内容主体区域  begin -->
    <div class="layui-body">  
        <div class="bg-blur">
            <img id="blur"  src="<?php echo $staticPath;?>/img/banner.jpg" alt="" />
        </div>
        <div class="bg"></div>
        <div class="system-wrap">
            <?php foreach($module as $val){ ?>
            <div class="system-item">
                <a href="<?php echo $val['url']; ?>">
                    <img class="system-item-logo" src="<?php echo $val['icon'];?>"  alt="<?php echo $val['name'];?>"/>
                </a>
                <span><?php echo $val['name'];?></span>
            </div>
            <?php } ?>
            
            <div class="welcome">
                欢迎回来，<?php echo $user_name;?>
            </div>

        </div>
    </div>
    <!-- 内容主体区域  end -->
    <div class="layui-footer" >
    @Copyright©2009-2017 深圳市创梦天地科技股份有限公司 版权所有 粤ICP备 13029562号
    </div>
</div>
</body>
<script src="../src/layui.js"></script>
<script>
//JavaScript代码区域
layui.use('element', function(){
  var element = layui.element;
  
});
</script>
</html>