<?php echo $this->render("layout/header1.phtml");?>
<div class="colMain">
    <div class="nav">
	<ul class="cc">
    	<li class="current"><a href="<?php echo $listUrl;?>">Sdk插件列表</a></li>
		<li><a href="<?php echo $addUrl;?>"><?php echo $navTitle;?></a></li>
	</ul>
	</div>
    <div class="main">
        <div class="toolbar">
            <div class="search fl">
                <form action="<?php echo $listUrl;?>" method="GET">       
                <div>
                     <label class="ig_label">平台：</label>
                     <ul class="ip_ul clearfix">
                        <li  class="<?php echo ($search['sdk_type'] == '')?'cur':'';?>"  > <a href="<?php echo $listUrl;?>?sdk_type=" >全部</a></li>
                        <li class="<?php echo ($search['sdk_type'] == 1)?'cur':'';?>" > <a href="<?php echo $listUrl;?>?sdk_type=1" >Android</a></li>
                        <li class="<?php echo ($search['sdk_type'] == 2)?'cur':'';?>" ><a href="<?php echo $listUrl;?>?sdk_type=2" >IOS</a></li>
                    </ul>
                    <input type="text" class="iText" name='name'  value='<?php echo $search['name'] ;?>' placeholder="可输入名称查询" />       
                    <input type="submit" class="submit" value="" 　/>
                </div>
                </form>
            </div>
        </div>
        <div class="content">
            <div class="grid">
                <table>
                    <thead>
                        <tr>
                            <th>平台</th>
                            <th>插件类型</th>
                            <th>排序</th>
                            <th>状态</th>
<!--                            <th>更新时间</th>-->
                            <th>操作</th>
                        </tr>
                    </thead>
                       <tbody>
                        <?php foreach($list as $k1=>$v1){?>
                        <tr>
                            <td><span class="blue"><?php echo  ($v1['sdk_type']==1)?'Android':'IOS'  ?></span></td>
                        	<td><?php echo $v1['name']; ?></td>
                    		<td><?php echo $v1['sort']; ?></td>
                    		<td>
                                <?php if($v1['status']){  ?>
                                    <span class="green">正常</span>
                                <?php }else{  ?>
                                    <span class="red">已下线</span>
                                <?php }  ?>
                            </td>
<!--                    		<td>--><?php //echo date('Y-m-d H:i:s',$v1['update_time']); ?><!--</td>-->
                            <td>
                                <a href="<?php echo$addUrl;?>/?id=<?php echo $v1['id'];?>" class="mr10">编辑</a>
                                <?php if($v1['status']){  ?>
                                    <a href="javascript:" onclick="changeStatus('<?php echo $changeStatusUrl;?>/?id=<?php echo $v1['id'];?>&status=0', '确认下线该条信息？', event);"　class="mr10">下线</a>
                                <?php }else{  ?>
                                    <a href="javascript:" onclick="changeStatus('<?php echo $changeStatusUrl;?>/?id=<?php echo $v1['id'];?>&status=1', '确认上线该条信息？', event);"　class="mr10">上线</a>
                                <?php }  ?>
                            </td>
                        </tr> 
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            <div class="mr10 mt10 cc tc"><?php echo $pager;?></div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(function(){


});
</script>
<?php echo $this->render("layout/footer1.phtml");?>