<?php echo $this->render("layout/header_layui.phtml");?>
<body>
    <div class="layui-fluid wrapper">
        <div class="layui-row layui-col-space30">
            <!-- left begin -->
            <?php echo $this->render("common/appinfo.phtml");?>
            <!-- left end  -->
            <!-- right begin  -->
            <?php echo $this->render("interative/conf/layout/right.phtml");?>
            <!-- right end   -->
        </div>
    </div>
</body>
<script>
    ;(function(){
        // 主页 数据 回调
        var mainCallback = {
            success:function(data){
                var app = data.data;
                if(data.success){
                    //初始化 mian 头部 信息
                    $("#main").find(".app-icon img").attr("src",app.icon);
                    $("#main").find(".app-name span").html(app.app_name);
                    $("#main").find(".app-key").html('AppKey：'+app.app_key);
                    $("#main").find(".app-type i").removeClass('ios');
                    $("#main").find(".app-type i").removeClass('android');
                    $("#main").find(".app-type i").addClass(app.platform_class);
                }else{
                    layer.msg(data.msg); 
                }
            },
            error:function(xhr,msg,e){
                layer.msg(msg); 
            } 
        };

        // 主页初始化
        function initMain(){
            var app_key = getQueryString('app_key');
            if(!app_key){
                var app =  $($(".appList li").get(0));
                $($(".appList li").get(0)).addClass("active");   
                app_key = app.find(".app-title").attr("data-app-key");
               $(".page_app_key").val(app_key);
            }else{
                $(".appList li").removeClass("active"); 
                var applist = $(".appList li");
                applist.each(function(){
                     var appKey = $(this).find(".app-title").attr("data-app-key");
                     if(appKey==app_key){
                          $(this).addClass("active");   
                     }
                });
                renderLayuiForm();
            }
            $(".app-key").attr("data-app-key",app_key);
            var url = baseurl + '<?php echo $getPosListUrl;?>?app_key=' + app_key;
            requestAjax({url:url},mainCallback);
         }

        initMain();  // 初始化主页
    })();
</script>
</html>
