<?php echo $this->render("layout/header1.phtml");?>
<div class="colMain">
    <div class="nav">
	<ul class="cc">
    	<li class="current"><a href="<?php echo $listUrl;?>">常见问题列表</a></li>
		<li><a href="<?php echo $addUrl;?>"><?php echo $navTitle;?></a></li>
	</ul>
	</div>
    <div class="main">
        <div class="toolbar">
            <div class="search fl">
                <form action="<?php echo $listUrl;?>" method="GET">       
                <div>         
                     <label class="ig_label">类型：</label>
                     <ul class="ip_ul clearfix">
                        <li  class="<?php echo ($search['sdk_type'] == '')?'cur':'';?>"  > <a href="<?php echo $listUrl;?>?tab_type=3&sdk_type=" >全部</a></li>
                        <li class="<?php echo ($search['sdk_type'] == 1)?'cur':'';?>" > <a href="<?php echo $listUrl;?>?tab_type=3&sdk_type=1" >Android</a></li>
                        <li class="<?php echo ($search['sdk_type'] == 2)?'cur':'';?>" ><a href="<?php echo $listUrl;?>?tab_type=3&sdk_type=2" >IOS</a></li>
                    </ul>
                    <input type="text" class="iText" name='name'  value='<?php echo $search['name'] ;?>' placeholder="可输入名称查询" />       
                    <input type="submit" class="submit" value="" 　/>
                </div>
                </form>
            </div>
        </div>
        <div class="content">
            <div class="grid">
                <table>
                    <thead>
                        <tr>  
                          <th>tab类型</th>
                            <th>SDK类型</th>
                             <th>更新時間</th>
                            <th>操作</th>       
                        </tr>
                    </thead>
                       <tbody>
                        <?php foreach($list as $k1=>$v1){?>
                        <tr>
  							<td><span class="blue"><?php echo  ($v1['tab_type']==1)?'常见问题':'接入流程'  ?>  </span></td>
                          	<td><span class="blue"><?php echo  ($v1['sdk_type']==1)?'Android':'IOS'  ?>  </span></td>
                    		<td><?php echo date('Y-m-d H:i:s',$v1['update_time']); ?></td>   
                            <td>
                                    <a href="<?php echo$addUrl;?>/?id=<?php echo $v1['id'];?>" class="mr10">编辑</a>
									<a href="<?php echo $viewUrl;?>/?id=<?php echo $v1['id'];?>" class="mr10">查看</a>
									<a href="javascript:" onclick="deleteOne('<?php echo $deleteUrl;?>/?id=<?php echo $v1['id'];?>', '', event);"　class="mr10">删除</a>
                            </td>
                        </tr> 
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            <div class="mr10 mt10 cc tc"><?php echo $pager;?></div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(function(){


});
</script>
<?php echo $this->render("layout/footer1.phtml");?>