<div class="setbkco">
            <div class="resetpwd_content register_content">
                <table>
                    <tr>
                        <td class="txtrig">邮箱</td>
                        <td><input type="text" class="inpu_sty email"/></td>
                    </tr>
                    <tr>
                        <td class="txtrig">密码</td>
                        <td class="tab_tdsty"><input type="password" class="pw pw1" /></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td class="zs">密码长度6-15，支持数字、字母和“-”</td>
                    </tr>
                    <tr>
                        <td class="txtrig">确认密码</td>
                        <td><input type="password" class="tInput pw pw2" /></td>
                    </tr>
                    <tr>
                        <td class="txtrig">验证码</td>
                        <td class="tab_tdsty">
                            <input type="text" class="code_sty cap" value="" autocomplate="off" />
                            <span id="code"><img src="/captcha/default" width="100" height="42" alt="Captcha" class="captcha changeCode" /></span>
                            <a class="blue changeCode">换一张</a>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td class="padtop">
                        <input type="checkbox" class="checkxy checkbox" checked="true"/>我已阅读并接受<a href="javascript:;" id="user_agreement" class='blue'>《用户协议》</a><br />
                        <input type="button" value="立即注册" class="btn_qd doRegister"/></td>
                    </tr>
                </table>
            </div>
        </div>
<div class="user_agreement" style="display:none;">
  <strong>磨基平台开发者协议</strong>
  <p class="tr">（2014年06月13日版）</p>
  <p style="font-size:16px;color:#333;">尊敬的开发者：</p>
  <br />
  <p>欢迎注册磨基广告平台。请您（以下简称“您”或“开发者”）仔细阅读以下全部内容（以下简称“本协议”），如您不同意本协议中的任何内容，请勿注册或继续使用磨基广告平台。您勾选“我已阅读并接受”《磨基广告平台开发者协议》的行为即表示您完全接受本协议所有条款的约束。</p>
  <p class="t">一、定义</p>
  <p>1.1、“磨基”，指磨基广告平台的开发、所有及运营方，以下简称“本平台”。</p>
  <p>1.2、“磨基广告平台”，指由磨基开发、所有并运营的移动广告平台。</p>
  <p>1.3、“服务”，指磨基通过磨基广告平台提供的各种服务。</p>
  <p>1.4、“开发者”，指接入磨基广告平台的SDK网站、应用程序等的所有人或拥有使用权人。</p>
  <p>1.5、“开发者推广渠道”，指开发者所有的或有使用权及运营权的包括但不仅限于网站、应用程序等，该网站或应用程序等可接入磨基的SDK或可在该等渠道上展示广告内容。</p>
  <p>1.6、“广告主”，指使用磨基广告平台，将其广告内容放在开发者推广渠道上推广的人。</p>
  <p>1.7、“广告内容”，指广告主通过磨基广告平台在开发者推广渠道上发布的广告内容，包括但不限于图片、文字、软件、链接。</p>
    
    <p class="t">二、服务条款</p>
    <p>2.1、磨基广告平台的服务内容由磨基根据实际情况向开发者提供。在开发者遵守本协议的前提下，磨基在此授予开发者限制性的、非独家的、不可转让的、不可再授权的权利来使用本平台的服务。</p>
    <p>2.2、磨基保留在不通知开发者的情况下，有权暂时性或永久性地在任何时候修改或停止本平台相关服务的全部或部分。开发者同意磨基就本平台相关服务所做的任何修改、延展或停止不承担任何责任。</p>
    <p>2.3、本平台有权在必要时对本协议进行修改，包括但不限于对平台的服务内容以及广告定价收费、广告收入分成比例进行调整，并无需通知开发者。开发者若需继续与本平台合作，须要完全接受修改后的协议内容。</p>
    
    <p class="t">四、使用规则</p>
    <p>4.1、开发者在申请注册磨基广告平台后，须向磨基提供准确的资料。如开发者使用本平台服务期间资料（邮箱、联系方式、账户信息等）有所变更，应及时更新信息，否则对于可能造成的损失将由开发者自行承担。</p>
    <p>4.2、开发者应当妥善保管自己的帐号和密码，并对以其帐号进行的所有活动和事件负法律责任。</p>
	<p>4.3	开发者在使用本平台的过程中应当遵守中华人民共和国相关法律法规。开发者不得提交包含以下内容的应用程序或网站等，否则由开发者自行承担全部责任，如给磨基造成损失的，还应赔偿磨基全部损失：
        •违反国家宪法所规定的基本原则的;<br>
        •危害国家安全，泄露国家秘密，颠覆国家政权，破坏国家统一的;<br>
        •损害国家荣誉和利益的;<br>
        •煽动民族仇恨、民族歧视，破坏民族团结的;<br>
        •破坏国家宗教政策，宣扬邪教和封建迷信的;<br>
        •散布谣言，扰乱社会秩序，破坏社会稳定的;<br>
        •散布淫秽、色情、赌博、暴力、凶杀、恐怖或者教唆犯罪的;<br>
        •侮辱或者诽谤他人，侵害他人合法权益的;<br>
        •含有法律、行政法规禁止的其他内容的;
</p>
	<p>4.4、开发者不得用任何不正当手段损害本平台的利益及声誉,不得利用非正规途径获得广告展示和点击、安装等。不正当手段包括但不限于技术模拟点击下载广告、人工唆使他人点击下载广告等获得虚假数据，本平台一旦发现开发者有前述行为,有权封锁帐号并且不予结算。</p>
	   
    <p class="t">五、期限与终止</p>
    <p>5.1、本协议期限自开发者使用本平台或开始接受本平台相关服务开始，除本协议明确约定的提前终止的情形外，本协议将永久性持续有效。本协议终止后，开发者应立即停止使用本平台及/或其服务。在本协议终止后，本协议第1, 3, 5, 6, 7, 8,和9条仍然有效。</p>
    <p>5.2、如因系统维护或升级的需要而需暂停服务，本平台将尽可能事先在重要页面进行通告。如发生以下任何一种情形，本平台有权随时中断或终止向开发者提供服务而无需通知开发者：
•开发者提供的资料不真实
•开发者违反本协议中规定的使用规则。
</p>
    <p>5.3、除前款所述情形外，本平台同时保留在不事先通知您的情况下中断或终止部分或全部服务的权利，对于所有服务的中断或终止而造成的任何损失，本平台无需对开发者或任何第三方承担任何责任。</p>

    <p class="t">六、免责申明</p>
    <p>6.1、开发者同意使用本平台服务所存在的风险将完全由自己承担；因其使用本平台服务而产生的一切后果也由开发者自行承担，本平台对开发者不承担任何责任。</p>
    <p>6.2、本平台不保证服务一定能满足开发者的要求，也不保证服务不会中断，对服务的及时性、安全性、准确性也都不作保证。开发者存放在本平台的文件，本平台不承担任何风险责任。</p>
	<p>6.3、本平台不对任何广告主提供的广告内容承担任何责任。如产生与广告内容相关的纠纷，开发者应当联系广告主解决。</p>
	
    <p class="t">七、违约赔偿</p>
    <p>7.1、开发者同意保障和维护本平台的利益，如因开发者违反有关法律、法规或协议规定中的任何条款而给本平台或任何其他第三方造成损失，开发者同意承担由此造成的损害赔偿责任。</p>

    <p class="t">八、通知</p>
    <p>8.1	本协议下所有通知应以如下方式发出：（a）向本平台发出的通知，应以要求回执的电子邮件的形式向磨基电子邮箱 【mobgi@idreamsky.com】 发出，该等通知在磨基收到时生效。（b）向开发者发出的通知，应以页面公告或向开发者提供的电子邮箱地址发送电子邮件的形式发出，该等通知在发出时即生效。</p>

    <p class="t">九、通则</p>
    <p>9.1、开发者有义务履行保密义务，不得向任何第三方披露或者透露有关本协议项下内容的任何信息及因履行本协议而获知的本平台或磨基的商业秘密，但根据有关法律规定向有权机构（如政府执法部门或司法机构）必须披露的除外。</p>
    <p>9.2、本协议受中国法律的约束。《联合国国际货物销售合同公约》不适用于本协议。所有本协议的争议应提交深圳仲裁委员会按照该仲裁机构的仲裁规则进行仲裁, 双方同意该仲裁机构就本协议所有争议事项具有不可撤销的管辖权。</p>
    <p>9.3、若本协议中任何条款被具有司法管辖权的机构认定为无效、违法或不可执行，则其他条款仍继续有效。</p>
    <p>9.4、未经磨基事先书面授权，开发者不得将本协议任何权利义务转让或转移，否则，该等转让、转移无效。</p>
    <p>9.5、磨基有权在未来任何时间在不发出通知的情况下修改更新本协议。开发者随时获知更新是开发者的义务，且开发者是被本协议的最新版本约束。</p>
    <p>9.6、本协议解释权归磨基所有。</p>
    </div>
<script type="text/javascript">
$(function(){
    $(".email").mailAutoComplete({left:0,width:300});
    $("#user_agreement").click(function(){
        var $c = $('<div style="width:774px;height:514px;text-align:left;overflow-x:hidden;overflow-y:auto;line-height:24px;border:1px solid #e7e7e7;position:relative;left:-60px;top:-28px;background-color:#ffffff;"></div>');
        $c.html($(".user_agreement").clone());
        $c.children().show();
        jDialog({
            content:$c,
            mask:true,
            width:800,
            height:600,
            button:{'ok':{'name':'确定',"className":"btn-s"}},
       });
    })
    // 点击输入密码框时
    $(".email").live("focusin", function(){
        if ($(this).val() == "请输入邮箱"){
            $(this).val("").removeClass("gray");
        }
    }).live("focusout", function(){
        if ($(this).val().trim().length <= 0){
            $(this).val("请输入邮箱").addClass("gray");
        }
    });
    // 检查邮箱格式
    $(".pw1").live("focusin", function(){
        if (!isEmail($(".email").val())){
            info('邮件格式不正确', 'error');
            $(".email").next('span').removeClass("ok").addClass("error");
            return false;
        }else{
            $(".email").next('span').removeClass("error").addClass("ok");
        }
    });
    // 刷新验证码
    $(".changeCode").click(function(){
        captcha();
    });
    $(".doRegister").live("click",function(){
        var pass1 = $.trim($(".pw1").val());
        var pass2 = $.trim($(".pw2").val());
        var email = $.trim($(".email").val());
        var cap = $.trim($(".cap").val());
        if (!isEmail(email)){
            info('邮件格式不正确', 'error');
            return false;
        }
        if ( pass1.length < 6 || pass1.length > 15){
            info("密码长度为6-15位", 'error');
            return false;
        }
        if (pass1 != pass2){
            info("两次密码不一致", 'error');
            return false;
        }
        if (!$(".checkbox").attr("checked")){
            info("您尚未选择接受《用户协议》", 'error');
            return false;
        }
        if (cap.length != 4){
            info("验证码错误", 'error');
            return false;
        }
        $(this).css("background-color","rgb(153, 153, 153)");
        $(this).val("正在注册......");
        $(this).attr("disabled",true);
        
        // post
        ajaxPOST("/register/doRegister",{ email : email, password : md5(pass1), captcha: cap },function(result){
            if (result.error == -1) {
                $(".doRegister").val("立即注册");
                $(".doRegister").css("background-color","");
                $(".doRegister").attr("disabled",false);
                captcha();
                info(result.msg, 'error');
            }else{
                window.location.href="/register/active?email="+email;
            }
        });
    });
});
</script>