<?php echo $this->render("layout/header_layui.phtml");?>
<body>
    <div class="layui-fluid wrapper">
        <div class="layui-row layui-col-space30">
            <div class="items-wrap wrap-bg space-top mian-h">
                <!-- titile begin -->
                <div class="layui-tab layui-tab-brief">
                    <ul class="layui-tab-title">
                        <li class="layui-this"><a href="<?php echo $listUrl;?>">兑换码列表</a></li>
                        <li><a href="<?php echo $addUrl;?>">添加兑换码</a></li>
                    </ul>
                </div>
                <!-- titile end  -->
                <!-- search begin -->
                <div class="temp-search-wrap">
                    <form class="layui-form" action="<?php echo $listUrl;?>" method="GET"  id="searchForm" >
                        <div class="layui-form-item">
                            <label class="layui-form-label">商品</label>
                            <div class="layui-input-inline">
                                <select id="goods_id"  name="goods_id" lay-verify="" lay-search >
                                    <option value="">全部</option>
									<?php foreach($goodsList as $k1=>$v1){ ?>
                                        <option value="<?php echo $k1; ?>"  <?php if( $search['goods_id']==$k1 ){ ?> selected <?php } ?> ><?php echo $v1; ?></option>
									<?php } ?>
                                </select>
                            </div>
                            <div class="layui-input-inline">
                                <input type="text" name="code" placeholder="请输入兑换码" class="layui-input" value="<?php echo $search['name']; ?>">
                            </div>
                            <div class="layui-input-inline">
                                <button  class="layui-btn layui-btn-normal">查询</button>
                            </div>
                            <a id="upload-temp" type="button" class="floatright layui-btn layui-btn-normal" href="<?php echo $addUrl;?>">添加兑换码</a>
                        </div>
                    </form>
                </div>
                <!-- search  end  -->
                <!-- table begin -->
                <div class="layui-form-item">
                    <table class="layui-table">
                        <colgroup>
                            <col width="150">
                            <col width="200">
                            <col>
                        </colgroup>
                        <thead>
                            <tr>
                                <th>id</th>
                                <th>商品类型</th>
                                <th>所属商品</th>
                                <th>兑换码</th>
                                <th>状态</th>
                                <th>创建时间</th>
                                <th>使用时间</th>
                            </tr> 
                        </thead>
                        <tbody>
                          <?php foreach ($goodsCodelist as $val){?>
                            <tr>
                                <td><?php echo $val['id'];?></td>
                                <td><?php echo $goodsType[$val['type']];?></td>
                                <td><a href="<?php echo $goodsListUrl.'?title='.$goodsList[$val['goods_id']];?>"><?php echo $goodsList[$val['goods_id']];?></a></td>
                                <td><?php echo $val['code'];?></td>
                                <td><?php echo $codeStatus[$val['status']];?></td>
                                <td><?php echo $val['create_time'];?></td>
                                <td><?php echo $val['update_time'];?></td>
                            </tr>
                              <?php }?>
                        </tbody>
                    </table>
                </div>
                <!-- table end -->
                <div class="mr10 mt10 cc tc"><?php echo $pager;?></div>
            </div>
        </div>

    </div>
</body>
<script>
;(function(){
 // 删除 
    $(".layui-table").delegate(".link-delete","click",function(){
        var id = $(this).attr("data-id");
        var that = $(this);
        var data =  {
            id : id,
            token : token,
        }
        layer.confirm('确认是否要删除?', {icon: 3, title:'提示'}, function(index){
            $.ajax({
                url : baseurl + '<?php echo $deleteUrl?>' ,
                async: false,
                data : data,
                type : 'post',
                dataType : 'json',
                jsonp : 'callback',
                success:function(data){
                    layer.close(index);
                    layer.msg(data.msg);
                    if(data.success){
                        that.parent().parent().remove();
                    }
                },
                error :function(xhr,msg,e){
                    layer.close(index);
                    layer.msg(msg); 
                }
            });
           
        });
    });
})();
</script>
</html>