<?php echo $this->render("layout/header_layui.phtml");?>
<body>
<div class="layui-fluid wrapper">
    <div class="layui-row layui-col-space30">
        <div class="items-wrap wrap-bg space-top mian-h">
            <!-- titile begin -->
            <div class="layui-tab layui-tab-brief">
                <ul class="layui-tab-title">
                    <li ><a href="<?php echo $listUrl;?>">商品列表</a></li>
                    <li class="layui-this"><a href="<?php echo $viewUrl;?>"><?php echo $info['id']?'编辑':'添加'; ?>商品</a></li>
                </ul>
            </div>
            <!-- titile end  -->
            <div class="temp-upload-wrap">
                <form class="layui-form" action="" method="POST"  id="addForm">
                    <div class="layui-form-item">
                        <label class="layui-form-label">商品分类</label>
                        <div class="layui-input-inline" style="z-index:9999;">
                            <select id="type"  name="type" lay-verify="required" lay-search lay-filter="goods_type" disabled>
                                <option value="">全部</option>
								<?php foreach($goodsType as $k1=>$v1){ ?>
                                    <option value="<?php echo $k1; ?>"  <?php if( $info['type']==$k1 ){ ?> selected <?php } ?> ><?php echo $v1; ?></option>
								<?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">商品标题</label>
                        <div class="layui-form-mid layui-word-aux">
							<?php  echo $info['title'];  ?>
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">状态</label>
                        <div class="layui-input-inline">
                            <input type="checkbox" 　<?php echo $info['status'] ? ' checked=""' : ''; ?>  name="status" disabled
                                   lay-skin="switch" lay-filter="switchStatus" lay-text="上架|下架">
                        </div>
                    </div>
                    <div class="layui-form-item ">
                        <label class="layui-form-label">有效时间</label>
                        <div class="layui-input-inline">
                            <input type="hidden" name="start_time" class="start_time" class="layui-input" value="<?php echo $info['start_time'];?>">
                            <input type="hidden" name="end_time" class="end_time" class="layui-input" value="<?php echo $info['end_time'];?>">
                            <input type="text" name="date" class="layui-input" id="date" placeholder="有效时间" value="<?php echo $info['start_time'];?> - <?php echo $info['end_time'];?>" disabled>
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">商品说明</label>
                        <div class="layui-input-inline">
                            <textarea id="desc" name="desc" style="width:1000px;height:240px;" placeholder="请输入内容" class="layui-textarea"><?php echo $info['desc']; ?></textarea>
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">大图</label>
                        <div class="layui-upload layui-input-block" >
                            <div class="layui-upload-list">
                                <input type="hidden" name="big_img" value="<?php  echo $info['big_img'];  ?>" />
                                <img class="layui-upload-img" width="100px" height="100px" src="<?php echo $info['id']?$attachPath.$info['big_img']:'' ?>">
                                <p> </p>
                            </div>
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">icon</label>
                        <div class="layui-upload layui-input-block" >
                            <div class="layui-upload-list">
                                <input type="hidden" name="icon" value="<?php  echo $info['icon'];  ?>" />
                                <img class="layui-upload-img" width="100px" height="100px" src="<?php echo $info['id']?$attachPath.$info['icon']:'' ?>" >
                                <p></p>
                            </div>
                        </div>
                    </div>

                    <div class="layui-form-item">
                        <label class="layui-form-label">库存</label>
                        <div class=layui-form-mid layui-word-aux">
						<?php  echo intval($info['stock']);  ?>
                    </div>
            </div>

            <hr class="layui-bg-gray">
            <div class="layui-form-item">
                <div class="layui-input-block">
                    <button class="layui-btn layui-btn-big layui-btn-primary cannel" type="button">取消</button>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
</div>
</body>

<link media="all" rel="stylesheet" type="text/css" href="<?php echo $staticPath; ?>/js/umeditor/themes/default/css/umeditor.css" />
<!--<script type="text/javascript" src="--><?php //echo $staticPath; ?><!--/js/umeditor/third-party/jquery.min.js"></script>-->
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/umeditor/third-party/template.min.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/umeditor/umeditor.config.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/umeditor/umeditor.js"></script>
<script type="text/javascript" src="<?php echo $staticPath; ?>/js/umeditor/lang/zh-cn/zh-cn.js"></script>
<script>
    ;(function(){

        //实例化编辑器
        var um = UM.getEditor('desc',{
            'imageUrl': "<?php echo $uploadDescImgUrl; ?>?token="+token, //图片上传提交后台对应的地址
            // toolbar:['source','insertcode',],
        });

        //取消按钮
        $(".cannel").click(function(){
            window.location.href= baseurl +'<?php echo $listUrl;?>';
        });
        layui.use('laydate', function(){
            var laydate = layui.laydate;
            laydate.render({
                elem: '#date'
                ,range: true
                ,done: function(value, date, endDate){
                    $('.start_time').val(date.year+'-'+date.month+'-'+date.date);
                    $('.end_time').val(endDate.year+'-'+endDate.month+'-'+endDate.date);
                }
            });
        });

    })();
</script>